### ISSUE TITLE
2.0 Serial Module Feature Request: MeshAPI over UART via protos mode

### ISSUE THREAD

**Issue by caveman99** [meshtastic/firmware#1204]
Expose the client API over a (compile time configurable) serial interface. Either HW Serial Number or RX/TX Pins. This way another Microcontroller can access the API and facilitate the creation of a standalone device.

The Combination RAK5005 Base/RAK4631 Core/RAK2305 IO would be a first platform to implement this on, nRF52 core for meshtastic and an ESP32 for the application, doing screen and an I2C keyboard. 

Apart from that, this would be useful for any integration with existing applications, microcontroller or more high-level hardware.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/rak5860-for-mqtt-internet-connectivity/3464/8

**Comment by mc-hamster** [comment]
> Expose the client API over a (compile time configurable) serial interface. Either HW Serial Number or RX/TX Pins. This way another Microcontroller can access the API and facilitate the creation of a standalone device.
> 
> The Combination RAK5005 Base/RAK4631 Core/RAK2305 IO would be a first platform to implement this on, nRF52 core for meshtastic and an ESP32 for the application, doing screen and an I2C keyboard.
> 
> Apart from that, this would be useful for any integration with existing applications, microcontroller or more high-level hardware.

Plumbing for this is in the serial plugin. Next step is to create a new instance of the phone api and pass it over. Very likely just need to mirror what's used now for the primary interface, minus the debug logging.

**Comment by garthvh** [comment]
Should use the new protos mode https://github.com/meshtastic/Meshtastic-protobufs/blob/cb2fb77bd8c2751e82b1017cd7545789a037fb7d/module_config.proto#L88

**Comment by garthvh** [comment]
Done, being used
