### ISSUE TITLE
Enhancement: add PMSA003I sensor

### ISSUE THREAD

**Issue by mkinney** [meshtastic/firmware#1285]
User Johnny Danger in Discord would like to use sensor PMSA003I in Telemetry (Environmental Measurement)

**Comment by mkinney** [comment]
https://www.adafruit.com/product/4632

**Comment by sachaw** [comment]
Protobufs not required

**Comment by garthvh** [comment]
Sensor ordered

**Comment by garthvh** [comment]
I think this is going to need protos as the plan currently is to add an additional telemetry one of.

**Comment by caveman99** [comment]
This needs protos for sure. Add the sensor to the enum for support and define new data points for the measurements. It's a low rate sensor, so implementation should be straightforward.

**Comment by garthvh** [comment]
Done
