### ISSUE TITLE
[Feature Request] Geofencing support

### ISSUE THREAD

**Issue by dhubitetackle** [meshtastic/firmware#1426]
I need geofencing capability for my project,
I would like a way to define coordinate bounds on a node, and if that node gets a gps fix outside of those bounds, trigger the external notifications plugin and broadcast a message.

**Comment by imkebe** [comment]
I think more flexible would be implementation of some kind rules/scripts manager. I'm thinking about the same idea however I also want to use external gyroscope module to trigger additional action (message to channel/mqtt)

https://github.com/berry-lang/berry might be an idea. Then we could share recipies for various use cases (like geofencing)

**Comment by garthvh** [comment]
This seems like something that would be implemented in a client not on device.
