### ISSUE TITLE
1.3 [Feature Request]: nRF52 support for Range Test module sender

### ISSUE THREAD

**Issue by charminULTRA** [meshtastic/firmware#1451]
I would like to see nRF52 support for the Range Test module, especially as these devices are becoming more popular. Additionally, since the stock PCB antenna for the RAK 4631 is a PCB antenna with only uFL connector, typical VSWR measurement tools cannot be used without special adapters.

**Comment by mc-hamster** [comment]
> I would like to see nRF52 support for the Range Test module, especially as these devices are becoming more popular. Additionally, since the stock PCB antenna for the RAK 4631 is a PCB antenna with only uFL connector, typical VSWR measurement tools cannot be used without special adapters.

What would be the minimum support you'd like to see by the Range Test Module on the RAK?

**Comment by charminULTRA** [comment]
> > I would like to see nRF52 support for the Range Test module, especially as these devices are becoming more popular. Additionally, since the stock PCB antenna for the RAK 4631 is a PCB antenna with only uFL connector, typical VSWR measurement tools cannot be used without special adapters.
> 
> What would be the minimum support you'd like to see by the Range Test Module on the RAK?

I think Sender functionality would be a good minimum, since testing send capability/range would probably be more of a question mark than receive.  Additionally, I imagine the File Browser access for rangetest.csv (for the Receive role) might be more complicated/time-consuming to implement without WiFi, but I'm just speculating as a non-technical person.

**Comment by mc-hamster** [comment]
Sender can be added as a minimum. Sure. That should be possible.

**Comment by alistair23** [comment]
The entire range test module is ESP32 only: https://github.com/meshtastic/firmware/blob/master/src/modules/esp32/RangeTestModule.cpp

But the code also contains `#ifdef ARCH_ESP32`. Could the file not be built for all targets (with some changes to the current code)? That should be a good start towards send support on other platforms.
