### ISSUE TITLE
new role = "client_all_on"

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/firmware#1481]
Create a new client role where settings are always on.

settings:
   screen_on_secs = xxxx

**Comment by thebentern** [comment]
I believe 31536000 was the arbitrarily large value chosen from the discourse group originally, which I think is equal to one year. The maximum value or an entirely new "always on" style setting would be my preference.

**Comment by garthvh** [comment]
What would be included in this that is not a part of the Router_Client role?

**Comment by garthvh** [comment]
Cleaning up RouterClient to work right is the preferred path for this.
