### ISSUE TITLE
[Feature request] Add ability to delete/remove individual nodes from nodedb

### ISSUE THREAD

**Issue by tropho23** [meshtastic/firmware#1761]
Request ability to delete/remove individual nodes from nodedb, rather than clearing the entire database. It is useful to keep some historical nodes in the database, such as those for lost devices, old devices that may come online again (such as fixed nodes with dead batteries).

Since `--set reset-nodedb` is currently used for clearing nodedb, recommend syntax `--set remove-nodedb <node name>` or similar.

I do not recommend allowing manually _adding_ nodes as that could be considered tainting or 'poisoning' the node database with false or incorrect node information.

**Comment by tropho23** [comment]
I forgot to add that this should allow app developers to call this possibly admin message, to add actions for removing nodes withing the iOS and Android apps.

**Comment by caveman99** [comment]
There's a recent addition to throw out the oldst node in the db if it is full. Would that be a good low key alternative?

**Comment by tropho23** [comment]
No, but this feature request is an extension of that exact feature.  Just looking for a means to remove stale nodedb info selectively without deleting all nodedb info, if that is possible.  The current reset-nodedb feature works great...from a wipe-it-all perspective :)

**Comment by tavdog** [comment]
So the first step here would be to implement this is firmware, triggerable via cli, then add trigger to the UI of android and ios.  A function in the firmware would take the node id number and delete it from memory and delete it from flash.

I'm looking through the code now.

**Comment by garthvh** [comment]
You would create an admin message in the protobufs that can be consumed by any client

**Comment by tavdog** [comment]
> You would create an admin message in the protobufs that can be consumed by any client

Yes now I see it would require modifying the adminMessage protobuf.  Is it frowned upon to go modifying the protobuf definitions for small features such as this ?

**Comment by tropho23** [comment]
Excellent!  I'm happy to see this closed and completed 🙂

Tony
________________________________
