### ISSUE TITLE
Feature suggestion: Canned Messages extension to send extra message types

### ISSUE THREAD

**Issue by lesykm** [meshtastic/firmware#1791]
It would be useful to have ability to send canned messages:
1) to different channels like "admin", "gpio", just arbitrary index number, etc
2) other types rather then text (for example, remote hardware type)

Usecases:
1. using hw keyboard lically reboot remote node by pressing on abutton
2. change remote node setting by pressing on local keyboard
3. read/write remote gpio by keypress
4. etc

**Comment by garthvh** [comment]
The admin or GPIO channels are not for messaging.
