### ISSUE TITLE
[Board]: PICOmputer RP2040+RFM95+ST7789+QWERTY

### ISSUE THREAD

**Issue by bobricius** [meshtastic/firmware#1832]
### SOC

Other

### Lora IC

RFM95

### Product Link

http://pemi.technology/PICOmputer

### Description

After years I am not able to make any working reliable code.
It is based on Raspberry pi PICO or PICO W with RFM95 module
suport various spi ST7789 based displays 240x240, 320x240 or 280x240
there is also 30/36btn keyboard organized in 6x5 or 6x6matrix
I can send assembed hardware for testing.
Thanks

**Comment by caveman99** [comment]
The problem is that RP2040 target being highly experimental. It's not something that has ever been seen working.

**Comment by caveman99** [comment]
Our firmware already supports all components of these boards, it's just nobody was able to make it run. RP2040 toolchain is included, RFM95 (Aka SX1276) is supported, ST7789 is included (it works on my wiphone) and the cardKB querty keyboard is in the code as well. So if you wanna have a dig  at it, it should not be that difficult to accomplish.

**Comment by bobricius** [comment]
I am awful programmer (I do something in Arduino IDE), I can provide hardware for somebody who can make port. It makes no sense to write code from the beginning.

**Comment by sachaw** [comment]
There's always time to improve, we have a huge community that would be willing to help with the bits you get stuck on.

**Comment by sachaw** [comment]
There's always time to improve, we have a huge community that would be willing to help with the bits you get stuck on.

**Comment by garthvh** [comment]
@bobricius I think we could get your original ESP32 version working pretty quickly compared to the pico.

**Comment by bobricius** [comment]
@garthvh yes but pico have some advantages, I spend about year to to design this device and make versatile low power computer but everybody want meshtastic integration.

**Comment by garthvh** [comment]
> @garthvh yes but pico have some advantages, I spend about year to to design this device and make versatile low power computer but everybody want meshtastic integration.

With the ESP32 device the main issue is getting the screen working, with the PICO you need everything so it is going to be a ways out.

**Comment by bobricius** [comment]
If I create nice looking I2C keyboard with this PICOmputer style for T-echo can anybody help with software integration ?

**Comment by garthvh** [comment]
> If I create nice looking I2C keyboard with this PICOmputer style for T-echo can anybody help with software integration ?

Sure, would work with any meshtastic device

**Comment by bobricius** [comment]
I think all smarter chips are affected with chip crisis, specially atmega, stupid chips not need special programing, just solder + solder bunch of switches

**Comment by puzzled-pancake** [comment]
> If I create nice looking I2C keyboard with this PICOmputer style for T-echo can anybody help with software integration ?

Another good idea for a target would be the RAK4631 as its already very well supported at a lower cost

**Comment by bobricius** [comment]
I am big fan on raspberry Pi Pico, keyboard + T-echo is easy way how to create communicator with average soldering skills.

But if someone would be willing to make a port for PICOmputer,
**I can supply the necessary hardware + money donation after successful port 300$ ??? **

**Comment by caveman99** [comment]
MCP23018 would require constant scanning for keypresses, which is considerably more IO activity on the bus than just periodically reading a latch register. There are reasons why these atmega8 thingies exist :-)
