### ISSUE TITLE
[Bug]: Negative values in NMEA position sentence

### ISSUE THREAD

**Issue by samuelhj** [meshtastic/firmware#1928]
### Category

Serial

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.0.0.18ab874-d

### Description

Using serial module in NMEA mode the sentence reports negative value on longitude. This causes the Garmin device (or any other NMEA0183 capable device) to not understand longitude, usually defaulting to 180°

Sentence example: $GNWPL,6432.48,N,-2207.82,W,BY705*71

But should look like this: $GNWPL,6432.48,N,2207.82,W,BY705*71

**Comment by samuelhj** [comment]
This fixed the negative value and the serial module NMEA mode is almost showing correct position ;) . Good work!

**Comment by caveman99** [comment]
so both the WPL and the GSA (own position) sentences are working as expected?
