### ISSUE TITLE
[Bug]: NMEA sentence contains wrong coordinate format 

### ISSUE THREAD

**Issue by samuelhj** [meshtastic/firmware#1931]
### Category

Serial

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.0.2.b004706-d

### Description

After the latest fix, clearing negative values from the NMEA sentence, a new bug has been found. 
It seems that instead of reporting coordinates in DD°MM.mmm' (Degrees, minutes and deciminutes) the NMEA sentence has DD.DDDD° values. This causes wrong lat/lon reported by several dozen kilometres. 

Expected behaviour: NMEA0183 uses DD°mm.mm' in the format of DDmm.mm  (NMEA sentence)

Example coordinates of meshtastic device Waypoint:
64°12.18'N 21°12.18'W
64.203000, -21.203000 
Example NMEA sentence from same coordinates: $GNWPL,6420.30,N,02120.30,W,Waypoint*xx
Example NMEA sentence CORRECT $GNWPL,6412.18,N02112.18,W,Waypoint*xx

**Comment by caveman99** [comment]
this is in develop and will be in the next firmware release
