### ISSUE TITLE
[Feature Request]: Display off at special times

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/firmware#1954]
I would like have the option to switch the display off at special times.

So p.e. I can set in the night the display off.

**Comment by thebentern** [comment]
Not a whole lot to go off of here. Would you mind explaining how this would work in greater detail? 
The device already has a screen timeout. If you had "dark hours" it would seem confusing to have the device not turn on the screen when the user clicks the user button.

**Comment by Dtrieb** [comment]
Yes. I forget that there is a screen timeout. So we can close this . Sorry 😐
