### ISSUE TITLE
[Feature Request]: manual buzzer option for external notification plugin

### ISSUE THREAD

**Issue by BeenThereScrewedUp** [meshtastic/firmware#1969]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.2.8146e84

### Description

For some boards, PIN_BUZZER is defined in the respective variant.h file.
For the T-Beam board, no buzzer is defined - which is correct as it does not feature an on board buzzer.

I connected a buzzer to pin 13 and GND and configured meshtastic accordingly. The debug log activates pin 13 as a digital pin instead of as a pwm pin. This seems to be the case as no PIN_BUZZER is defined for the board. However, there is no option to define the pin as pwm pin without recompiling the firmware with a modified variant.h.

Would it be possible to allow a manual flag to be set in the notification configuration to choose between digital and pwm output?

If not it would be nice if you could someone could update the documentation to indicate that a buzzer relying on tone.h and pwm is only possible on boards with a built-in buzzer and otherwise only digital out is available.

**Comment by garthvh** [comment]
Detected PWM modules should be used for ease of use, GPIO should be the manual option as it is much more finicky for regular users.

**Comment by garthvh** [comment]
This is in place now settings are on device and external notification
