### ISSUE TITLE
[Feature Request]: Add Device.Role and Position.Flags in Metadata

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#1989]
### Platform

NRF52, ESP32

### Description

It would be helpful to know what the device role is when requesting metadata from a remote node so that messaging can only show clients if a network has a lot of ROUTER devices that are not connected to apps.

It would also be helpful to be able to get the position flags for a remote node as well to support vehicle use cases

**Comment by caveman99** [comment]
Are you talking about the periodic NodeInfo broadcasts or a certain admin packet you have to requests verbatim?

**Comment by garthvh** [comment]
> Are you talking about the periodic NodeInfo broadcasts or a certain admin packet you have to requests verbatim?

This message https://github.com/meshtastic/protobufs/blob/e406029f68d8a554f43fd1f250baca6b3c1a9a33/device_metadata.proto#L13
