### ISSUE TITLE
[Bug]: T-Beam display not honoring screen timeout

### ISSUE THREAD

**Issue by Anonym-tsk** [meshtastic/firmware#2006]
### Category

Hardware Compatibility, Other

### Hardware

T-Beam

### Firmware Version

2.0.6.97fd5cf

### Description

The display on the T-Beam is not turning off after the "Screen on for" setting.

Test setup: 2.0.6 firmware on T-Beam, WiFi connection.

I tried screen on time from 30 to 600 seconds.

**Comment by caveman99** [comment]
if the device is powered by USB, the screen will not turn off.

**Comment by Anonym-tsk** [comment]
Why? I worry about oled screen burn-in.

**Comment by garthvh** [comment]
> Why? I worry about oled screen burn-in.

Not a real big concern https://hackaday.com/2019/04/23/a-year-long-experiment-in-oled-burn-in/

**Comment by Anonym-tsk** [comment]
> Not a real big concern

I have diy co2 sensor with oled display. Some pixels burned-in after 2 years.

**Comment by garthvh** [comment]
> > Not a real big concern
> 
> I have diy co2 sensor with oled display. Some pixels burned-in after 2 years.

Of being on the same screen, which is not an issue for meshtastic

**Comment by Anonym-tsk** [comment]
Would you make configuration parameter "Turn off screen also if device is powered"?
