### ISSUE TITLE
WiFi Client loses connection

### ISSUE THREAD

**Issue by ReiHof** [meshtastic/firmware#2009]
I have installed version 2.0.2 on different devices.
Only T-Beams lose WiFi connection after a few hours and can only reconnect after reset. 
[TBeam_Log_221111_short.txt](https://github.com/meshtastic/js/files/10001184/TBeam_Log_221111_short.txt)
As a test I had changed the return value in WiFiAPClient.cpp in function reconnectWiFi() from 12 hours to 5 minutes. The problem was solved. Is this the right way ?

**Comment by caveman99** [comment]
That is solved in newer alphas. i think around 2.0.5ish.

"return 300000; // every 5 minutes" among other optimizations. Please pdate your firmware and re-test.
