### ISSUE TITLE
Feature Request: Send Position with WantResponse = true without specifying a specific node.

### ISSUE THREAD

**Issue by EmilM256** [meshtastic/firmware#2012]
I really like the Request position feature. It is especially useful right after turning on the device. However, I noticed that it only works "directly" (which is also useful for me).

I have a question: is it possible to add a second function that will work the same but the query will be passed through the mesh?

If we have a network of three devices, A B and C. A sees B, B sees C, but A does not see C directly. It would be nice if device A could query the position of C (thanks to a new feature).

Is it possible? Would it be good to add this?

**Comment by garthvh** [comment]
Behind the scenes this sends a position to a specific node with wantResponse = true.

In my testing setting wan response on a channel message does not result in positions being returned

**Comment by GUVWAF** [comment]
I think the original request was to request the position from a node that is not the first hop, not per se from every node in the mesh. @EmilM256 which device firmware are you running? I think this already works from 2.0.2 on.

**Comment by EmilM256** [comment]
I did the first tests on the 2.0.3 software. Currently, the "mobile" nodes are 2.0.6, while the routers are still not updated - 2.0.3.

Update position request only works if my device is direct (no hops), in any case. If I request a position for a node where there must be hops, I get no response.

**Comment by garthvh** [comment]
A dm still uses the mesh, there is no response other than the ack sent when I request a response when sending a channel message, when sending a position with wantResponse = true and a destination node I get a position back even if it has to go through another node.  I have the want response off on channel messages in the apple apps because it does not result in a position being returned.

**Comment by garthvh** [comment]
This is a position sent with a destination 
🕸️ ROUTING PACKET received for RequestID: 3353640645 Error: This message is not a failure
💾 ACK Received and saved for MessageID 3353640645
🗞️ BLE (Notify) characteristic, value will be read next
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 4145973744

And this is one without

🕸️ ROUTING PACKET received for RequestID: 3795134801 Error: This message is not a failure
💾 ACK Received and saved for MessageID 3795134801

**Comment by tim292stro** [comment]
I just want to point out a side effect of this request - that is, someone getting on your mesh and sniffing out all of your other nodes.  It's harder to do this when radio direction finding is required with tranisent packet bursts, but this function would essentially get people within a few meters of the node without more than another device (or protocol impersonating device with a LoRa modem) on request.  I urge all to consider cases where this might be a problem.

**Comment by garthvh** [comment]
It also is likely to create a storm of responses and Ack is implemented that would be problematic for networks with more than a handful of nodes.
