### ISSUE TITLE
[Feature Request]: No power limitations please...

### ISSUE THREAD

**Issue by SR7673** [meshtastic/firmware#2016]
### Platform

ESP32

### Description

Hello Kevin and the team,

I'd like to suggest the removal of a power limitation. I'm operating in the EU 433 MHz band and the maximum power i can select into the app (Android) is 12 dBm, probably due to regularity considerations. Understood. 
HOWEVER: Please consider that some people are forced to use a thin and very lossy coax cable between node and antenna. See this table
![diagramm_kabel](https://user-images.githubusercontent.com/86408129/205446574-cb79a2bb-2f23-48b7-b3f4-db8a68e7e2c8.gif)
For a 10m long RG174 cable at 433 MHz you are getting about 6.5 dB signal attenuation (and 13 dB at 866 MHz!!). If someone wants to put an antenna on the roof of a house and keep the node two floors below to keep the bluetooth link and needs to use a thin cable that can be passed through a closed window (thus RG174), you can easily get 8 dB attenation. This signal loss could be compensated by running 20 dBm instead of 12 dBm and the legel ERP limit is still hold.
Furthermore the operator of a transmitter is responsible for keeping the legal limits, not the software writer.
12 dBm could be kept as the default value when installing the app.

Best regards and thanks for the great project that is an important step for the freedom of communication.

**Comment by garthvh** [comment]
This is due to both regulations and our upstream radio library, you are free to modify the value for your edge case.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/how-to-set-the-tx-power-to-more-than-12-dbm-on-433-mhz/6876/1
