### ISSUE TITLE
[Bug]: Incorrect power status

### ISSUE THREAD

**Issue by SR7673** [meshtastic/firmware#2017]
### Category

Other

### Hardware

T-Lora v2 1.6

### Firmware Version

2.0.5.65e8209

### Description

Running this node in Router only mode. It states that it is powered by the "mains", i.e. over the USB. However it is powered from a battery (over the JST plug on the back side). "It states" means that this is shown from the Android app, version 2.0.3.

**Comment by garthvh** [comment]
You can try setting the ADC multiplier override value
