### ISSUE TITLE
[Feature Request]: Remove nodes from NodeDB after a certain period of inactivity. Including their message store.

### ISSUE THREAD

**Issue by caveman99** [meshtastic/firmware#2028]
### Platform

NRF52, ESP32

### Description

This will enhance user experience on bigger networks, not having to scroll through a pletora of older node entries. Both during standalone/canned message operation and on the app display.

**Comment by garthvh** [comment]
What timing are you thinking of?  Would the absence of a node cause the removal on the app side?

**Comment by tavdog** [comment]
I think this is dup of #2396
