### ISSUE TITLE
[Feature Request]: Clone watchdog/LED1 output to any GPIO pin

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/firmware#2032]
### Platform

NRF52, ESP32

### Description

Please add the ability to mirror the heartbeat "blinking" signals to any user-configurable GPIO pin.
This feature is required to efficiently integrate "hardware" external watchdogs into autonomous Meshtastic nodes/repeaters located in hard accessible places.

**Comment by garthvh** [comment]
This is already in place on most of the boards without adding any configuration, what exactly are you trying to do with which board?

**Comment by D4rk4** [comment]
For example RAK19007

**Comment by garthvh** [comment]
There are already pins on the 19007 you can use, check the data sheet for led2, led1 is the charger I think and does not get managed from the firmware.

**Comment by garthvh** [comment]
> @garthvh so, how I can pick up the GREEN LED heartbeat signal on this board?

Check the data sheet, RAK offers extensive documentation

**Comment by garthvh** [comment]
There is a pin for led2, which is what you want, not sure what 5d is

**Comment by garthvh** [comment]
There are no usable GPIO pins available on the base board, you need an IO board. 

There is nothing to do with this request.
