### ISSUE TITLE
[Bug] Unable to flash RAK 19007 / RAK 11200 Combo

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2033]
The RAK11200 seems to only be capable of being flashed with the EOL 5005 base board, even if I flash it on a 5005 and then move the core to a 19007 it boots and immediately crashes.

**Comment by caveman99** [comment]
this may be a bigger issue - we had reports of trouble making 11200 talk reliably to 13300 on the 19007. 5005 works fine.

**Comment by caveman99** [comment]
I assume you know about the GPIO0 twist. Do you have an error message when flashing on 19007 fails? Did you try 115200 bps instead of 921600? Bad cable ( i had one of those yesterday, even USB-C)

**Comment by garthvh** [comment]
Duplicate of #2054
