### ISSUE TITLE
[Feature Request]: Allow users out of canned messages

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2042]
### Platform

NRF52, ESP32

### Description

It would be nice if users with a rotary encoder had a way out without sending a message, either a cancel at the bottom of the message list that advances the screen, or a timeout that advances the screen.  Currently once you twist the encoder you are forced to send a message to get out.

**Comment by caveman99** [comment]
the select screen shoud time out after 20 seconds. This is a bug

**Comment by garthvh** [comment]
The timeout is working again @caveman99, would it be hard to add cancel to the wheel of messages or is that a big hassle?

**Comment by jp-bennett** [comment]
I'd like to see a "cancel" option, too. Really feels like a missing UX element.

**Comment by mverch67** [comment]
What about a long press on the button to cancel? Would be in line with the screen ui PR.

_Long (2 sec) user button press exits to default local device screen at any time_
