### ISSUE TITLE
Feature request - Ability to determine who ack'd a message 

### ISSUE THREAD

**Issue by kevinb0** [meshtastic/firmware#2048]
When sending a message in a chat room, it's great to get a read receipt (the check inside the cloud). I think it'd be helpful to know who received it - for example, long pressing the icon would pop up a window saying all the nodes that ack'd that message. It would also be neat to have that dynamically update that multiple times, so for multiple nodes, you'd have an easy way to see if node X recieved message Y.

**Comment by garthvh** [comment]
This is not really possible for channels (group chats) right now but may be viable for DM's

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/tracking-which-nodes-are-used-to-hop/6933/5

**Comment by GUVWAF** [comment]
Confirmation by the intended receiver of a direct message is in the firmware from 2.0.9 on. I will create feature requests for the apps.
