### ISSUE TITLE
[Bug]: RAK 11200 crash when try access to HTTP

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/firmware#2054]
### Category

Other

### Hardware

Rak11200

### Firmware Version

2.0.7.91ff7b9-d

### Description

Meshtastic-Web crash RAK12000, when file not found

### Relevant log output

```Shell
[ 51094][E][vfs_api.cpp:104] open(): /littlefs/static/hotspot-detect.html does not exist, no permits for creation
[ 51101][E][vfs_api.cpp:104] open(): /littlefs/static/hotspot-detect.html.gz does not exist, no permits for creation
WARNING file:stream_interface.py __reader line:179 Meshtastic serial port disconnected, disconnecting... device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

**Comment by caveman99** [comment]
Is there more in this log? Usually a crash has some more output

**Comment by D4rk4** [comment]
No, just reboot, prev messages are not related to the error and are always different.

**Comment by garthvh** [comment]
> No, just reboot, prev messages are not related to the error and are always different.

Which base board are you using?

**Comment by D4rk4** [comment]
RAK12000 + RAK19007 + RAK12002 + RAK1906

**Comment by garthvh** [comment]
How did you flash the device?

**Comment by D4rk4** [comment]
@garthvh esptool via device-install script =)
