### ISSUE TITLE
[Bug]: Screen is black on T-Beam + SSD1309

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/firmware#2059]
### Category

Hardware Compatibility

### Hardware

T-Beam

### Firmware Version

2.0.8

### Description

After 5-10m after flash 2.0.8. display stops working. Just not showing anything, firmware still sees Screen (regarding log).

A downgrade to 2.0.7 did not help. Look like destroyed on the hardware level.

**Comment by D4rk4** [comment]
Display - SPD0301

**Comment by caveman99** [comment]
It's physically not possible to destroy these kind of displays through the firmware. Wear over months can ruin pixels, cracked edges of the screen may damage. But not within minutes and not through a software bug.

**Comment by D4rk4** [comment]
@caveman99 I will try with another T-Beam

**Comment by D4rk4** [comment]
After test with second unit got it:
![image](https://user-images.githubusercontent.com/1151390/209143253-210784c6-58d5-4755-9dd7-db2a0b0e4c76.png)
Roll back firmware to 2.0.7 resolve issue.

**Comment by caveman99** [comment]
https://github.com/meshtastic/firmware/compare/v2.0.7.91ff7b9...v2.0.8.090e166?expand=1

I have been through this diff up and down and can't for the life of me find a spot that will induce the described behaviour. Maybe you have more luck than me. Plus i don't have that display type here to counter-check :-(

**Comment by D4rk4** [comment]
I will try with all artifacts related to this diff on weekend.

**Comment by D4rk4** [comment]
PR2051 broke the display.

**Comment by garthvh** [comment]
Have you tried setting the oled type under display settings?

**Comment by D4rk4** [comment]
@garthvh nope, may you describe which params and values I need to provide to meshtastic cli.

**Comment by garthvh** [comment]
Not totally sure, you can do the update from both android and iOS 

https://meshtastic.org/docs/settings/config/display#oled-defintion

**Comment by garthvh** [comment]
Looks like it is display.oled in the protobufs

**Comment by garthvh** [comment]
meshtastic --set display.oled OLED_SH1106 is probably what you need, I don't think any of the 1.3" screens are actually a SSD13XX

**Comment by D4rk4** [comment]
@garthvh both OLED_SSD1306 and OLED_SH1106 not working for my SSD1309

**Comment by garthvh** [comment]
Do you have a single screen like this?  They don't seem to have a good library and are 3X the cost of a 1.3" SH1106.

**Comment by D4rk4** [comment]
@garthvh How it's related to costs? Also it's 1.51"

**Comment by garthvh** [comment]
We have a limited amount of resources and nobody working on the firmware has this screen, at $30 few users are buying this screen to use with meshtastic. If you want support added for this screen it is going to be you adding it at this point as you are the only user who can test it

**Comment by caveman99** [comment]
> PR2051 broke the display.

that is a huge rollup PR. Nevertheless i just went through it and again i can not find a place that would really impact the operation of this OLED screen.

**Comment by D4rk4** [comment]
@caveman99 may you build firmware from PR2051 with all commits except changes related to Screen.* files? I hope it's related to dual-color screen support changes.

**Comment by caveman99** [comment]
The 2.0.10 firmware can disable these changes interactively, in fact the default is now the old visual before 2.0.7

**Comment by D4rk4** [comment]
@caveman99 how I can disable this in 2.0.10?

**Comment by D4rk4** [comment]
@caveman99 is not actual, because firmware killed the second display.

**Comment by D4rk4** [comment]
@caveman99 @garthvh Working with default settings on 2.0.12

**Comment by thebentern** [comment]
Fixed. Closing
