### ISSUE TITLE
Device resets when changing screens

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/firmware#2079]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.0.6

### Description

Device sometimes reboots when pressing the lower button to switch screens

**Comment by caveman99** [comment]
We need Logs to debug that. Also please update to the latest firmware in the 2.0.x series

**Comment by GaryR-12** [comment]
Thanks, Updated to 2.0.8
Will monitor for issues.
