### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by seydunatirej** [meshtastic/firmware#2088]
I want to install the platform, but after installing visual studio, when I import the project, there are problems. I don't understand why. I would be glad if you help

**Comment by sachaw** [comment]
We need more than that to go off. What problems are you running into, what steps have you performed and what have you tried to remedy the situation?

**Comment by seydunatirej** [comment]
I will send the screenshot of the errors I get when I run the code. Because of these the firmware doesn`t upload in the device. I will be very glad if I could solve this. I hope you could help me. Thank you.. 
![1](https://user-images.githubusercontent.com/58654344/210436050-fd9d61ca-5b5a-431e-8c7f-59892f661fee.png)
![2](https://user-images.githubusercontent.com/58654344/210436059-aac19613-71cf-4b30-9f03-d06a6702a02a.png)

**Comment by sachaw** [comment]
Not seeing what the issue is? Does it build?

**Comment by seydunatirej** [comment]
It`s staying like in the first picture and it is not building.

**Comment by sachaw** [comment]
There's no build output or error in the first picture, please confirm the following
1. You have selected your desired environment (board) in pio
2. You have clicked build (not build and upload), to confirm that it successfully builds
3. You will either get a build success (highlighted in green) or a fail (highlighted in red).
Please report back on what it is and any associated errors.

**Comment by seydunatirej** [comment]
I thank you for helpfully instructions. Because I didn't choosed environment board it didn't worked. With your help its going well now.!
