### ISSUE TITLE
[Feature Request]: Add SSD1327 LCD support

### ISSUE THREAD

**Issue by Krezalis** [meshtastic/firmware#2091]
### Platform

ESP32

### Description

Add SSD1327 LCD support.
Resolution 128 * 128, 16 levels of grays.

**Comment by caveman99** [comment]
I ordered one of these a few weeks back, unfortunately the chinese seller sent wrong boards (SH1106, 128*128*1) and is not very cooperative about changing them for the right ones. Searching around i could not find a single reputable vendor that carries these at the moment, so they look to be another victim of the chip shortage. Feel Free to reopen if these are available again in quantity :-)

**Comment by Krezalis** [comment]
![photo1672340942](https://user-images.githubusercontent.com/4151282/211166061-2894e7f8-8513-46cc-9da3-62ffdfc56f4a.jpeg)
Have one yellow display, it looks fantastic. I paid for it $15, but now I see it is not popular.
