### ISSUE TITLE
[Bug]: Rak5005/4631 with eink screen and FW 2.0.10 to 2.0.12

### ISSUE THREAD

**Issue by feh123** [meshtastic/firmware#2101]
### Category

Hardware Compatibility

### Hardware

Rak4631

### Firmware Version

2.0.10, 2.0.11 and 2.0.12

### Description

I was using 2.0.6 on my rak5005/4631/14000 (eink screen) devices. I have tried updating via terminal and nrfutil dfu serial to FW 2.0.10, 2.0.11 and 2.0.12 but there are some problems. With these versions I see no meshtastic logo splash screen on update completion. The updating seems to work - no errors are reported. When I connect the devices via the latest iOS app (from Testflight) I get no rebooting screen when changes parameters. Again the changes are accepted. I have a TBeam running 2.0.12 in the mesh as well. That reboots correctly displaying the splash screen and the rebooting message on parameter change. Oddly however in the iOS app it still says the TBeam is on 2.0.6! So nothing too serious but I thought I would report it - maybe not many users are using a 14000 screen.

**Comment by claib** [comment]
Hi there
is there any news about RAK EInk ?
Still no success to get epaper working since Version 2.06
Even now with 2.023

did i miss something ?
