### ISSUE TITLE
Web Interface reset before i can send a message through the text field [Bug]: 

### ISSUE THREAD

**Issue by homesec24** [meshtastic/firmware#2102]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.12.2400dd4

### Description

If i chat over the WEB Interface and the node has a connection to the main mqtt server and i want to write, the text field always do a reset ... as a workaround i write my text to the url field from the browser and do a copy/paste and press send immediately.

**Comment by caveman99** [comment]
closing, this is living here now ... https://github.com/meshtastic/web/issues/67
