### ISSUE TITLE
[Feature Request]: Block Users Feature 

### ISSUE THREAD

**Issue by spm81** [meshtastic/firmware#2111]
### Platform

ESP32

### Description

 Block Users Feature in the future maybe useful

**Comment by caveman99** [comment]
https://meshtastic.org/docs/settings/config/lora#ignore-incoming-array

**Comment by homesec24** [comment]
I tryed out lora.ignore_incoming but it returns "Aborting due to: 'google._upb._message.Descriptor' object has no attribute 'ignore_incoming'" if i want to add a node by Number. Maybe also a Black/Whitelist would be helpfull?
