### ISSUE TITLE
[Bug]: mqtt hostnames can't always be <32 characters

### ISSUE THREAD

**Issue by bmidgley** [meshtastic/firmware#2117]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.6

### Description

Sometimes hostnames we get for stuff in the cloud are really long and not negotiable. But we're pegged at 31 characters currently.

**Comment by D4rk4** [comment]
Some users in the Russian telegram chat mentioned this issue before.
As a result of this limitation, we can't use free MQTT servers with random domain names for example HiveMQ.

**Comment by garthvh** [comment]
This has been bumped to 64

**Comment by xhci** [comment]
@garthvh by default, my ActiveMQ hostname on AWS is 67 characters (not including the port). It requires significantly more cost like a network load balancer to use custom hostnames. Would it be possible to bump this higher?

**Comment by garthvh** [comment]
> @garthvh by default, my ActiveMQ hostname on AWS is 67 characters (not including the port). It requires significantly more cost like a network load balancer to use custom hostnames. Would it be possible to bump this higher?
> 
> I added an MR here that will probably fix the issue: #5604

This can't be merged (and would have to be made in the protobufs repo) There is no space left on the MQTT config packet.

**Comment by xhci** [comment]
Thanks for the feedback. I'll figure out a solution on my end.

**Comment by bmidgley** [comment]
We made a short cname in our case to avoid the long cloud hostname
