### ISSUE TITLE
[Bug]: Heltec V3 GPIO Read 

### ISSUE THREAD

**Issue by SamJe11y** [meshtastic/firmware#2124]
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

2.0.10

### Description

Flashed firmware to Heltec V2 and, through the terminal (Using Linux Ubuntu OS) managed to read a GPIO and detect a button press both locally and remotely - tried doing this with a Heltec V3 and can't seem to pick up button presses at all, locally or remote. 

Flashed the latest version of firmware (2.0.12) to both boards, but found that read command in terminal wouldn't print the received remote hardware statement. Flashed the 2.0.10 firmware and received the following - 

Commands used: watch -n 1 meshtastic --port /dev/ttyUSB0 --gpio-rd 0x1000 --dest '!fa815e54'

Received: Connected to radio
Reading GPIO mask 0x1000 from !fa815e54
Received RemoteHardware type=READ_GPIOS_REPLY, gpio_value=4096 value=4096

However, still can't detect button presses. Have the command functions changed ? I also noticed the Heltec V3 GPIO pin numbers are much higher / not as logically ordered as the Heltec V2, could this confuse the GPIO mask settings? 

Thanks,
Sam

**Comment by thebentern** [comment]
Possibly resolved by #930. We can reopen if needed
