### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by uw5elk** [meshtastic/firmware#2138]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.0.12

### Description

T-echo stopped showing up in device manager.  Shown only as TECHOBOOT partition when double-clicking the upper side button.  Anyone have any ideas?

**Comment by garthvh** [comment]
Give this a try https://meshtastic.org/docs/getting-started/flashing-firmware/nrf52/nrf52-erase

**Comment by uw5elk** [comment]
I copy Meshtastic_nRF52_factory_erase.uf2 to TECHOBOOT.  I connect via serial (using Putty) and press the key... and nothing happens :(
