### ISSUE TITLE
[Feature Request]: Shutdown countdown

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/firmware#2139]
### Platform

ESP32

### Description

If we press the power button, to switch off the T-Beam, it would be great if we get a count down:
3,
2, 
1,
Shutdown 
and then the T-Beam goes off.

**Comment by garthvh** [comment]
That button is controlled by the AXP chip, not the firmware

**Comment by Dtrieb** [comment]
One question to that:

How this work with the dim the display?
After that you can close this. 

@garthvh

**Comment by garthvh** [comment]
> One question to that:
> 
> 
> 
> How this work with the dim the display?
> 
> After that you can close this. 
> 
> 
> 
> @garthvh 

That button is controlled by the firmware, the far left power button just cuts power without any interaction.
