### ISSUE TITLE
[Feature Request]: Change "No GPS Module" when location is from app

### ISSUE THREAD

**Issue by GMart** [meshtastic/firmware#2141]
### Platform

NRF52, ESP32

### Description

When I use a board without GPS installed, and I'm using location from my phone, currently the last screen shows "No GPS Module". That is technically correct, however I think it would be more useful to show something like "Location from phone"/"Location from app" instead. With the way it is, you have no way of knowing if your location is being sent over the mesh by looking at the device. Maybe even show the coordinates being sent over the mesh.

The default behavior could be kept if the device is not receiving a location from the app/ not connected and doesn't have a GPS module.

**Comment by GMart** [comment]
Has there been any update on this? Or has there been any changes in the past few versions of the firmware that would allow for this?

**Comment by code8buster** [comment]
Working on it. Stay tuned, doing some testing before sending the pull request
