### ISSUE TITLE
Heltec WSL v3 No GPS

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2142]
Looks like similar to the Heltec V3 #2039, the WSL V3 variant also has  "HAS_GPS" set to 0 disabling GPS capabilities. I'm assuming that just needs to be removed but firmware is not my area so I didn't want to mess with it. Which is why I'm opening an issue for a professional to take a look 🤪

https://github.com/meshtastic/firmware/blob/5520d68b341787451dedefd048d0652e0d88d789/variants/heltec_wsl_v3/variant.h#L4

**Comment by thebentern** [comment]
Fixed in latest release
