### ISSUE TITLE
[Bug]: Cannot set power.ls_secs - it is always 300 secs (client) or 86400 (router)

### ISSUE THREAD

**Issue by rpsainio** [meshtastic/firmware#2200]
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.0.13.7e27729-d

### Description

the $SUBJECT tells it all: it is not possible to set that value with CLI.

### Relevant log output

```Shell
meshtastic --set power.lsSecs 200 --port=/dev/ttyACM0
Connected to radio
Set power.ls_secs to 200
Writing modified preferences to device
[risto@rsa46 configs]$ meshtastic --get power.lsSecs --port=/dev/ttyACM0 
Connected to radio

power.ls_secs: 86400
Completed getting preferences
[risto@rsa46 configs]$ meshtastic --set device.role  CLIENT_MUTE
Connected to radio
Set device.role to CLIENT_MUTE
Writing modified preferences to device
[risto@rsa46 configs]$ meshtastic --get power.lsSecs --port=/dev/ttyACM0 
Connected to radio

power.ls_secs: 300
Completed getting preferences
[risto@rsa46 configs]$ meshtastic --version
2.0.9
```

**Comment by garthvh** [comment]
Power settings should be managed by the role now

**Comment by caveman99** [comment]
the explicit setting should still be honored, even if in most cases it does more harm than good.

**Comment by rpsainio** [comment]
explains as I checked the source already - those default values look quite arbitrary to me.

**Comment by rpsainio** [comment]
maybe we need : "this parameter will be become obsolete in near future"

**Comment by rpsainio** [comment]
Ah whatever, the best SW is the one you bake yourself.. I noticed this when I tried to test further #2084 as that boot-loops happens only when node goes to LS and maybe there is time dependence. @caveman99 cheers from HD

**Comment by garthvh** [comment]
> 

Do no harm!
