### ISSUE TITLE
[Bug]: Unset Region is transmitting

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2205]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.0.13

### Description

We must have re-introduced TX power when region is unset when we updated the protobuf defaults

**Comment by caveman99** [comment]
i noticed that all the way through 1.3 cycle, but wasn't able to pinpoint it. the tx shutout was right there in the code and yet it would do stuff when unset.

**Comment by caveman99** [comment]
There was a merge duplication, effectively disabling the check path. https://github.com/meshtastic/firmware/pull/2231 fixes that
