### ISSUE TITLE
[Bug]: Possible heap leak if lora.tx_enabled false

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#2227]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.13

### Description

First, I tested whether **WiFi** or **WiFi+MQTT** have an effect on the heap leak.
The heap derating values in all tested cases are 465±2 bytes/minute.
The 3 modules for the test:
blue WZ1 T-Beam SX1276
ret TEST T-Beam SX1262
magenta ZELX TLORA v2.1_1.6 as Referenzmodul

Here in the standard mode Send & Receive enabled.

![Issue_1](https://user-images.githubusercontent.com/3943213/215467508-0e08897a-6cd2-40c2-ad26-ff09eb7913f9.png)

One way to restrict the transmission via a parameter is
`--set lora.tx_enabled false`

![Issue_2](https://user-images.githubusercontent.com/3943213/215467557-7c7ffb50-68e3-45c0-8f7a-54030f772bf0.png)

**There is a significantly higher heap derating if tx_enabled is set to false.**

**Comment by caveman99** [comment]
looks like this was related to https://github.com/meshtastic/firmware/pull/2231 - can you retest after the next firmware release?

**Comment by karamo** [comment]
Yes, I will repeat the test with 2.0.15 soon.

**Comment by karamo** [comment]
Now I tested on both modules FW 2.0.14 with `meshtastic --port com8 --set lora.tx_enabled false` on the red Module.

![Issue_6](https://user-images.githubusercontent.com/3943213/215767306-f5abb910-8523-4797-87ce-28370e32de64.png)

The larger heap leak is fixed. There is even an improvement, but it is also logical, since with lora.tx_enabled false now no transmissions take place at all.

**Comment by karamo** [comment]
Is fixed in **FW 2.0.14**
can be closed.
