### ISSUE TITLE
[Feature Request]: Received Messages Timestamp Configuration

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2234]
Received messages will now display a timestamp on the device's display. This is an excellent feature, especially for devices such as the Meshenger or when using the S&F module. However, there are some drawbacks for the user experience with this new feature. 

1. If there is no GPS/RTC on the device, the timestamp displayed on the device will be 00:00:00. As no all devices will have these modules, I would suggest making this feature a configurable device option. Example: display.received_timestamp `true` or `false`. This allows the user to elect to enable/disable the feature as needed with their devices. 
2. The timestamp, when the device has GPS/RTC, is displayed in Zulu/GMT and not the local time (unless local is Zulu/GMT). This requires a user to know their GMT offset and mentally calculate with each message which is not the best user-facing experience. A suggested remediation would be to enable an offset in the firmware for the display only, similar to C to F, while keeping logging at Zulu/GMT. Example: display.timezone_offset `integer`.

**Comment by garthvh** [comment]
This was updated to relative time which is a much easier solution on a microcontroller without a whole stack available to handle time worldwide.
