### ISSUE TITLE
No Heap-Leak with Role REPEATER

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#2238]
With **FW 2.0.17** there is a new role: **REPEATER**
Many threads that are not required for the role REPEATER do not start.
As a result, it turns out that basically no heap leak occurs anymore.
The **blue** one is REPEATER
	`meshtastic --port com16 --set device.role REPEATER`

the other are CLIENT

![Issue_7](https://user-images.githubusercontent.com/3943213/216047592-3ff6e53c-01de-45b6-b2a6-1eb523953296.png)

**Comment by caveman99** [comment]
related to #2228

**Comment by thebentern** [comment]
Closing this, since it's more of an observation and so we can track the heap leak issue in #2228

**Comment by karamo** [comment]
The difference between **CLIENT** and **REPEATER** are the following threads, which do not run with REPEATER:
```
• GPS
• NodeInfoModule
• PositionModule
• DeviceTelemetryModule
```
In subsequent test runs, the effects are tested individually.
