### ISSUE TITLE
[Bug]: Heap-Leak in DeviceTelemetryModule

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#2239]
### Category

Firmware

### Hardware

T-Beam, Other

### Firmware Version

2.0.17

### Description

As shown in issue #2238, no heap leaks occur with role REPEATER. In subsequent test runs, the effects are tested individually. The difference between CLIENT and REPEATER are the following threads, which do not run at role REPEATER:
• GPS
• NodeInfoModule
• PositionModule
• DeviceTelemetryModule

![Issue_8](https://user-images.githubusercontent.com/3943213/216129349-66c221c0-f2fc-4db3-806c-9022e8545b22.png)
GPS, NodeInfoModule, PositionModule = no Heap-Leak

![Issue_9](https://user-images.githubusercontent.com/3943213/216129471-9da0adb8-d171-4cfc-a917-831f04a764ab.png)
(red) TEST = CLIENT
(magenta) ZELX = CLIENT (magenta) TLORA (Referenz)
(blue) WZ1 = REPEATER + DeviceTelemetryModule

 #### A heap-leak occurs when the `DeviceTelemetryModule` is active.

**Comment by karamo** [comment]
I found the heap-leak. @caveman99 will make the PR.
![Issue_2239](https://user-images.githubusercontent.com/3943213/216253720-af4f3b1d-46b8-47fc-9438-b6390f10f179.png)

**Comment by mc-hamster** [comment]
WOW, WOW, WOW!!!!!

Thank you for this great research!
