### ISSUE TITLE
Eink Screen not working with 2.0.14.2baaad8

### ISSUE THREAD

**Issue by feh123** [meshtastic/firmware#2241]
I have three rak4631's with eink screens. I use them to communicate so they were using 2.0.3 to get the best signal range. I thought I would try 2.0.14 as the range issue was solved. I have updated pip and meshtastic to the latest versions. I tried the update using nrfutil with the ota-zip file from terminal. The updates were successfully installed (as seen in meshtastic --info) but eink screen did not update and still displayed 2.0.3 as the FW. I tried this on two rak4631's with the same result. I have not tried any other versions of the software. I went back to 2.0.3 on both and the screens are working well.

**Comment by jfirwin** [comment]
Thanks @garthvh!
