### ISSUE TITLE
[Bug]: Device message timestamp changed to random characters in 18 update

### ISSUE THREAD

**Issue by mchuzie** [meshtastic/firmware#2251]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.0.18.1a7991c

### Description

Upgraded from 16 to 18. Messages timestamps on device are replaced with random characters. Downgraded back to 16 and timestamps are restored.

**Comment by garthvh** [comment]
Relative time has replaced the UTC timestamp so that it is not necessary to manage timezones and daylight savings time on device.

**Comment by caveman99** [comment]
@garth it looks like sometimes the relative timestamp prints garbage. i want to add a guard clause and check if values are plausible.

**Comment by tavdog** [comment]
Has this been fixed somewhere ? I haven't experienced this issue on 2.1
