### ISSUE TITLE
[Bug]: Heap-Leak at sending via CLI

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#2257]
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.0.18

### Description

malicious behavior: When I extend the **MT-CLI (python)** with the `--sendrepeattext` function
and e.g. 10x send a message at intervals of 20 seconds.
The heap then drops continuously also after the send ends (1) and remains at a lower heap level after some time (2).
![Issue_st-002](https://user-images.githubusercontent.com/3943213/217230058-2fd7932f-d02e-49fc-b6a9-c111d9f4743b.png)
![Issue_st-001](https://user-images.githubusercontent.com/3943213/217230098-ef58617d-a9a9-42e9-9b6b-6b5d7b26de63.png)

**Comment by caveman99** [comment]
Sorry, but just sending a message queues stuff up all around. What is the display aftre 15 minutes?

**Comment by karamo** [comment]
> Sorry, but just sending a message queues stuff up all around. What is the display aftre 15 minutes?

constant at lower Heap.

**Comment by karamo** [comment]
> Sorry, but just sending a message queues stuff up all around. What is the display aftre 15 minutes?

constant at lower heap. see red line.
![Issue_st-005](https://user-images.githubusercontent.com/3943213/217525518-d8a14886-0764-4ec1-a996-82bf5c13c796.png)

**Comment by thebentern** [comment]
The CLI has a more transient "PhoneAPI" connection lifecycle than the apps, so I'm not entirely surprised

**Comment by karamo** [comment]
Today I tested with FW 2.0.21 + tryfix.
Result: No Heap-Leak
![FW21+tryfix-ok_2023-02-22_11-17-44](https://user-images.githubusercontent.com/3943213/220591340-b78af4cf-00d3-4023-b03e-b99add908116.jpg)
The up-peaks are the time I sent a message via CLI.

Issue can bee closed.
