### ISSUE TITLE
T-Beam and T-Echo intercommunication issue

### ISSUE THREAD

**Issue by PhilipLykov** [meshtastic/firmware#2277]
After update to 2.0.20 and setting up the Override frequency to 432.2 on three T-Echo and two T-Beam devices they stoped any communication between different models. Within a model communication is ok.

**Comment by caveman99** [comment]
Can you post a bootup serial log of both devices? see if the radio parameters match?

**Comment by garthvh** [comment]
Yes, licensed user mode turns off encryption
