### ISSUE TITLE
[Feature Request]: ILI9225 Serial Port TFT LCD Modul

### ISSUE THREAD

**Issue by linux150** [meshtastic/firmware#2284]
### Platform

ESP32

### Description

Hi, im using a TBeam with the ILI9225 TFT LCD.
Would there be any chance to get support for this display or is it not possible with this firmware.
Normaly i use it with rdz_ttgo_sonde firmware from dl9rdz https://github.com/dl9rdz/rdz_ttgo_sonde

LG
Martin

**Comment by thebentern** [comment]
There are no plans to use TFT modules over serial. There is likely existing support for this screen over SPI however.

**Comment by linux150** [comment]
thanks for answer
