### ISSUE TITLE
[Bug]: Heap-Leak at Web-Browser connect

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#2301]
### Category

Firmware

### Hardware

T-Beam

### Firmware Version

FW 2.0.21+tryfix

### Description

Normal state... I just made a web browser connect (Chrome) > negative spike > jump ≈+10k ... ... ... no actions made on the web browser, only open > continuous drop to heap reboot ... after that it remains normal, although the web browser is still connected and I can send a Msg.

WZ1 (blue linie) FW 2.0.21+tryfix
magenta & orange are only for reference

![Web-connect-1](https://user-images.githubusercontent.com/3943213/220911432-229c3cf0-0700-42d3-a995-bc63c9680101.png)

### I need help!
I have no idea where to start troubleshooting.

**Comment by garthvh** [comment]
I would start with the response to wantConfig

**Comment by sachaw** [comment]
What connection method were you using, can you replicate the behaviour across all 3 methods?

**Comment by karamo** [comment]
With FW 2.1.2 + Patch #2329 Heap ist ok.
No longer Heap-Leak.

Issue can bee closed.

**Comment by karamo** [comment]
> What connection method were you using, can you replicate the behaviour across all 3 methods?

I connected in Chrome-Browser via IP.
This ist the clearest methode.
