### ISSUE TITLE
[Bug]: SX1262 radios drop packets when doing CAD while actively receiving

### ISSUE THREAD

**Issue by Josh-SMU** [meshtastic/firmware#2307]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.0.17

### Description

My devices don't always show traffic in serial debugging, after a non-determinate amount of reboots it works as expected. Troubleshooting and logs in #2291

**Comment by GUVWAF** [comment]
If it's only intermittently, this might just be related to a low-level issue I found with SX1262 radios that are dropping packets if they are switching to channel activity detection mode when actively receiving. A change in the library RadioLib where Meshtastic depends on is required for that. 

If you don't mind I will hijack this issue for that while I'm actively going after this.

**Comment by Josh-SMU** [comment]
Please do!

This makes sense as I also notice this issue (at least of intermittenly failing to receive messages without other explanation) on the SX1262 chip in the Pinephone backplate project I'm currently writing.
