### ISSUE TITLE
[Bug]: Tlora-t3s3-v1 firmware reboots continuously (TLora T3S3 with SX1262 chip)

### ISSUE THREAD

**Issue by mverch67** [meshtastic/firmware#2308]
### Category

Hardware Compatibility

### Hardware

LILYGO T3-S3 (SX1262) V1.1 20221205

### Firmware Version

2.0.22.fbfd0f1

### Description

Flash firmware onto TLora T3S3 with SX1262. The device reboots continuously and changes region to LORA_24 which is obviously not expected.

**To fix this I had to do the following changes in the code:**

1- tlora_t3s3_v1/variant.h:
```
#define SX126X_DIO1 33
#define SX126X_BUSY 34
//#define SX126X_RXEN 21
//#define SX126X_TXEN 10
#define SX126X_E22
```

2- main.cpp:
Move SX1280Interface initialization AFTER SX1262Interface initialization 

3- (for upload to device) tlora_t3s3_v1/platform.ini
`upload_protocol = esp-builtin`

4- (for convenience) platform.ini
`;default_envs = tlora-t3s3-v1`

**Explanation of the above changes:**
Without (1) the currently wrong DIO1 pin definition leads to hang after the first transmission and the currently wrong DIO2(BUSY) leads to arbitrary failures during chip initialisation. It is also required to set the tcxo_voltage implicitly via define SX126X_E22 as for various other devices. 
Without (2) the device region changes to LORA_24 and the device permanently reboots. This is because the RadioLib SX128x::begin() code returns RADIOLIB_ERR_INVALID_FREQUENCY (instead of RADIOLIB_ERR_WRONG_MODEM) when a SX1262 chip is present.
Without (3) platformio uses esptool for flashing the device which fails for unknown reason. The upload only succeeded when using esp-builtin (and pressing boot + reset button of the device beforehand).

### Relevant log output

regarding (2) :-
```Shell
INFO  | ??:??:?? 2 Starting meshradio init...
INFO  | ??:??:?? 2 Radio freq=869.588, config.lora.frequency_offset=0.000
INFO  | ??:??:?? 2 Set radio: region=EU_868, name=LORALR, config=1, ch=1, power=27
INFO  | ??:??:?? 2 Radio myRegion->freqStart -> myRegion->freqEnd: 869.400024 -> 869.650024 (0.250000 mhz)
INFO  | ??:??:?? 2 Radio myRegion->numChannels: 2 x 125.000kHz
INFO  | ??:??:?? 2 Radio channel_num: 1
INFO  | ??:??:?? 2 Radio frequency: 869.587524
INFO  | ??:??:?? 2 Slot time: 42 msec
INFO  | ??:??:?? 2 Set radio: final power level=13
M  SX128x
INFO  | ??:??:?? 2 SX128x init result -12
WARN  | ??:??:?? 2 Radio chip only supports 2.4GHz LoRa. Adjusting Region and rebooting.
```

regarding (3) :- 
```
Configuring upload protocol...
AVAILABLE: cmsis-dap, esp-bridge, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
*** [upload] AssertionError : Missed target configuration for eink0.1
Traceback (most recent call last):
  File "/home/lora/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Action.py", line 1318, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lora/.platformio/platforms/espressif32/builder/main.py", line 35, in BeforeUpload
    env.AutodetectUploadPort()
```

**Comment by mverch67** [comment]
Addional findings:

I investigated why esptool (3) is not working to upload the firmware and found the following:
The platformio port autodetection is not finding the upload port, reason is obviously the capital 'X' in boards/tlora-t3s3-v1.json:     
`"hwids": [["0**X**303A", "0x1001"]]. `
After replacing with lower case 'x' the autodetection works but the connect to the serial port hangs indefinitely.  I solved this by adding the line 
`upload_flags = --no-stub`
to tlora_t3s3_v1/platform.ini
Now, the esptool was able to successfully flash the firmware to the esp32-s3 board. Also, it is required to press boot and reset button prior to uploading the firmware.

However, a drawback is that now also the serial terminal must be closed beforehand, so I prefer to use upload_tool esp-builtin where I can leave the debug terminal connected.

**Comment by mverch67** [comment]
After some further investigations why the esp32-s3 does not automatically start after the upload I found that this is a limitation of the USB CDC mode.
This mode can be disabled in boards/tlora-t3s3-v1.json:
`      "-DARDUINO_USB_CDC_ON_BOOT=0",`
and voilà I don't need to press and hold any buttons anymore and I don't need the --no-stub option. I can just compile&upload without touching the Tlora. The only thing that is left that I need to quit my external serial monitor... but I can use the platformio serial monitor which does this automatically for me :)

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/lilygo-t3s3-v1-0/7343/3
