### ISSUE TITLE
[Feature Request]: Add Support for LilyGo Q10 Keyboard Driver Module

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2311]
### Platform

NRF52, ESP32

### Description

LilyGo offers a [BB Q10 driver module](https://www.aliexpress.us/item/3256804521965718.html) (Note: This product page has multiple options, the one I'm referring to is the first one which is a small pcb that is $9), that allows you to utilize a Q10 keyboard via i2c. I've found this [LilyGo Github repo](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/master/src) which has the Q10 Keyboard info, if that helps but I'm not sure if that's the exact one or not.

If support is added, it would be a great option for compact standalone devices as the size is much smaller than the cardkb. One thing to note, unlike cardkb, these keyboards do not have arrow keys. However, we could possibly utilize the alt button as a modifier and then use wasd for up, left, down, right when modified? 

<img width="479" alt="Screenshot 2023-07-28 at 12 50 44 PM" src="https://github.com/meshtastic/firmware/assets/6912600/453a5f4a-2c20-4587-8856-afd1b78f7ad4">

**Comment by Californian** [comment]
I'd like this for exactly the use case described (standalone communication device) -- if anyone can point me in the right direction I'd be happy to look into contributing!

**Comment by mverch67** [comment]
@rcarteraz I created a draft PR, please install the firmware from the .zip and check if it works for you!

**Comment by caveman99** [comment]
This will be in 2.2.3
