### ISSUE TITLE
[Bug]: Only send NodeInfo in response to a position request, not on the position schedule

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2360]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.1.2

### Description

When a position is sent directly to another node and a response is requested we send a NodeInfo if the device does not have a position.  This works pretty well and at least lets the other user know that the device responded.

We also seem to send an empty NodeInfo on the position schedule if the device has no GPS, and no fixed or phone provided positions which seems unnecessary.

**Comment by GUVWAF** [comment]
I was wondering why I couldn’t replicate this, but I found that it is only sending this to the node that is currently displayed on the screen (if you have one). In fact, calling this `sendNetworkPing` function is done when you enter the power “ON” state and you sent the last ping more than one minute ago.
I agree that this is unnecessary. I also wonder if sending your position to the node that is displayed is even something that is desired?

**Comment by garthvh** [comment]
> I was wondering why I couldn’t replicate this, but I found that it is only sending this to the node that is currently displayed on the screen (if you have one). In fact, calling this `sendNetworkPing` function is done when you enter the power “ON” state and you sent the last ping more than one minute ago.
> I agree that this is unnecessary. I also wonder if sending your position to the node that is displayed is even something that is desired?

Seems undesirable. I only found this because empty position packets crashed the app at one point so I log them.
