### ISSUE TITLE
Few questions max nodes and max hops

### ISSUE THREAD

**Issue by danilomna** [meshtastic/firmware#2368]
Hi

How many node devices are possible on a single meshtastic network? Could we reach 1024?

How many hops are allowed? Max hops number?

Thanks in advance.

**Comment by garthvh** [comment]
Node limit is 80, max hops is 7

**Comment by danilomna** [comment]
Are there any way to make it work for 1k nodes? Some custom change?

Have you ever seen some lora mesh project suitable to 1k nodes?

**Comment by garthvh** [comment]
Even 80 is optimistic and untested.
