### ISSUE TITLE
[Feature Request]: Allow the root MQTT topic msh to be user-configurable

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/firmware#2380]
### Platform

NRF52, ESP32

### Description

Planning ahead for scalability, if the root topic currently hard-coded at msh could be user changable, a single MQTT broker could apply user acls to completely separated meshes on the same box for multi-mesh isolation and scalability.  Something like mqtt.mesh_root (default = msh).

**Comment by caveman99** [comment]
@ghostop14 can you test this?

**Comment by ghostop14** [comment]
Sure thing.  I'll have some time tonight.
