### ISSUE TITLE
[Feature Request]: Per-network support

### ISSUE THREAD

**Issue by tb0hdan** [meshtastic/firmware#2401]
### Platform

ESP32

### Description

Hi,

As one of the Ukrainian community members, I'd like to make a following proposal:

Set up a test environment at the developer side, with MQTT credentials from larger networks, with hardware, that is mostly
available within the regional Meshtastic network and use it to debug reboots, hangs and other issues. 

I am ready to pay for a device dedicated for this purpose. I'll send credentials using secure means when necessary.

Thanks.

**Comment by garthvh** [comment]
What exactly do you need?

**Comment by tb0hdan** [comment]
In our specific case, improved reliability is required. I.e. fewer reboots for MQTT nodes. Right now it ranges from 1-2 per hour on TBEAM devices, which we're using as routers.

**Comment by tb0hdan** [comment]
Plus, select developers will definitely benefit from having real traffic on their devices

**Comment by tb0hdan** [comment]
Any updates on this? Our network seems to be the biggest so far with the highest amount of traffic and consecutive problems.

**Comment by mc-hamster** [comment]
Not sure of the request.

Is this request for dedicated mqtt servers pre region?

**Comment by tb0hdan** [comment]
Our network is already larger than `mqtt.meshtastic.org` is. Both overall and online nodes. I need someone from core developers to reach out, I'll provide MQTT credentials for testing new firmware and debugging issues on big networks. That's what I'm asking for.

**Comment by ut3uku** [comment]
Traffic is a major problem in Ukraine's network. Messages are being delayed or dropping. We cannot rely on it for emergency communication((

**Comment by garthvh** [comment]
Step one is to disable JSON over MQTT, it is not for production.

Step two is to turn down your hop limit if it has been pushed to 7.

The next step is to post a config from one of your connected devices so we can take a look.

**Comment by tb0hdan** [comment]
Hey guys, MQTT is now combined, with 73 nodes online. You should get some nice traffic.

**Comment by tb0hdan** [comment]
![image](https://user-images.githubusercontent.com/201715/235321271-1d94e4f1-b247-4dfc-bcc8-1d9f67f954a8.png)

**Comment by tb0hdan** [comment]
2.1.7 / T-Beam

- 67/80 nodes
-  node_db full erasing... message
- no reboots though

**Comment by tb0hdan** [comment]
![image](https://user-images.githubusercontent.com/201715/235321369-e0513da7-bd5e-4310-a8e6-69a447e9c3f5.png)

Only one message was sent. Duplicates.

**Comment by tb0hdan** [comment]
Also, most attempts to run `meshtastic --nodes` fail with "timeout" error, but when they are successful (rarely), device stops responding to ping:

```
64 bytes from 192.168.3.6: icmp_seq=267 ttl=255 time=3.94 ms
64 bytes from 192.168.3.6: icmp_seq=268 ttl=255 time=2.29 ms


64 bytes from 192.168.3.6: icmp_seq=278 ttl=255 time=3.16 ms
64 bytes from 192.168.3.6: icmp_seq=279 ttl=255 time=2.98 ms
```

**Comment by tb0hdan** [comment]
Okay, got it. Every time any kind of serial command succeeds, device reboots itself

**Comment by tb0hdan** [comment]
![image](https://user-images.githubusercontent.com/201715/235321664-e5d966a6-b84f-4237-a035-a9fb926f2864.png)

**Comment by tb0hdan** [comment]
```

**Comment by tb0hdan** [comment]
```
│  75 │ Gremlen_AFR                  │ 5c2c  │ !a3fb5c2c │ N/A        │ N/A         │ N/A        │ N/A       │ N/A       │ N/A                 │ N/A            │
```

NodeDB doesn't reach more than 75 nodes ever

**Comment by tb0hdan** [comment]
2.1.7 reboots every 44 seconds with current node count

**Comment by garthvh** [comment]
With a large network --info and --nodes are unlikely to work reliably in the python CLI, both of these methods aggregate a bunch of different packets together and is slow. You might try the C# Cli as it probably performs better.

**Comment by garthvh** [comment]
Unless you are using short fast  I would not anticipate getting to 80 nodes.

Nodes like this one are going to create a lot of traffic, 7 hops every minute with many nodes really multiplies quickly. https://mesh.in.ua/grafana/d/Q2DodHa4k/mesh-node?orgId=1&var-nodeId=917327552&refresh=10s

**Comment by garthvh** [comment]
Per @caveman99 The problem with high hop limits is the packet is cascading and multiplying. If you have every router in reach in an ideal network one packet on Hop Limit 7 causes 126 retransmissions.  Unnecessarily high hop limits on some nodes combined with excess telemetry and position packets is likely most of your problem (wifi on a tbeam has issues as well)

You should also make sure that router router client or repeater are only used on stationary nodes with an advantage of some kind (power, height, antenna etc) if everything is a router then there is no advantage to using that mode at all.

**Comment by garthvh** [comment]
Network support is not something the project will be providing.  @jp-bennett may have some interest.
