### ISSUE TITLE
[Feature Request]: Higher priority for manually requested position

### ISSUE THREAD

**Issue by SR7673** [meshtastic/firmware#2413]
### Platform

NRF52, ESP32

### Description

Is it possible to increase the priority for a manual request of the position from a node?
I noticed that my manual request for the position of a node in a 4 hop distance often leads to no result whereas messages come through.
From the Android debug window i see that the priority is "BACKGROUND". If the priority just for manual requests could be increased to something like a message, then this rare event would lead to positive results more likely...

**Comment by tavdog** [comment]
The priority of a location request is set by the phone app.  However the response is hard coded as BACKGROUND unless the device is set as a tracker.  I don't see a way of indicating to a remote node that the location request was manually initiated and to therefore increase the priority.  Also there is a 3 hop limit for location requests as well which might be why you're getting no results when 4 hops are required.
  
`PACKET FROM PHONE (id=0xeb5af42c fr=0x00 to=0x24, WantAck=0, HopLim=3 Ch=0x0 Portnum=3 priority=10)`
