### ISSUE TITLE
Question: are meshtastic doing lbt in EU868 frequencies in order to avoid duty cycle?

### ISSUE THREAD

**Issue by megabyte2010** [meshtastic/firmware#2419]

**Comment by GUVWAF** [comment]
While the firmware does Listen-Before-Talk, in the EU you then also need to perform Automatic Frequency Agility (AFA) to be allowed to exceed the duty cycle. Meaning you have to switch from frequency when you hear someone else, which Meshtastic can’t do, so we can’t ignore it.

The radio will stop transmitting completely when you hit the limit, until it is allowed again. If you experience this now, you can lower some of the broadcast intervals (e.g. [Device Telemetry](https://meshtastic.org/docs/settings/moduleconfig/telemetry#device-metrics-update-interval), [Position](https://meshtastic.org/docs/settings/config/position#broadcast-interval)) or use a faster modem preset and make sure you didn’t set a high hop limit.
