### ISSUE TITLE
[Feature Request]: Create Configuration Option for Messages Displayed on Device's Display

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2427]
### Platform

NRF52, ESP32

### Description

Can we make displaying received messages on the device's display configurable? Additionally, an option to set a timeout period so after xx number of minutes it goes away would be a good option to have as well in case you want them but don't wish for them to persist on the screen, especially after turning the device on/off.

**Comment by RightHandMan1** [comment]
agree, old messages are like old read emails. need to have them timeout, since they dont seem to upload after the cli or android app connects.

**Comment by garthvh** [comment]
I really like the support simplify of being able to tell users that the last message received is the one on the screen. My preference would be not to have to manage this at all from client apps, there may be a case for some management options for a stand alone device but seems unnecessary if you are using the device with a mobile phone on a network with any traffic at all.

**Comment by garthvh** [comment]
There is a support cost to every setting, and they are really painful to remove, I hear from a lot of users and nobody has ever been concerned with this previously.  I get questions about nearly every setting we have so when we add them they need to offer a compelling feature, I am unconvinced this is a compelling feature by itself.

**Comment by garthvh** [comment]
Part of the comprehensive device UI Issue
