### ISSUE TITLE
[Feature Request]: Create Configuration Option for Nodes Displayed on Device's Display

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2428]
### Platform

NRF52, ESP32

### Description

Can we make displaying the nodes on the network on the device's display configurable? There may be times you do not want that information displayed for security or other concerns. At times it's also a bit of a hinderance if you have multiple nodes displayed on the screen that you have to cycle through to the information pages. Adding an option to turn this feature on/off would be great.

**Comment by RightHandMan1** [comment]
It would be nice, to be able to delete the messages from a node, from the cli or app, not just deleting on the app. Deleting the message on the app, does not delete the message on the node. reset_nodedb does not delete a message, only the known nodes, plus thats a little too drastic. removing all power from the node doesnt remove the msg either. If the node is in standalone/wifi mode, keeping the message on the display, just seems like it would consume memory space,etc.

**Comment by mc-hamster** [comment]
> It would be nice, to be able to delete the messages from a node, from the cli or app, not just deleting on the app. Deleting the message on the app, does not delete the message on the node. reset_nodedb does not delete a message, only the known nodes, plus thats a little too drastic. removing all power from the node doesnt remove the msg either. If the node is in standalone/wifi mode, keeping the message on the display, just seems like it would consume memory space,etc.

Please open this as separate request. It's less likely to get lost that way :)

**Comment by garthvh** [comment]
Part of the comprehensive device UI Issue
