### ISSUE TITLE
[Bug]: Crash when sending commands via serial

### ISSUE THREAD

**Issue by micheljung** [meshtastic/firmware#2440]
### Category

Serial

### Hardware

Heltec v2

### Firmware Version

2.1.9

### Description

1. Connect via USB
2. Use the CLI client `2.1.6`
3. Send any command, e. g. `meshtastic.exe --info`
4. Watch the device crash/restart

### Relevant log output

```Shell
Connected to radio
```

**Comment by caveman99** [comment]
It does not crash, but restarts. That is a shortcoming of the python serial libs and the hardware design of the heltec boards. The m5stack also does that. There's no easy solution and if there was one it would have to go into the python client. Try using the c-Sharp CLI instead, that should work better.

**Comment by micheljung** [comment]
Thanks, just found this information:

![image](https://user-images.githubusercontent.com/1864183/232904724-f5ee0ff5-a01e-492e-90b6-96a02d87f27a.png)
https://meshtastic.org/docs/settings/moduleconfig/mqtt
