### ISSUE TITLE
[Bug]: NMEA0183 $GNGGA sentence missing time data/wrong format of string

### ISSUE THREAD

**Issue by samuelhj** [meshtastic/firmware#2451]
### Category

Serial

### Hardware

Not Applicable

### Firmware Version

V2.1.5.23272da beta

### Description

Affects all versions since NMEA0183 implementation.

The $GNGGA string contains field that is not supposed to be there as per this comment on the forums https://meshtastic.discourse.group/t/how-to-on-the-serial-modules-mode-nmea/6785/11?u=samuelhj

Example output: $GNGGA,1681483.279,46XX.XXXX,N,005XX.XXXX,E,0,12,0089,0231,M,0047,M,0,0000*
Excpected output: $GNGGA,hhmmss.ss,46XX.XXXX,N,005XX.XXXX,E,0,12,0089,0231,M,0047,M,0,0000*
(Checksum at the end of the string is omitted in these examples since it's irrelevant)

See construction of NMEA strings: https://gpsd.gitlab.io/gpsd/NMEA.html#_gga_global_positioning_system_fix_data

While not a huge issue, it would be useful to have correct timestamp if users start to connect other applications to this port that could take advantage of the device's own location.

**Comment by fcatt** [comment]
Works for me, thank you!
`$GNGGA,140342.00,4XXX.5634,N,005YY.4790,E,2,12,0089,0356,M,0047,M,0,0000*5C`
