### ISSUE TITLE
[Bug]: flash installation failed on LORA32 (version: Tiora-v2-1-1.6)

### ISSUE THREAD

**Issue by JosefSo** [meshtastic/firmware#2455]
### Category

Serial

### Hardware

T-Lora v2 1.6

### Firmware Version

Tiora-v2-1-1.6

### Description

When I tried to flash this device via browser (Google Chrome) I've got issue (See the screenshot):
<img width="1213" alt="Screen Shot 2023-05-02 at 20 15 44" src="https://user-images.githubusercontent.com/77780368/235727116-69c7255c-6603-471c-a4d8-635e38d39c82.png">

### Relevant log output

```Shell
installation failed
⚠️
Your ESP32-S3 board is not supported.
```

**Comment by JosefSo** [comment]
I checked and you are right it is new T3S3. How do I flash it in this case?

**Comment by megabyte2010** [comment]
> I checked and you are right it is new T3S3. How do I flash it in this case?

Press boot button, keep it pressed and press and release reset button and release boot button. And you need to flash with cli. The browser flasher gives error

**Comment by caveman99** [comment]
This is fixed by now in the web flasher. Not a firmware issue.
