### ISSUE TITLE
Version 2.1.12 Rak4631 no longer gets telemetry. [Bug]: 

### ISSUE THREAD

**Issue by Donnie650** [meshtastic/firmware#2489]
### Category

Hardware Compatibility

### Hardware

Rak4631

### Firmware Version

2.1.12

### Description

After updating and doing a erase and upload this version no longer gives telemetry from my Rak4631 environment module.

**Comment by Donnie650** [comment]
I also returned to version 2.1.11 and started receiving telemetry again also.

**Comment by caveman99** [comment]
Fixed in 2.1.13
