### ISSUE TITLE
[Bug]: T-Echo "Shutting Down" text is cropped

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/firmware#2497]
### Category

Hardware Compatibility

### Hardware

T-Echo

### Firmware Version

2.1.11

### Description

![20230517_144327](https://github.com/meshtastic/firmware/assets/117498748/960a6526-c77c-497e-ac89-5720f2161955)
When shutting down the T-Echo, the "Shutting Down..." text crops the first two letters.  I have the same issue on two T-Echo's

**Comment by markbirss** [comment]
https://github.com/meshtastic/firmware/pull/2499
