### ISSUE TITLE
[Bug]: T-Echo: After re-boot, displays very old message.

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/firmware#2501]
![stale message](https://github.com/meshtastic/firmware/assets/121647809/4365ac46-a9ae-4bab-9d9b-39eea8bee56a)
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.1.11.5ec624d

### Description

After re-boot, the screen always shows the same very old message even though there have been many more recent messages from the displayed radio.

**Comment by garthvh** [comment]
I don't think this is just the techo.

**Comment by caveman99** [comment]
the device has ONE slot where it stores the last received message. If that slot is occupied the message will be displayed. It will be overwritten when a new message arrives.
