### ISSUE TITLE
[Bug]: T-Echo: Screen flashes periodically (reset?)

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/firmware#2502]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.1.11.5ec624d

### Description

Screen flashes black periodically. Sometimes seconds between flashes, sometimes minutes. Seems random.

https://github.com/meshtastic/firmware/assets/121647809/e70417b9-8b81-4f77-bf28-d7c58eb1669f

**Comment by prokrypt** [comment]
Um, maybe that's just how e-ink displays work... But maybe someone else who actually has this device can comment.

**Comment by thebentern** [comment]
This is expected behavior, as the e-ink display has to "wipe" to ensure no pixels get stuck in a previous state. :-)
