### ISSUE TITLE
[Feature Request]: Visually not clear where to click to save

### ISSUE THREAD

**Issue by TheRealCryss** [meshtastic/firmware#2504]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.1.12

### Description

It isn't obvious _where_ exactly to click in order to save the settings. There should be a visual hint for that when the mouse is not over the area and when it hovers over it as well. Clicking on Save (Speichern in DE) which highlights up when there was a change in the input fields doesn't save, which one would expect. Instead you have to click in a part of the pop-up message.

This report is for the current Meshtastic app from the Appstore on MacOS. I haven't tested it on other OSs.

![Bild 21 05 23 um 12 20](https://github.com/meshtastic/firmware/assets/128715006/d9fb24ff-c0a6-4fc6-877c-0eac67f192fe)

**Comment by prokrypt** [comment]
This belongs @ https://github.com/meshtastic/Meshtastic-Apple/issues

**Comment by prokrypt** [comment]
I believe this belongs @ https://github.com/meshtastic/Meshtastic-Apple/issues

**Comment by TheRealCryss** [comment]
I'm sorry. Should I delete it or can it be moved?

**Comment by garthvh** [comment]
It is a catalyst issue, hopefully they address it soon, no need to open a bug
