### ISSUE TITLE
[Board]: variant/diy/v1_2 - DevKit C4 / Lolin32 / Lolin32 lite  

### ISSUE THREAD

**Issue by clownjoy** [meshtastic/firmware#2509]
### SOC

ESP32

### Lora IC

SX126x

### Product Link

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html

### Description

Hi Meshtastic Team,

please add proposed DIY board profile. It seems that it is a big family of such boards having same GPIO layout. It can similarly used as variant/diy/v1_1. In my case I've set new profile varian/diy/v1_2 with GPIO pin adoptions . With regards, 

Jozef

**Comment by caveman99** [comment]
The Pull Request was closed, since the Devkit C4 target will work with diy_1
