### ISSUE TITLE
[Board]: STM32WL (Seeed Studio Wio-E5)

### ISSUE THREAD

**Issue by GUVWAF** [meshtastic/firmware#2539]
### SOC

Other

### Lora IC

SX1262 (inside STM32WL)

### Product Link

https://www.seeedstudio.com/LoRa-E5-mini-STM32WLE5JC-p-4869.html

### Description

There is currently a variant of the firmware for this architecture with which the device boots and the radio initializes, but LittleFS is not working. See #2265.

Should be a very low-power device as it uses the same processor as NRF52 (single-core ARM Cortex-M4) running at lower clock frequency, no Bluetooth, and the radio is integrated on the same chip.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/stm32wl55-mesh-lora/7820/2

**Comment by Dr-Gandalf** [comment]
Is it really worth to develop this HW? It only has 256kB flash memory, if it ever works, it will be really limited, considering the that other ARM devices compiles to ~600kB binary file. It may be better to implement a stm32wb5mmg + sx1262 https://www.st.com/en/microcontrollers-microprocessors/stm32wb5mmg.html this will have Bluetooth and 1MB flash, just an idea.

**Comment by thebentern** [comment]
It will be worthwhile as an ultra low-power repeater
