### ISSUE TITLE
[Bug]: Static IP configuration doesn't work

### ISSUE THREAD

**Issue by micheljung** [meshtastic/firmware#2543]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.1.11

### Description

Connect a RAK with an ethernet module and DHCP enabled, it will successfully get an IP address (e. g. 192.168.1.223) and can be pinged.

Switch to the static IP configuration, set the exact same IP address (192.168.1.223) and appropriate subnet mask (255.255.255.0) and you can no longer ping the device.

**Comment by garthvh** [comment]
Are you converting the ip address to an integer?

**Comment by micheljung** [comment]
No, I'm setting the IP address via Android App and it enforces x.x.x.x

In the debug panel of the app, it correctly shows the IP configuration in decimal values.
