### ISSUE TITLE
[Bug]: T-Echo Device can't be turned off

### ISSUE THREAD

**Issue by Burnwald** [meshtastic/firmware#2553]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.1.15

### Description

While holding down power off button you receive the text on the screen "shutting down", but instead of completely turning off, device always goes to sleep. Same happens after sending command "shutdown" from mobile application. 

https://photos.app.goo.gl/hbn3V7m6KzPE2rJbA

**Comment by Burnwald** [comment]
https://photos.app.goo.gl/hbn3V7m6KzPE2rJbA

**Comment by garthvh** [comment]
Nrf52 devices like the techo go to deep sleep for shutdown. The techo has a gps light that is not controllable that never turns off.

**Comment by garthvh** [comment]
https://github.com/meshtastic/firmware/issues/1493
