### ISSUE TITLE
[Feature Request]: More Flexible Location Data Configuration

### ISSUE THREAD

**Issue by jp-bennett** [meshtastic/firmware#2563]
### Platform

NRF52, ESP32

### Description

Location data is currently sent over the Primary channel, if enabled at all. It's rather difficult to change things around, to send location data to a different channel. When using a Meshtastic radio for multiple purposes, like family tracking and also disaster recovery, a user might want a simple way to change on what channels location data is sent. For normal operation, only the private, primary channel would get location data. But right after a disaster, the location could be turned on for everyone.

I suggest a pair of options for each channel, to send and receive location data. Easily configured by end users, even non-technical users. This would allow meshtastic users to quickly adapt to an emergency, and still manage their privacy during normal times.

Edit: Radios also respond to location requests over non-primary channels, making it impossible to limit location data to a subset of channels. Short term suggest simply refusing to respond to location request over non-primary channel. Longer term, there should be a mechanism to limit channels to respond to location requests. Maybe limit responses to the channels configured to broadcast location.

**Comment by jp-bennett** [comment]
Turning on sending of location data on non-primary channels should trigger a "big annoying warning" that it can cause massive slow-downs to the mesh.

**Comment by RightHandMan1** [comment]
I'm kinda with you on this one. It would also solve an MQTT issue where Primary ch dont match over many nodes, but a matching secondary(s) would. Especially when SHTF , no internet is available, and a local laptop w a wifi router and MQTT locally hosted,, is providing comm to a neighborhood or SAR event..  But, there would probably need a number after the peer to indicate which 'channel' the node is currently seen on,etc.

**Comment by jp-bennett** [comment]
I've been thinking more about this, and I'm wondering if there's a compelling reason to actually have a "Primary" channel. It seems like a meaning distinction, since channel 0 is always primary.

**Comment by garthvh** [comment]
The channel index is an app only construct, it is not sent over the mesh.

**Comment by garthvh** [comment]
Got all sorts of new location flexibility
