### ISSUE TITLE
[Bug]: Device telemetry encodig (INA219 - current and volage sensisng) is wrong. This happens on rels > 2.1.13

### ISSUE THREAD

**Issue by vinloren** [meshtastic/firmware#2602]
### Category

Other

### Hardware

T-Lora v2 1.6

### Firmware Version

2.1.18

### Description

on Tlora2 -1-1-6 device  the encoding of the INA219 telemetry data is wrong as you can see in the attached screen shot: the voltage value is 22.94V and the current is ‘infinitymA’. This happens also on rel 2.1.15 and 2.1.17, 2.1.13 is working well instead.
![bad_telemetry](https://github.com/meshtastic/firmware/assets/2716553/7ec5e0d2-c01d-4c05-a9b8-5aed6ebc6afa)

**Comment by pdxlocations** [comment]
I can duplicate this bug on tlora V2-1 1.6
![ina219bug](https://github.com/meshtastic/firmware/assets/117498748/065515d2-3949-4f1e-9d58-7ccad7ab6967)

**Comment by pdxlocations** [comment]
@thebentern  could be something in #2536 ?

**Comment by thebentern** [comment]
> @thebentern  could be something in #2536 ?

That's what I'm thinking

**Comment by vinloren** [comment]
It seems there is a relationship with #2536
