### ISSUE TITLE
[Bug]: INA260 is showing frozen telemetry data with strange numbers

### ISSUE THREAD

**Issue by snowman982** [meshtastic/firmware#2605]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.1.15 - 2.1.18

### Description

Hardware: RAK4631 with RAK12002 clock module + SHT31 and INA260 module.

On firmware 2.1.14 both sensors were giving correct telemetry data without any problems.

When reflashing to firmware 2.1.15 or newer, the sensor reading from the SHT31 still works as it should, but the sensor reading from the INA260 shows frozen numbers of "5368709.00V" and "-1.3mA".

When running the debug (meshtastic --noproto) on firmware 2.1.14,  both the SHT31 and INA260 are found on the I2C bus and both are then initialized.

But when i run the debug on firm 2.1.18, both sensors are still found on the I2C bus, but only the SHT31 seems to initialize.

![Screenshot_20230710_135047_Meshtastic](https://github.com/meshtastic/firmware/assets/139131936/c63baddc-9671-4452-aa62-851426a14bac)

### Relevant log output

```Shell
INFO  | 13:03:46 21 [EnvironmentTelemetryModule] Environment Telemetry: Initializing
INFO  | 13:03:46 21 [EnvironmentTelemetryModule] Init sensor: SHT31
INFO  | 13:03:46 21 [EnvironmentTelemetryModule] Opened SHT31 sensor on default i2c bus
INFO  | 13:03:47 22 [EnvironmentTelemetryModule] (Sending): barometric_pressure=0.000000, current=-1.250000, gas_resistance=0.000000, relative_humidity=32.820000, temperature=25.879999, voltage=5368709.00000
```

**Comment by thebentern** [comment]
I believe this is the same issue as #2602. Closing so we can track it in a single issue
