### ISSUE TITLE
[Feature Request]: Ham mode updates

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2622]
### Platform

NRF52, ESP32

### Description

* [x] Remove encryption keys from all secondary channels
* [x] Delete the admin channel
* [x] Set Device.RebroadcastMode to LocalOnly

**Comment by code8buster** [comment]
https://github.com/meshtastic/firmware/blob/master/src/modules/AdminModule.cpp#L649
Local_Only is implemented already
