### ISSUE TITLE
[Board]: Nano G2 Ultra

### ISSUE THREAD

**Issue by neilhao** [meshtastic/firmware#2658]
### SOC

NRF52

### Lora IC

SX1262

### Product Link

https://wiki.uniteng.com/en/meshtastic/nano-g2-ultra

### Description

The primary design goal of the Meshtastic[[2]](https://wiki.uniteng.com/en/meshtastic/nano-g2-ultra#fn2) Mesh Device Nano G2 Ultra is to reduce power consumption and improve battery life by using the low power MCU NRF52840 and optimizing the power relatived designs. The typical battery life is optimized to be about 3.5 days. Nano G2 Ultra and [Nano G1 Explorer](https://wiki.uniteng.com/meshtastic/nano-g1-explorer) have exactly the same Lora front-end circuit design and internal wideband Lora antenna, which supports frequencies from 815 Mhz to 940 Mhz. The wideband antenna, combined with an optimized wideband Lora RF frontend circuit, enables the Nano G2 Ultra to work with the majority of regions' LoRa frequency bands around the world without the need for antenna changes. The design of the Nano G2 Ultra also takes into account the potential effect of the human body on its antenna performance, [ensuring optimal RF performance even when carried in a pocket](https://wiki.uniteng.com/meshtastic/nano-g1-explorer#human-body-near-antenna-hbn).

<html><body>
<h4 id="power-consumption-and-features-comparison-of-nano-g2-ultra-and-nano-g1-explorer" class="toc-header">Power Consumption and Features Comparison of Nano G2 Ultra and Nano G1 Explorer</h4> <div class="table-container">

Editions | Nano G2 Ultra | Nano G1 Explorer
-- | -- | --
Core Research Areas | Low Power Design | Human Body Near Antenna (HBN) Wideband High Radiation Efficiency Planar Antenna and RF Front-end Design
Product Status | ACTIVE | ACTIVE
Current Hardware Version | 19 Jun 2023 | 06 Mar 2023
Lora RF Max Output Power | Up to 22 dBm | Up to 22 dBm
LoRa Transceiver | SX1262 | SX1262
Lora Operation Frequency | Wideband from 815 Mhz to 940 Mhz | Wideband from 815 Mhz to 940 Mhz
MCU | NRF52840 | ESP32
WIFI | - | YES
Bluetooth | v5.4 | v4.2
Satellite Navigation | GPS, BDS | GPS, BDS
Real-Time Clock (RTC) | NXP PCF8563 | -
USB Connector | Type C | Type C
Screen | 1.3 Inch OLED Screen | 1.3 Inch OLED Screen
Battery | Optional 3.7V 603450 JST 1.25mm Rechargeable Li-Polymer Battery | Optional 3.7V 603450 JST 1.25mm Rechargeable Li-Polymer Battery
Power Input Socket | USB Type C, JST 1.25mm Connector for Rechargeable Li-Polymer Battery | USB Type C, JST 1.25mm Connector for Rechargeable Li-Polymer Battery
Antenna | Build In Wideband PCB Antenna | Build In Wideband PCB Antenna
Accessories | Build In 10 Pin FPC Connector (0.5mm Pitch, 1x I2C, 6x GPIO, VCC3V3 and GND)Optional I2C Extension Board (1x GROVE I2C Socket and 1x SparkFun QWIIC I2C Socket for Sensors and Keyboard) | -
Typical Average Power Consumption | 14.24 mA @ 4.3V (Lora TX Power = 22 dBm, GPS OFF, Screen OFF, Two Nodes in Network) | 70.50 mA @ 4.3V (Lora TX Power = 22 dBm, GPS Low Power Mode, Screen OFF, Two Nodes in Network)
Typical Scenarios | Hiking,  Pilot, Skiing, Work with the majority of regions' LoRa frequency bands  around the world without the need for Antenna changes. The typical battery life is optimized to be about 3.5 days. | Hiking,  Pilot, Skiing, Work with the majority of regions' LoRa frequency bands  around the world without the need for Antenna changes. The typical battery life is optimized to be about	16 Hours.

</div> <p>In
 general, Nano G2 Ultra is not designed to replace Nano G1 Explorer, 
Nano G2 Ultra focuses on low power, and Nano G1 Explorer supports WIFI.</p>

**Typical RF Performance**
<html><body>

Item | Description
-- | --
Lora Operation Frequency | 815 Mhz to 940 Mhz
Lora Max RF Output Power | 22 dBm
VSWR of Lora PCB Antenna | < =1.5 @ 915 MHz and  868Mhz
Gain of Lora PCB Antenna | 2.0 dBi, Omni-directional
Impedance Bandwidth of Lora PCB Antenna | 815 Mhz to 940 Mhz for VSWR < = 2
Polarization of Lora PCB Antenna | Linear
High-Precision Frequency Reference for Lora | 32MHz TCXO (+-1.5 ppm)
Positioning And Navigation Module | Build-in GPS Module, LNA and Omni-directional Antenna. GPS and BDS are supported
VSWR of GPS PCB Antenna | < =2 @ 1575.42 MHz, GPS L1 Band
Impedance Bandwidth of GPS PCB Antenna | 1474 Mhz to 1590 Mhz for VSWR <= 2

</body>
</html>

**Comment by code8buster** [comment]
Support added with #2660
