### ISSUE TITLE
[Bug]: T-deck - Freetext last character

### ISSUE THREAD

**Issue by Szetya** [meshtastic/firmware#2692]
### Category

Other

### Hardware

T-Deck

### Firmware Version

2.1.21.97d7a89

### Description

In Freetext mode, the last character is not sent.

**Comment by mverch67** [comment]
I cannot reproduce this. The messages are receives as displayed. 
Could you provide logs?

**Comment by caveman99** [comment]
This happens when you tell the firmware to add the bell character. The math is wrong, it replaces the last char instead of appending it.

**Comment by Szetya** [comment]
Thank you for your reply! This setting solved the problem! Shall we close the issue or should it remain open? I leave it to you!

**Comment by Szetya** [comment]
Thank you very much! I think I'll close with this. :)
