### ISSUE TITLE
[Bug]: T-Echo Button to switch display view not working

### ISSUE THREAD

**Issue by daniel-hofer** [meshtastic/firmware#2736]
### Category

Hardware Compatibility

### Hardware

T-Echo

### Firmware Version

2.2.2.f35c7be

### Description

Since 2.2.x the Button on the left upper side of the T-Echo does nothing with the screen but the red LED blinks after pressing the button.
So I cannot switch the page of the display

**Comment by caveman99** [comment]
![t-echo-lilygo-29bb1163f14cb471056c6067b6acd204](https://github.com/meshtastic/firmware/assets/25002/c94258aa-193d-438a-9b8f-f8230f372f80)

Are you sure you mean the UPPER left button? That's reset. LOWER left is the user button.

**Comment by daniel-hofer** [comment]
> ![t-echo-lilygo-29bb1163f14cb471056c6067b6acd204](https://user-images.githubusercontent.com/25002/261990044-c94258aa-193d-438a-9b8f-f8230f372f80.jpg)
> 
> Are you sure you mean the UPPER left button? That's reset. LOWER left is the user button.

Oh no, sorry about that, my mistake! I got the keys mixed up because my other Node, a heltec v.3, has them the other way around. Sorry! I'll print myself a label for the T-Echo.
