### ISSUE TITLE
[Board]: Heltec ESP32-C3 HT-CT62

### ISSUE THREAD

**Issue by markbirss** [meshtastic/firmware#2740]
### SOC

ESP32

### Lora IC

SX1262

### Product Link

https://heltec.org/project/ht-ct62/

### Description

Pinout for the Module
https://resource.heltec.cn/download/HT-CT62/HT-CT62.png

Heltec provides a ready to use backplate for the HT-C62
https://heltec.org/product/esp-dev-backplane/

**Comment by caveman99** [comment]
This will be in 2.2.3 release
