### ISSUE TITLE
[Bug]: Mesh algoritm 

### ISSUE THREAD

**Issue by MasterSPB** [meshtastic/firmware#2761]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

any

### Description

If I understood the doc correctly: https://meshtastic.org/docs/overview/mesh-algo
the message will be forwarded by the farthest node,
but if we simulate a situation where there are several nodes near the sender, while the ROUTER node may be closer than another CLIENT node, because of this, the router will not relay messages, while the technical characteristics of the router are much better and it could transmit the message much further.
please see small example:
green - sender 
orange - client Node 1 
blue - client node 2
red - router node
black - other nodes
![example](https://github.com/meshtastic/firmware/assets/5583890/54ac07e3-10a0-4358-ad9e-a04885ac4272)

suggestion: node with type ROUTER - broadcasting messages every time

**Comment by GUVWAF** [comment]
This is already the case. Devices with the same role indeed compete by SNR, but the Router/Repeater/Router_Client get priority over Clients as explained [here](https://meshtastic.org/docs/settings/config/device#role).
