### ISSUE TITLE
[Bug]: heltec v3 bootloop

### ISSUE THREAD

**Issue by daniel-hofer** [meshtastic/firmware#2787]
### Category

Hardware Compatibility

### Hardware

Heltec V3

### Firmware Version

2.2.5.8255128

### Description

After update from 2.2.4 to 2.2.5 the heltec v3 
reboots continuously.
Now I try a flash without updating...

### Relevant log output

```Shell
DEBUG | 18:18:08 30 [Power] Battery: usbPower=0, isCharging=0, batMv=4013, batPct=79
INFO  | 18:18:10 31 [NodeInfoModule] Sending our nodeinfo to mesh (wantReplies=1)
INFO  | 18:18:10 31 [NodeInfoModule] sending owner !fa8252a4/R_LEHEN_MQTT/TBOT
DEBUG | 18:18:10 31 [NodeInfoModule] Initial packet id 764582104, numPacketId 4294967295
DEBUG | 18:18:10 31 [NodeInfoModule] Update DB node 0xfa8252a4, rx_time=1694542690, channel=0
DEBUG | 18:18:10 31 [NodeInfoModule] handleReceived(LOCAL) (id=0x2d9298da fr=0xa4 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=4 WANTRESP rxtime=1694542690 priority=10)
DEBUG | 18:18:10 31 [NodeInfoModule] No modules interested in portnum=4, src=LOCAL
DEBUG | 18:18:10 31 [NodeInfoModule] localSend to channel 0
DEBUG | 18:18:10 31 [NodeInfoModule] Add packet record (id=0x2d9298da fr=0xa4 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=4 WANTRESP rxtime=1694542690 priority=10)
DEBUG | 18:18:10 31 [NodeInfoModule] Expanding short PSK #1
DEBUG | 18:18:10 31 [NodeInfoModule] Using AES128 key!
DEBUG | 18:18:10 31 [NodeInfoModule] ESP32 crypt fr=fa8252a4, num=2d9298da, numBytes=47!
DEBUG | 18:18:10 31 [NodeInfoModule] enqueuing for send (id=0x2d9298da fr=0xa4 to=0xff, WantAck=0, HopLim=3 Ch=0x8 encrypted rxtime=1694542690 priority=10)
DEBUG | 18:18:10 31 [NodeInfoModule] txGood=0,rxGood=0,rxBad=0
DEBUG | 18:18:10 31 [RadioIf] SX126x standby failed with error -707

assert failed: void SX126xInterface<T>::setStandby() [with T = SX1262] SX126xInterface.cpp:199 (err == RADIOLIB_ERR_NONE)


Backtrace: 0x4037851e:0x3fcebd30 0x40381695:0x3fcebd50 0x40387dc1:0x3fcebd70 0x42013122:0x3fcebea0 0x420129ee:0x3fcebec0 0x420174b7:0x3fcebee0 0x42017524:0x3fcebf00 0x42143c3e:0x3fcebf20 0x420060ad:0x3fcebf40 0x42006162:0x3fcebf60 0x42031781:0x3fcebf80 0x420110c2:0x3fcebfb0 0x42066b4d:0x3fcebfd0




ELF file SHA256: 47d14f64d3726508

E (13635) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
```

**Comment by daniel-hofer** [comment]
After erase and install, I'm not able to set the Region, after reboot, the region is unset again:
DEBUG | ??:??:?? 93 [Router] SX126x standby failed with error -707

assert failed: void SX126xInterface<T>::setStandby() [with T = SX1262] SX126xInterface.cpp:199 (err == RADIOLIB_ERR_NONE)


Backtrace: 0x4037851e:0x3fceb5e0 0x40381695:0x3fceb600 0x40387dc1:0x3fceb620 0x42013122:0x3fceb750 0x42012fc3:0x3fceb770 0x421441eb:0x3fceb790 0x42143fd5:0x3fceb7b0 0x42013b33:0x3fceb7d0 0x4201f6a0:0x3fceb7f0 0x4201f78b:0x3fceb810 0x4202059d:0x3fceb830 0x4201f50a:0x3fceba30 0x42013392:0x3fcebc30 0x42018409:0x3fcebc70 0x420184f5:0x3fcebc90 0x42018515:0x3fcebcb0 0x42017b19:0x3fcebce0 0x42006162:0x3fcebd00 0x42031781:0x3fcebd20 0x420110c2:0x3fcebd50 0x42066b4d:0x3fcebd70




ELF file SHA256: 47d14f64d3726508

E (4506) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4212ea71
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a68
entry 0x403c98d4
E (364) esp_core_dump_flash: No core dump partition found!
E (364) esp_core_dump_flash: No core dump partition found!
▒▒@INFO  | ??:??:?? 0

**Comment by jp-bennett** [comment]
> After update from 2.2.4 to 2.2.5 the heltec v3
> reboots continuously.

Please give the artifacts here a try, and see if this fixes the issue: https://github.com/meshtastic/firmware/actions/runs/6163729432#artifacts

**Comment by mverch67** [comment]
This affects also:

- bpi_picow_esp32_s3
- heltec_wireless_paper
- heltec_wsl_v3
