### ISSUE TITLE
[Bug]: Despite disabled air quality module, the data is displayed

### ISSUE THREAD

**Issue by memo-567** [meshtastic/firmware#2797]
### Category

Hardware Compatibility

### Hardware

T-Beam

### Firmware Version

2.2.6.b53cb38 Alpha

### Description

Despite disabled air quality module, the data is displayed both, locally and via mesh.

Sensor: BME680

![202309151500](https://github.com/meshtastic/firmware/assets/58190287/a60b5292-9c0a-4925-b381-dd0a32864342) 

![202309151510](https://github.com/meshtastic/firmware/assets/58190287/ba712eb5-c5b4-4f19-bc8c-005ee78d3d6d)

**Comment by garthvh** [comment]
That data is part of the environment metrics if you have a 680. Air quality is a different module that uses AQI specific features.

**Comment by memo-567** [comment]
Ah okay. Thanks for the info 😀
