### ISSUE TITLE
[Bug]: GPS is never detected on monteops_hw1

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/firmware#2801]
### Category

Hardware Compatibility, Other

### Hardware

Rak4631

### Firmware Version

2.2.6.b53cb38

### Description

Look like regression.
GPS module is EVA-M8E-0.

**Comment by jp-bennett** [comment]
Anything interesting in the log output? Does the device eventually start getting GPS updates? We try to fail safe by listening at 9600 baud even with nothing found. Is that GPS available on a Rak module?

**Comment by D4rk4** [comment]
It appears that only the monteops_hw1 variant is malfunctioning. I have conducted tests using various firmware versions that incorporate the new GPS detection logic and discovered that the native rak4631 firmware variant operates correctly.

**Comment by jp-bennett** [comment]
Are any of these available as hardware samples?

**Comment by D4rk4** [comment]
@jp-bennett I will send you one of them when the next test batch arrives.
