### ISSUE TITLE
Set hop_limit to default when set by user to a bad value

### ISSUE THREAD

**Issue by RicInNewMexico** [meshtastic/firmware#2805]
Conversation with garth led to the thinking that, rather than setting hop_limit to the max of 7 when a bad (>7 hop) value is configured, we should maybe just cause invalid values to revert back to the default hop_limit of 3.

Thinking is that anyone setting their device to a value over the maximum of 7 is likely doing so arbitrarily and without doing sufficient research into the effect that hop count has on the overall network. As the network they are operating on may not be their own, especially in large event settings like Burning Man and Defcon, reverting back to the default on an invalid entry would help limit network flooding / congestion.

**Comment by jp-bennett** [comment]
Ideally with a message, to avoid a stream of bug reports?
