### ISSUE TITLE
[Bug]: tWatch s3 screen never sleeps with newest prerelease

### ISSUE THREAD

**Issue by me639276639936** [meshtastic/firmware#2818]
### Category

Hardware Compatibility, Other

### Hardware

T-Watch

### Firmware Version

2.2.7.e8970ad 

### Description

After updating to latest prelease, watch screen does not sleep. Always on.

**Comment by mverch67** [comment]
Can you please check the display settings. What value is set for "Screen timeout" ?

**Comment by me639276639936** [comment]
I see. I guess that is something I have to update after the update. 

Thanks!! Works now and I feel dumb. Hahaha

**Comment by mverch67** [comment]
> I see. I guess that is something I have to update after the update.
> 
> Thanks!! Works now and I feel dumb. Hahaha

You probably did a flash erase during the update witch sets all values to default (= no screen timeout).
