### ISSUE TITLE
[Feature Request]: Implement RTC awake from deep sleep for NRF52

### ISSUE THREAD

**Issue by andrekir** [meshtastic/firmware#2822]
### Platform

NRF52

### Description

right now we're only using low-level `sd_power_system_off()` for deep sleep and [it's not using the msecToWake parameter](https://github.com/meshtastic/firmware/blob/master/src/platform/nrf52/main-nrf52.cpp#L158-L198) (ie. to wake up after N seconds).

[RAK suggests ~using FreeRTOS~](https://github.com/RAKWireless/WisBlock/blob/master/examples/RAK4630/communications/LoRa/LoRaWAN/Low_Power_Example.md)

if this is something that could be implemented it would allow, for example, SENSORS running for very long periods (months?) without a charge.

**Comment by jp-bennett** [comment]
If I understand it, this would mean converting our entire codebase away from using the Arduino threads concurrency library, to using full RTOS, which is very involved.

**Comment by andrekir** [comment]
got it, thanks. so the FreeRTOS method is not viable.

right now we're only using low-level `NRF_POWER->SYSTEMOFF = 1;` for deep sleep and [it's not using the `msecToWake` parameter](https://github.com/meshtastic/firmware/blob/master/src/platform/nrf52/main-nrf52.cpp#L158-L198) (ie. to wake up after N seconds).

the other examples I found require an RTC to generate an interrupt and not sure our RTC lib supports that.

**Comment by jp-bennett** [comment]
Would we do nearly as well, to just power everything down, like the lora chip, GPS, BLE, and LEDs, and then do a long delay() call?

**Comment by andrekir** [comment]
that's a great idea. perhaps we can get into sub-mA power draw using these [NRF power states](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.s132.api.v3.0.0%2Fgroup___n_r_f___s_o_c___e_n_u_m_s.html&anchor=ga66c4a4f3902bf8dfd3751c32e6589790):

```
sd_power_mode_set(NRF_POWER_MODE_LOWPWR) // low power
delay(secToWake)
sd_power_mode_set(NRF_POWER_MODE_CONSTLAT) // default
```

also, this might need to go into NRF52 Light Sleep logic (for TRACKERs and SENSORs).

**Comment by andrekir** [comment]
for simplicity sake, going for RTC awake on this request, then open a separate one for low-power states for TRACKER/SENSOR roles.

current RTC libs: [PCF8563](https://github.com/lewisxhe/PCF8563_Library) & [Melopero_RV-3028](https://github.com/melopero/Melopero_RV-3028_Arduino_Library).

PCF8563 example: https://github.com/Xinyuan-LilyGO/T-Echo/blob/main/examples/Sleep/Sleep.ino
