### ISSUE TITLE
[Feature Request]: Filter out messages from unknown user (seq messages)

### ISSUE THREAD

**Issue by hb9eue** [meshtastic/firmware#2828]
### Platform

ESP32

### Description

Hi

Over MQTT some devices seem to be spaming sequentially increasing messages starting with the string 'seq' from 'unknown user'. So those messages can not be silenced and end up using allowed LORA transmit time on 868Mhz in LongFast

I have not yet found a way to filter them, not even with a mosquito MQTT bridge in between which would only allow to filter topic, not content.

I wonder if there is a way to filter such messages.

-Benoît-

**Comment by garthvh** [comment]
You can do this a number of ways.  You can ignore 3 nodes on android, there is a toggle to ignore all range test messages in the apple app.  The latest firmware will not push those messages out on the public mqtt.
