### ISSUE TITLE
[Bug]: T-Lora Lilygo T3S3 2.2.8 reboot not working

### ISSUE THREAD

**Issue by NickDolfin** [meshtastic/firmware#2829]
### Category

Other

### Hardware

Other

### Firmware Version

2.2.8

### Description

After changing parameters in using firmware 2.2.7 the device reboots automatically. Good!
This does not happen in 2.2.8. I have to use the reset button. In addition changing to a power supply that is not attached to a computer results in no startup.

I have no idea what to do. I reflashed the older 2.2.7 in it and it works flawlessly.

**Comment by thebentern** [comment]
Is this issue still occurring?

**Comment by NickDolfin** [comment]
* I do not know. I have not checked it lately.*

**Comment by sergeybe2** [comment]
This bug is actual for 2.2.14.

**Comment by thebentern** [comment]
Just tested rebooting via the admin command and implicit reboot on config change for my T3S3. It's working flawlessly. Something is likely incorrect with your configuration or setup.
