### ISSUE TITLE
[Bug]: GPS Module not found on Nano G1 Explorer

### ISSUE THREAD

**Issue by Eric-Sparks** [meshtastic/firmware#2832]
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

2.2.7.e8970ad.alpha

### Description

When upgrading from 2.2.4 alpha, and before, to 2.2.7 alpha the GPS module on the Nano G1 Explorer isn't detected.  I've been able to recreate this problem on two of four devices I have.  Upgrading to the latest firmware (2.2.8 alpha) does not fix the problem.

**Comment by jp-bennett** [comment]
Can you check the position configuration, whether GPS_RX_PIN and GPS_TX_PIN are set differently in the units that are failing to detect GPS? The boot log output of the working and non-working devices would be helpful as well. Thanks!

**Comment by jp-bennett** [comment]
I believe this should be fixed in the 2.2.10 Alpha release. Let us know if there are further problems.
