### ISSUE TITLE
[Bug]: T-Beam GPS LED

### ISSUE THREAD

**Issue by NickDolfin** [meshtastic/firmware#2844]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.2.9.47301a5 alpha

### Description

The red gps led in my Tbeam (with m8n chip) is not blinking anymore using the 2.2.9 alpha firmware.
Using the older firmwares the led does blink properly.

**Comment by jp-bennett** [comment]
This is probably expected, with the new GPS powersave code. Do you have GPS position enabled on your T-beam, and is it working as expected?

**Comment by NickDolfin** [comment]
Hi,

I just tested it briefly.

Apparantly, the led flashes after a position has been detected wile using the gps update interval.
I think it works as it should.

I will do more testing to fully analyze the gps update interval...

Stay tuned for an update.

**Comment by NickDolfin** [comment]
small update:

It appeasr that the gps update rate is correct.
However, the reported (with an ipad attached to a different esp32 board) number of sats is not correct: It remeains at 0 (zero).

**Comment by NickDolfin** [comment]
esp32 bumped to 2.2.9
Still 0 sats reported in the meshtastic bluetooth app.

**Comment by jp-bennett** [comment]
We're also working an issue with the T-beam 1.2 revision, where the GPS is behaving strangely. Can you check whether your board is a 1.2? There is a label right beside the Lora Antenna connector on the board.

**Comment by garthvh** [comment]
Number of sats is a position flag that must be enabled under position settings for it to be sent to the app

**Comment by NickDolfin** [comment]
White silkscreen on PCB near lora antenna:
V22_V1.1
202110222.

Near edge of pcb:
Sticker with CE mark.
FCC ID: 2ASYE-T-BEAM
Model: T-BEAM-V1.1

**Comment by NickDolfin** [comment]
@garthvh  Where do you set that flag?
I cannot find it:

![Capture](https://github.com/meshtastic/firmware/assets/121138495/f4d28ff0-879f-4e6b-9edb-bcde6b064dec)

**Comment by NickDolfin** [comment]
note to myself: meshtastic --pos-fields SATINVIEW
