### ISSUE TITLE
[Feature Request]: Raspberry pi pico w Bluetooth use, uart for lora transceivers and i2c for oled display

### ISSUE THREAD

**Issue by Tfjjjastro** [meshtastic/firmware#2886]
### Platform

ESP32

### Description

is:open please do something in firmware for pico w which uses i2c for oled display, uart for lora transceiver and device Bluetooth to connect with pico and i am using lora e32 900t30d cdebyte module do something i need help

**Comment by garthvh** [comment]
We are only able to support SPI radios.

**Comment by GUVWAF** [comment]
You can already connect an I2C OLED display (e.g. SSD1306, SH1106) to your Pico using pins 4 (SDA) and 5 (SCL).
