### ISSUE TITLE
[Feature Request]: Support UF2 flashing ESP32-S3 boards

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2898]
### Platform

ESP32

### Description

The Tbeam S3, Tbeam Supreme and Heltec Wireless Tracker all have Adafruit TinyUF2 support which would allow for flashing via mass storage emulation (Drag and Drop). However, there's no littlefs support for this which means there's no persistence when it comes to config changes. I would like to propose we explore a solution to this. 

A previous proposal was for a change from littlefs to fat, however, there were legitimate concerns about the cross-platform consistency of this change. See #1949. Are there any alternative options that we can explore?

**Comment by garethhcoleman** [comment]
Reading the discussion around this issue on the previous pr you referenced, I would offer the opinion that uf2 flashing is a secondary win, the real benefit would be easy file transfer between device and pc. However as this sounds like it depends on fat not littlefs I can't see what could resolve this short of a feature improvement on the uf2 side.

The web flasher provides an easy way to flash devices if that is your main consideration.

**Comment by thebentern** [comment]
I'm going to close this _for now_, since we have working 1200bps reset support in the web flasher and that makes this issue pretty low priority, since the goal was easy flashing.
