### ISSUE TITLE
[Bug]: Ham Parameters Packet is not Working

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2899]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.2.12

### Description

I am sending a valid ham parameters packet from the user config view when a user selects licensed user, but I am never getting an ack back from the device for this admin message and it never reboots.

**Comment by garthvh** [comment]
The first issue was that it was allowing to large a call sign and causing invalid protobuf error.  I have fixed that in the UI and it is sending a valid message, we just need to reboot after the ham parameters message is saved.

**Comment by RicInNewMexico** [comment]
Fixed by #2911
