### ISSUE TITLE
[Bug]: Fix GPS delete when send reset NodeDB

### ISSUE THREAD

**Issue by ozmy** [meshtastic/firmware#2925]
### Category

Other

### Hardware

DIY

### Firmware Version

2.2.12.092e6f24

### Description

When the user sends the reset NodeDB command, the fixed GPS coordinates in the device are deleted.
The problem occurs in many versions

**Comment by thebentern** [comment]
Sadly this is a function of the NodeDB. Position is persistent on the current node in the NodeDB. When you clear it, this information is lost. This isn't an issue we can resolve without a major refactor. 
Perhaps, this is something we can look at solving in 3.0. It's been an annoyance for quite some time.
