### ISSUE TITLE
Online/Offline maps w/ optional SD card storage for T-deck

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2945]

**Comment by garthvh** [comment]
@mverch67 this was in the design repo cross platform project, I converted it to a firmware issue

**Comment by RicInNewMexico** [comment]
Funny, we were just discussing this on the discord yesterday. I didn't even realize an issue had been opened on the topic. 

I came across this which might be useful as a starting point: https://github.com/mryndzionek/esp32_offline_osm/tree/main

I think the most difficult part (from my perspective anyway) will be getting the SD card functioning. I've tried in the past and had issues with the SPI locking.

**Comment by danumbaman** [comment]
perhaps the most valuable feature of the t-deck. would love to see this happen in some form of OSM

**Comment by kovar-ursa** [comment]
I'd like to be able to log position data locally to a TRACKER device. SD card support is clearly a necessary first step.

This YouTube video shows how the problem was solved for a LilyGo device: https://www.youtube.com/watch?v=hLCFNR3jp8Y

**Comment by KyleMaas** [comment]
I would love to see this feature as well.

**Comment by jgauchia** [comment]
Hi, 
I'm working in a project with Offline OSM maps (PNG tiles stored in SD card) as well (under development) vector maps.

[https://github.com/jgauchia/IceNav-v3](url)

My programming skills are fairly simple, and it's a personal hobby project. Perhaps something from it could be useful to you."

**Comment by thebentern** [comment]
This is being tracked in Device-UI effort. Closing
