### ISSUE TITLE
Add ESP32-C3 (Heltec HT62) to Build Jobs

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#2975]
The Heltec HT62 (ESP32-C3) is not included in the build workflows, at least as far as I can tell, which means it's not included in the releases. Currently the only way to flash is via PIO.

**Comment by Fireflaker** [comment]
likely same issue here?
I cannot flash heltec paper or tracker using online flasher. Nothing happens upon clicking flash.
