### ISSUE TITLE
[Bug]:Wireless Tracker v1.0 or v1.1 the GNSS chip is initialized to only recieve GPS & BDS satellites.

### ISSUE THREAD

**Issue by GPSFan** [meshtastic/firmware#2983]
### Category

Other

### Hardware

Heltec Wireless Tracker

### Firmware Version

2.2.15.31c4693

### Description

The protocol spec provided on the Heltec download site is for an older version of the Firebird series. the correct protocol spec is available at:
https://en.unicorecomm.com/products/detail/34
where 1.4.2.5 CFGSYS: Configure Satellite System
describes the much expanded command for the Firebird II chips of which the UC6580 is one.
The initialization code in GPS.cpp is:

       } else if (gnssModel == GNSS_MODEL_UC6850) {

            // use GPS + GLONASS
            _serial_gps->write("$CFGSYS,h15\r\n");
the h15 will init the chip for GPS L1 & L5 and BDS B1I
IMHO it should bi initialized for GPS L1 & L5, BDS B1I & B2a, GLONASS  L1, GALILEO E1 & E5a, and SBAS.
That would make the command _serial_gps->write("$CFGSYS,h25155\r\n");

### Relevant log output

```Shell
N/A
```

**Comment by garthvh** [comment]
Looks like you have everything here to open a PR
