### ISSUE TITLE
[Bug]: Admin Command Not Working on Multi-Hop Nodes

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/firmware#3009]
### Category

Other

### Hardware

Rak4631

### Firmware Version

Multiple up to 2.2.14

### Description

Admin Channel is no longer working on nodes more than one hop away.  My network is a mix of firmware.  I've tried reverted the sending node back to 2.2.9 with no improvements.

Possibly related to https://github.com/meshtastic/Meshtastic-Android/issues/794 ?

**Comment by andrekir** [comment]
@pdxlocations if your results were using the Android app, please try release [2.2.16](https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.2.16)

**Comment by pdxlocations** [comment]
> @pdxlocations if your results were using the Android app, please try release [2.2.16](https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.2.16)

Yup, all fixed.  Thank you @andrekir !
