### ISSUE TITLE
[Bug]: T-Deck `TAB` key mapping missing which is required for secondary channels. 

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#3027]
### Category

Other

### Hardware

T-Deck

### Firmware Version

2.2.16

### Description

#3010 Added the ability to select secondary channels as a destination when using a standalone device. However, these channels do not appear as an option. 

Tested with T-Deck: ** **UPDATE** ** No mapping for tab, which the T-Deck keyboard lacks. 
Start typing text
Swiped left/right with either the trackball or touchscreen to scroll through destinations.
No secondary channel appears, only primary and known peers. 

Tested with RAK4631 (Meshenger w/ CardKB):**  **UPDATE** ** This was a user error. Tab has to be pressed twice in order to cycle through secondary channels. 

Expected outcome would be for secondary channels to appear as a selectable destination when sending a message.

**Comment by mverch67** [comment]
I suggest to use a gesture (e.g. swipe up) for implementation, so that it'll also work for T-Watch as well.

**Comment by garthvh** [comment]
Is this fixed now?

**Comment by fifieldt** [comment]
#3668 was merged - should this be closed?
