### ISSUE TITLE
[Feature Request]: M5Cardputer Meshtastic client

### ISSUE THREAD

**Issue by aat440hz** [meshtastic/firmware#3037]
### Platform

ESP32

### Description

I know I will probably get laughed at and berated by the meshtastic community for suggesting this, but here it goes... It would be really cool to see a meshtastic client for the m5cardputer that connects to your meshtastic device via bluetooth and allows you to send and receive messages etc.

**Comment by garthvh** [comment]
You should be able to plug in the cardkb and have a stand alone client already
