### ISSUE TITLE
[Board]: wireless-stick-v3

### ISSUE THREAD

**Issue by Quency-D** [meshtastic/firmware#3039]
### SOC

ESP32

### Lora IC

SX1262

### Product Link

https://heltec.org/project/wireless-stick-v3/

### Description

Due to the heavy workload of UI development, the screen is temporarily not displayed.

**Comment by garthvh** [comment]
The screen is too small for meshtastic, not on the roadmap, you are welcome to give it a try.

**Comment by thebentern** [comment]
The rest of the board should work with the existing WSL target.
