### ISSUE TITLE
JSON not unique enough when using Detection Sensor[Feature Request]: 

### ISSUE THREAD

**Issue by galvheim** [meshtastic/firmware#3042]
### Platform

ESP32

### Description

Hi,

When triggering switch of Detection Sensor, the JSON-string that is produced is not unique enough to be read out. At least there should be a usable Type-description, but there is just "" with nothing inside. It should come out in a more usable form with maybe the Friendly Name in JSON or at the very least "detection" in the Type.

Regards
Gunnar..

**Comment by GUVWAF** [comment]
Implemented with #3043.
