### ISSUE TITLE
[Bug]: T-Echo changing any position settings results in "no GPS device"

### ISSUE THREAD

**Issue by rolf-tx** [meshtastic/firmware#3059]
### Category

Hardware Compatibility, Other

### Hardware

T-Echo

### Firmware Version

2.2.17

### Description

For T-Echo changing any parameter in the Position settings tab results in the GPS not being detected "no GPS device".
Changing the GPS pin definitions from Unset to 41, 40, 37 seems to get the device detected some of the time but unable to get satellite lock.  
Doing a  Device-Factory Reset seems to be the only think that makes it acquire satellites again (instant lock)

**Comment by Mictronics** [comment]
I can't confirm. I have 4 T-Echo with the actual master branch code running, including changes from 2.2.17. All device get the GPS module detected and having a position lock within a few minutes. Changing GPS setting do not have any other effect than the expected change. And I experiment a lot here at the moment.

**Comment by Mictronics** [comment]
Tried also the pre-compiled 2.2.17 on one Echo device. GPS position acquired in less than 2 min on the window sill.

**Comment by rolf-tx** [comment]
@Mictronics
Thanks for checking.
I’m using the iOS app, are you using iOS or android?

**Comment by Mictronics** [comment]
Android.

**Comment by thebentern** [comment]
Can you post a meshtastic --info dump of your position config after saving on the iOS app? That would help us pin down what's getting unset

**Comment by rolf-tx** [comment]
@thebentern 
I have attached a bad and a good info dump and start log. 
Note that sometimes I had to do a physical hard reset of the device to trigger "no GPS" after setting Timestamp=on, the soft reset still had the GPS functioning.

[info-2.2.17.bad.txt](https://github.com/meshtastic/firmware/files/13850357/info-2.2.17.bad.txt)
[info-2.2.17.ok.txt](https://github.com/meshtastic/firmware/files/13850359/info-2.2.17.ok.txt)
[log.2.2.17.bad.txt](https://github.com/meshtastic/firmware/files/13850535/log.2.2.17.bad.txt)
[log.2.2.17.ok.txt](https://github.com/meshtastic/firmware/files/13850536/log.2.2.17.ok.txt)

**Comment by Mictronics** [comment]
The bad config is missing:
```
"gpsUpdateInterval": 120,
"gpsAttemptTime": 900,
```
I can reproduce this bug when I set in Android app the `GPS Update Interval`and `Fix attempt duration` manually to zero (0). The Echo then shows "No GPS Module".

**Comment by rolf-tx** [comment]
@Mictronics Thanks for the quick fix. I built it and it fixed the issue.

**Comment by Mictronics** [comment]
@rolf-tx I hope you don't build my branches. These are modified on special purpose for personal use.

**Comment by rolf-tx** [comment]
@Mictronics No, not normally, just for this case. 

Any idea when the changes will be merged in bleeding?

**Comment by Mictronics** [comment]
There is work in progress, see PR #3064
