### ISSUE TITLE
[Bug]:  Web interface can not disable telemetry power screen

### ISSUE THREAD

**Issue by LanWolf** [meshtastic/firmware#3068]
### Category

Category
Other

Hardware
LILYGO TTGO T3S3

Firmware Version
2.2.17

### Description

After enabeling telemetry power screen with meshtastic  web interface, it can not be disabled in web interface.
i set it to true in the web interface and the screen was enabled on my device 
When setting false in the webinterface the screen would not disable .
the cli command
`meshtastic -- set telemetry.powerScreenEnabled false` 
dit work and disabled the powerscreen.

`Module preferences: { "mqtt": { "address": "mqtt.meshtastic.org", "username": "meshdev", "password": "large4cats", "encryptionEnabled": true, "root": "msh" }, "serial": {}, "externalNotification": {}, "rangeTest": {}, "telemetry": { "deviceUpdateInterval": 900, "environmentUpdateInterval": 900, "environmentMeasurementEnabled": true, "environmentScreenEnabled": true, "airQualityInterval": 900, "powerUpdateInterval": 9000, "powerScreenEnabled": true }, "cannedMessage": { "enabled": true, "allowInputSource": "cardkb" }, "audio": {}, "remoteHardware": {}, "neighborInfo": { "updateInterval": 900 }, "ambientLighting": { "ledState": true, "current": 10, "red": 223, "green": 215, "blue": 12 }, "detectionSensor": { "minimumBroadcastSecs": 45, "detectionTriggeredHigh": true } }
`

**Comment by thebentern** [comment]
The interface was never created. That is a configuration in the protobufs that was added recently and has not been wired up to anything.
