### ISSUE TITLE
[Bug]: GPS Latitude value randomly inverts

### ISSUE THREAD

**Issue by kingoffoxes** [meshtastic/firmware#3076]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.2.16.1c6acfd

### Description

Occasionally the reported node GPS position looses the negative in front. 
ie. -40.0000 becomes 40.0000 which shows on the map as a position on the other side of the planet. 
using Apple app to view map. Compared on the local app and another node reporting the DUT nodes position on its map.

**Comment by KodinLanewave** [comment]
I've seen similar issues but instead of just losing the negative, I lose the entire value of latitude and it goes to zero, as shown here from my Owntracks history for one of my nodes:
![image](https://github.com/meshtastic/firmware/assets/168792/389ee95e-55e7-4ab5-8813-a12030bf2d00)

**Comment by jp-bennett** [comment]
This looks familiar. @KodinLanewave , what hardware is this? 
@kingoffoxes, do you know which revision of the t-beam you have?

**Comment by kingoffoxes** [comment]
> This looks familiar. @KodinLanewave , what hardware is this? @kingoffoxes, do you know which revision of the t-beam you have?

T-Beam is a T-22_v1.1 20210222 (SX1262) with GPS u-blox NEO-M8N-0-10

**Comment by KodinLanewave** [comment]
I'm using a RAK with the M8N GPS module.

**Comment by madeofstown** [comment]
I see this on my Heltec V3 and Pi Pico W using my phones GPS as well as on my Raspberry Pi 4 (Linux native device) with a LoRA/GNSS Hat.
