### ISSUE TITLE
Location Ambiguity

### ISSUE THREAD

**Issue by Ferretdog** [meshtastic/firmware#3092]
Coming from using APRS in the ham radio world, I often enable Position Ambiguity which rounds off the last x digits of my lat/long. This gives people a rough idea where I am, but not an exact location, which is sufficient for many purposes. I might be happy to have people know roughly where I live without knowing the exact house, or knowing what town I'm in, but not much more than that. 

- I suggest a position ambiguity be added to the location settings, with a user selectable choice of digits of the decimal lat\long from 0 to 5 (or more), eg. x., x.y, x.yy, x.yyy, etc.

For example a decimal lat/long to 4 or more decimal places locates a specific house. [-37.8929, 145.1524](https://www.google.com/maps/place/37%C2%B053'34.4%22S+145%C2%B009'08.6%22E/@-37.8928979,145.1511125,18z/data=!4m4!3m3!8m2!3d-37.8929!4d145.1524?entry=ttu) 

But if I drop it back to [3 decimal places](https://www.google.com/maps/place/37%C2%B053'31.2%22S+145%C2%B009'07.2%22E/@-37.8919979,145.1507125,18z/data=!3m1!4b1!4m4!3m3!8m2!3d-37.892!4d145.152?entry=ttu) I'm still pretty close without disclosing which house I'm in, [2 places is quite adequate](https://www.google.com/maps/place/37%C2%B053'24.0%22S+145%C2%B009'00.0%22E/@-37.8899957,145.1474251,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-37.89!4d145.15?entry=ttu) or even [1 place](https://www.google.com/maps/place/37%C2%B048'00.0%22S+145%C2%B006'00.0%22E/@-37.7940619,145.0664402,13.23z/data=!4m4!3m3!8m2!3d-37.8!4d145.1?entry=ttu) is plenty for what part of town or what suburb you're in which is often enough on a shared channel.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/adjustable-gps-precision-for-privacy/9513/3

**Comment by jp-bennett** [comment]
I've started work on this. Currently using a binary bitmask, so we just set the bits of precision.

**Comment by jp-bennett** [comment]
PRthis feature is at https://github.com/meshtastic/firmware/pull/3248, and support in the Python app is at https://github.com/meshtastic/python/pull/487 If anyone is interested in these features, and wants to test, I'd be very interested to hear how that goes.
Full precision for a channel is 32, and at 0 location data is fully disabled for the given channel.

**Comment by dougle03** [comment]
Will we see this in the web and Android app? - Perhaps for security purposes ambiguity over position should be the default with the option to increase accuracy.

**Comment by jp-bennett** [comment]
@dougle03 It's already in the iOS and Android app source code, and will roll out with the next release of both. It's not in the web app yet, but I expect that to happen before too long.

**Comment by Firworksyt** [comment]
Is this only for cellular device GPS forwarding or also for the hardware GPS on a node? I'm hoping it's for both so we can anonymize a little bit but still show the general location.
