### ISSUE TITLE
[Bug]: Whacky date entries in Device Metrics Log

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/firmware#3103]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.1.23.04bbdc6

### Description

The first entry in the Device Metrics Log is almost always UNKNOWN TIME and sometimes the dates are wacky (1969 and 2009) as shown in the attached screenshot.

![IMG_6205](https://github.com/meshtastic/firmware/assets/121647809/d008106b-8d91-4240-ac12-1d90b77cd0d0)

**Comment by garthvh** [comment]
Those times come from your device. I would update the firmware, there have been several time fixes since 2.1.23

**Comment by garthvh** [comment]
The first entry will usually have an empty time after boot as it has no time from the GPS.
