### ISSUE TITLE
 [Feature Request]: Stop charging under freezing temperatures

### ISSUE THREAD

**Issue by yo3hjv** [meshtastic/firmware#3107]
### Platform

NRF52, ESP32

### Description

A problem encountered in practice: when installing a node in an outdoor location with no electricity grid, power is supplied by a lithium battery cell and charging by a solar panel. It is known that at temperatures below freezing (0 degrees Celsius, 32 degrees Fahrenheit) the battery can deliver energy but charging can degrade it irreversibly.
Therefore, an algorithm to stop charging when the temperature drops below this threshold (possibly a degree or two above) would be welcome, even necessary.
The T-Beam boards whose charging circuit is APX193 do not have a built-in NTC to measure the battery temperature (but the circuit itself) but a practical solution would be to base this algorithm on the temperature measured by the external BME280 or BMP280 circuit which is already implemented in the firmware.
Thus, based on the temperature measured by the detector, a load stop threshold below 0 C/32F could be implemented as a failsafe measure. In the setting app (Android, iPhone) a higher value for charge prevention (e.g. 5C/35F) can be set by the user.
This issue is derived from the practical experience of testing the operation of such a node based on TBeam V1.1 to be installed in an outdoor location, at high altitude and in an environment with temperatures that may drop below freezing, to increase the coverage distance.

**Comment by thebentern** [comment]
This isn't exactly a universal truth depending on cell chemistry and quality. The figure for damaging cells is generally much lower than 32 degrees F. This seems like something better served for a custom build in a fork rather than the mainline firmware.
