### ISSUE TITLE
[Bug]: No BT connectivity when WIFI enabled 

### ISSUE THREAD

**Issue by milkpirate** [meshtastic/firmware#3140]
### Category

BLE

### Hardware

Heltec V3

### Firmware Version

v2.2.17.dbac2b1

### Description

As soon as I enable WIFI at one of the nodes, it is not reachable anymore via Bluetooth.

Is that desired behavior?

### Relevant log output

```Shell
N/A
```

**Comment by garthvh** [comment]
You can't use BLE and WiFi at the same time, they use the same antenna.
