### ISSUE TITLE
[Bug]: I can't activate GPS

### ISSUE THREAD

**Issue by Ronda-00** [meshtastic/firmware#3173]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.2.21.7

### Description

I activate the option within position
 and when restarting the t-beam
  the GPS is deactivated again. thanks

**Comment by jp-bennett** [comment]
This is probably due to a change to firmware, that the mobile clients are still rolling out.

**Comment by Ronda-00** [comment]
I have installed firmware 2.2.20 and the GPS works perfectly

**Comment by BrunoKlu** [comment]
Have same issue with all my nodes on 2.21 will try with android app but same issue on Ios and web client

**Comment by mverch67** [comment]
Until the mobile clients have implemented the new gpsMode you could use the CLI to activate the GPS.
`meshtastic --set gps_mode ENABLED`

**Comment by jp-bennett** [comment]
> Until the mobile clients have implemented the new gpsMode you could use the CLI to activate the GPS.
> `meshtastic --set position.gps_mode ENABLED`

Unfortunately pip seems to be only offering 2.20 at this time.

**Comment by mverch67** [comment]
In the meantime GPS_mode is supported by CLI, Android and Apple app... can you re-test and close this report if everything works?
