### ISSUE TITLE
[Feature Request]: Rangetest change.

### ISSUE THREAD

**Issue by rikianeiros** [meshtastic/firmware#3182]
### Platform

ESP32

### Description

I am trying to add a row in the .csv that gives the RSSI on the range test. I have tried it an it is very easy.

**Comment by rikianeiros** [comment]
fileToAppend.printf("%d,", mp.rx_rssi); // RX RSSI
    Is just adding this.

**Comment by andrekir** [comment]
Duplicate of #2372
