### ISSUE TITLE
[Bug]: client.meshtastic.org wifi connection to local IP no longer works

### ISSUE THREAD

**Issue by pfeiffee** [meshtastic/firmware#3203]
### Category

WiFi

### Hardware

Heltec V3

### Firmware Version

2.2.22.404d0dd

### Description

client.meshtastic.org wifi connection to local IP no longer works in any scenario I could find, yielding of SSL_accept failed in log.

**Comment by caveman99** [comment]
you need to add a new ssl exception for your device every time you factory reset it. See https://meshtastic.org/docs/software/web-client/#http for an explanation
