### ISSUE TITLE
[Bug]: Gps light flashes when fixed location is set

### ISSUE THREAD

**Issue by weirdal3333** [meshtastic/firmware#3205]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.2.21

### Description

Gps light flashes (meaning the module is enabled) when a fixed location is set, regardless of gps toggle/smart location settings.

Proposed solution: turn off gps module when fixed location is set

**Comment by thebentern** [comment]
Fixed position does not disable GPS. GPS mode toggling does this. Try triple-clicking the user button to disable the GPS. The status screen will show whether it is turned off or not
