### ISSUE TITLE
[Board]: PJRC Teensy4.1

### ISSUE THREAD

**Issue by catchra** [meshtastic/firmware#3221]
### SOC

Other

### Lora IC

N/A

### Product Link

https://www.pjrc.com/store/teensy41.html

### Description

Although this board doesn't have wifi/bt or any lora radio on it
it is a very powerful mcu with ethernet and usb host capability 

This addition would open up new possibilities for users interested in leveraging the unique capabilities of the Teensy 4.1
for mesh networking within the meshtastic ecosystem

![](https://www.pjrc.com/store/teensy41_card11a_rev3.png)
![](https://www.pjrc.com/store/teensy41_card11b_rev4.png)

Specifications
    ARM Cortex-M7 at 600 MHz
    Float point math unit, 64 & 32 bits
    7936K Flash, 1024K RAM (512K tightly coupled), 4K EEPROM (emulated)
    QSPI memory expansion, locations for 2 extra RAM or Flash chips
    USB device 480 Mbit/sec & USB host 480 Mbit/sec
    55 digital input/output pins, 35 PWM output pins
    18 analog input pins
    8 serial, 3 SPI, 3 I2C ports
    2 I2S/TDM and 1 S/PDIF digital audio port
    3 CAN Bus (1 with CAN FD)
    1 SDIO (4 bit) native SD Card port
    Ethernet 10/100 Mbit with [DP83825 PHY](http://www.ti.com/product/DP83825I)
    32 general purpose DMA channels
    Cryptographic Acceleration & Random Number Generator
    RTC for date/time
    Programmable FlexIO
    Pixel Processing Pipeline
    Peripheral cross triggering
    Power On/Off management

**Comment by thebentern** [comment]
Manuel is correct. As compelling as the hardware for this board is, there is no off the shelf lora supported variants and the Milk-V Duo boards are capable alternatives in the MeshtasticD linux support.
