### ISSUE TITLE
[Feature Request]: Add password protection for node access

### ISSUE THREAD

**Issue by mattdrum** [meshtastic/firmware#3222]
### Platform

NRF52, ESP32

### Description

I have been considering security vunerabilities related to my mesh network. I know that a BLE pin is possible for nodes but I don't believe that is sufficient to prevent unauthorized access to messages and settings. 

I would like for the option to be added to add a password to login to the node both on the android, IOS, and web client to prevent unauthorized access.

**Comment by thebentern** [comment]
This is not feasible in the current infrastructure

**Comment by darkfiberiru** [comment]
> This is not feasible in the current infrastructure

Why is this not feasible?
