### ISSUE TITLE
[Feature Request]: Short Name aka short_name shoud be 7 or 8 chars long for Amateur Radio mode

### ISSUE THREAD

**Issue by DE8MSH** [meshtastic/firmware#3231]
### Platform

ESP32

### Description

Hello. 

Thank you very much for your hard work. What I found out: The Short Name aka short_name is generated from letters and mac address numbers -- changable I know. In amateur radio mode we need another notation. Stations in amateur radio mode are called DO7OO-7 for eg. Here in Germany BNetzA don't like station names like D234 for example in amateur radio. They like names like DO7OO-7 -- like used in APRS. Can we have longer short_name(s)? I saw short_name is char short_name[6] But APP alows 4 chars only. It should be char short_name[8] and APP should be allowed to enter DO7OO-7 for eg.

Thank you very much for having a look at it. 

de DO7OO

**Comment by garthvh** [comment]
Name is what is used for call sign , not the shortname
