### ISSUE TITLE
Make Store and Forward module storage abstraction for flash / SD card 

### ISSUE THREAD

**Issue by LanWolf** [meshtastic/firmware#3234]
### Platform

NRF52

### Description

Is the RAK15001 board a suitable solution for store and foward with rak modules  ? 

https://store.rakwireless.com/products/wisblock-flash-module-rak15001

**Comment by jp-bennett** [comment]
I think the game plan is to modularize the S&F backend to support more devices and storage types.

**Comment by attermann** [comment]
@thebentern Not sure an old closed issue is the best place to restart this discussion, but I have just such a storage abstraction that I built for a similar project that I'd love to see utilized in Meshtastic firmware to enable support for external FLASH/FRAM storage. I'm happy to do the integration, just want to be sure that maintainers are open to accepting it.
