### ISSUE TITLE
[Bug]: Messages not sending when MQTT is enabled

### ISSUE THREAD

**Issue by habr05** [meshtastic/firmware#3237]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.2.21.7f7c5cb

### Description

With Wi-Fi and MQTT enabled, messages do not send - receiving works. Disabling MQTT "fixes" sending. 
Version 2.2.19.8f6a283 has the same issue.
Version 2.2.17.dbac2b1 does not have this problem.

**Comment by GUVWAF** [comment]
There was another fix for this in the alpha firmware release 2.2.22. Please try that version.
