### ISSUE TITLE
[Board]: Flipper Zero with LoRa GPIO connection.

### ISSUE THREAD

**Issue by Mariner10** [meshtastic/firmware#3250]
### SOC

Other

### Lora IC

Not included.

### Product Link

https://flipperzero.one/

### Description

With the flipper zero being an all in one kind of device, it could really benefit from the added LoRa addition to it. all that would be required is the GPIO LoRa module to be plugged into the top. It could communicate with your app over bluetooth, and it already has a built in screen and control interfaces for ease of use! By supporting this product, you will also be moving into a buzzing community that will most likely latch onto your ideology and help out making nodes all around the world.

**Comment by thebentern** [comment]
This would need to be an effort on the Flipper Zero firmware, not Meshtastic firmware
