### ISSUE TITLE
[Feature Request]: making meshtastic.local changeable

### ISSUE THREAD

**Issue by AssetBurned** [meshtastic/firmware#3252]
### Platform

NRF52, ESP32

### Description

Having multiple nodes in your own WiFi makes it a bit problematic when all of them listen to meshtastic.local.

Having an easy way to change that via web interface would be great.

**Comment by thebentern** [comment]
This is used for service discovery in the clients. You will need to use IPs instead of the name.

**Comment by AssetBurned** [comment]
oh... ok so this is then actually a bug. https://github.com/meshtastic/firmware/issues/3305
