### ISSUE TITLE
Meta: E-Ink Terminology - Seeking Opinions

### ISSUE THREAD

**Issue by todd-herbert** [meshtastic/firmware#3261]
I'm hoping to get some opinion on the terminology we use to discuss E-Ink displays here.

To summarize the situation, for anyone not particularly familiar:

E-Ink displays can often have different styles of "update operation", used to draw images.
The terms used are usually something like:
* Full Refresh
* Partial Refresh

A full refresh is considered the default operation. The display flashes several times, to fully adjust the pigment for the new pixels.
An update which moves the pixels quickly and subtly, without flashing, is often referred to as a "partial refresh"

___

I have recently noticed that some display manufacturers are more precise with their language, acknowledging three distinct operations:

- Full Refresh - fullscreen image transferred to display, slow blinking update
- Fast Refresh - fullscreen image transferred to display, fast update
- Partial Update - small region transferred to display, fast update

Although I have shied away away from the term "partial refresh" in my own work, I know I have been guilty of using the terms "partial refresh" and "fast refresh" interchangeably.

Strictly speaking, the way we been working here with E-Ink displays might more accurately be described as "Fast Refresh", than "Partial Update".

In order for me to move forward with confidence,  I want to ask:
**Would you prefer code to use the term "fast refresh"?**
**Would you prefer to continue with the terms "partial refresh" / "partial update"?**

**Comment by markbirss** [comment]
@todd-herbert I asked for Discord channel long time ago for in particular e-ink displays
