### ISSUE TITLE
[Feature Request]: Allow longer short name (4 characters isn't very useful)

### ISSUE THREAD

**Issue by robbietee** [meshtastic/firmware#3267]
### Platform

NRF52, ESP32

### Description

Allow longer than 4 characters in short name. The short name would be much more useful if more characters were allowed.
I know there is already a long name field that can be used but i'm specifically talking about the short name. Many users are using the long name as a "status" field so allowing the short name to be longer could be used to set a fixed station or node name.

**Comment by caveman99** [comment]
Please don't open feature requests that were just closed with a valid reason.

From The Protobuf comments: `A VERY short name, ideally two characters.` - So 4 is aready doube that size. The Shortname is used for identificaton on very small screens, please use the long name for anything else.
