### ISSUE TITLE
[Feature Request]: Detection Sensor Message Channel Setting

### ISSUE THREAD

**Issue by tomfarnham** [meshtastic/firmware#3275]
### Platform

NRF52, ESP32

### Description

Detection Sensor messages appear to transmit by default on Channel 0. A feature to set the transmit channel would allow separate management for connections to MQTT. Specifically, maintaining the default LongFast channel for network propagation, but relegating sensor information to separately secured channels. This would feature would ideally still default to Channel 0 for transmission to maintain backwards compatibility, but be overrided by an additional setting for more flexibility.

**Comment by sendingstrings** [comment]
> This is beyond the current intended scope of the detection sensor module. Perhaps we'll consider it for 3.0. This would fall under the scope of: [#3207](https://github.com/meshtastic/firmware/issues/3207)

How is this part of [Feature Request]: Spread telemetry/GPS updates across channels #3207?
