### ISSUE TITLE
Move duplicate font definition code to common header file (tech dept)

### ISSUE THREAD

**Issue by thoherr** [meshtastic/firmware#3301]
While implementing feature request #3284 i recognised that the definition of screen fonts is duplicated in several files, namely
src/graphics/Screen.cpp, src/modules/Telemetry/PowerTelemetry.cpp, src/modules/Telemetry/EnvironmentTelemetry.cpp, src/modules/CannedMessageModule.cpp.
To avoid breaking something, i even introduced another copy in src/modules/esp32/PaxcounterModule.cpp to implement the feature.

I propose to cleanup the duplicate code by moving it to a separate header file and indlude this in the files named above.

**Comment by thebentern** [comment]
Closed with #3302
