### ISSUE TITLE
[Feature Request]: Turn of start sound in settings

### ISSUE THREAD

**Issue by stl1988** [meshtastic/firmware#3309]
### Platform

ESP32

### Description

I'm using an M5Stack device with Meshtastic. Sometimes it reboots suddenly ant the start sound is very loud. Can you build in the possibility to turn off this sound entirely?

**Comment by garthvh** [comment]
It is on by default but you should be able to turn it off, is it playing the 24 beep sound?

**Comment by stl1988** [comment]
What is the 24 beep sound?
