### ISSUE TITLE
[Feature Request]: deleting waypoints without needing to reflash

### ISSUE THREAD

**Issue by kmg0026** [meshtastic/firmware#3324]
### Platform

ESP32

### Description

Add the feature of deleting last heard waypoints in the app without needing to reflash the hardware.  Currently, the last heard waypoint shows on the screen every time a message is sent.  It seems the only way to remove this is to flash the board to clear it.

**Comment by kmg0026** [comment]
![IMG_1427](https://github.com/meshtastic/firmware/assets/64663947/c92f17fc-932c-42cc-8547-dbf1681fe7c8)

photo of the Heltec v3 screen every time I send a message.

**Comment by caveman99** [comment]
This screen always shows the last received message. you can indeed only clear it with a reflash. No way round this atm.
