### ISSUE TITLE
[Feature Request]: Switch between device GPS and phone GPS

### ISSUE THREAD

**Issue by BjornB2** [meshtastic/firmware#3332]
### Platform

ESP32

### Description

I have a Heltec V3 with external GPS that is powered via a diode so I can enable/disable it by pressing the menu button 3 times. If I disable the device GPS, the Heltec keeps transmitting the last known location, even though "fixed" is off in the settings and my phone is sharing it's location. 

It would be nice to have multiple options:

1. Disable GPS and stop transmitting location info - Handy for privacy reasons
2. Disable GPS and keep transmitting last location - Handy when staying at the same location for a while
3. Disable GPS and start transmitting phone location - Handy for power saving when connected.

Or an in app setting to disable device GPS automatically and switch to phone GPS when phone is connected.

**Comment by Danie10** [comment]
I enable my phone GPS only when leaving home, as my Heltec V3 device defaults to Fixed location and Smart location both on. I notice though it seems to update the fixed location when phone GPS sharing is on. So when I later disable phone GPS when home, it stays on that last updated fixed location. It should actually keep the fixed location as originally saved.

Mentioning her as related to same topic/fix being suggested.

The new alpha version though does seem to be addressing the privacy aspect where it adjusts the accuracy of the location to low or medium accuracy.
