### ISSUE TITLE
[Feature Request]: use callback of libpax for PaxcounterModule

### ISSUE THREAD

**Issue by thoherr** [meshtastic/firmware#3342]
### Platform

ESP32

### Description

The PaxcounterModule currently polls data from [libpax](https://github.com/dbinfrago/libpax) and sends it to the mesh (with configurable update interval). The underlying library is therefore initialized with countermode 1, which means that it continuously counts BLE and WiFi devices since start of the node, without ever resetting the data. Depending on the location and the uptime of the node, this accumulated count after a while looses its semantics.

Taking the standalone [PAXcounter Firmware](https://github.com/cyberman54/ESP32-Paxcounter) as blueprint, the idea there is to have counting intervals for the devices, after which the data is sent to a callback function and the values are reset to 0 (which allows to have time series of counts).

I therefore suggest to use the callback and the pax_report_interval_sec of the libpax library to implement the PaxcounterModule and set the countermode to another value, in order to have a time sliced count. This behaviour (countermode) may also be made configureable for the PaxcounterModule, which would be another (easy to implement) feature.

I already implemented the necessary changes and tested them successfully on my TTGO LoRa32 V2.1_1.6.

What do you thing about this change, @caveman99 ?

**Comment by caveman99** [comment]
This sounds like a sensible approach, can you make a PR i can review?
