### ISSUE TITLE
[Bug]: Duplicate messages received hours after original.

### ISSUE THREAD

**Issue by kghunt** [meshtastic/firmware#3364]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.2.23.5672e68

### Description

Messages show as received which a duplicates of actual earlier messages. These messages do not show as sent on the sender side.

**Comment by kghunt** [comment]
This happens on both android and iOS. Almost like the the device has buffered the messages and later sends them again. I think I have seen a pattern where it is when your phone disconnected then reconnect to the node.

**Comment by caveman99** [comment]
Please check if 2.2.24 exhibits this as well.
