### ISSUE TITLE
[Feature Request]: XPT2046 TouchScreen support

### ISSUE THREAD

**Issue by kpbicka** [meshtastic/firmware#3367]
### Platform

ESP32

### Description

I just successfully launched ILI9341 display. But unfortunately, it’s not possible to initialize the touchscreen. There is a single mention of [XPT2046](https://ldm-systems.ru/f/doc/catalog/HY-TFT-2,8/XPT2046.pdf) in the code, but I cannot understand which platform it refers to. I think the TouchScreenBase.cpp only works with capacitive screens, because the resistive panel with XPT2046 controller requires initial calibration
![IMAGE 2024-03-10 20:59:16](https://github.com/meshtastic/firmware/assets/43946570/d992d95e-6d62-426f-b8d1-e20c5ec05f4f)
Anyone use touchscreens?

**Comment by thebentern** [comment]
The display is support, but unfortunately resistive touch panels are a pain to work with. Not really on our list to tackle considering all of the other market options available with capacitive touch.
