### ISSUE TITLE
[Feature Request]: use Priority BACKGROUND for low priority messages; MIN should not be used

### ISSUE THREAD

**Issue by thoherr** [meshtastic/firmware#3380]
### Platform

NRF52, ESP32

### Description

As @caveman99 commented [here](https://github.com/meshtastic/firmware/pull/3351#discussion_r1518839152), it would be approriate for all low priority messages to use the priority BACKGROUND. The priority MIN should just be the minimal priority available, but actually never used (same applies to priority MAX).
This would apply to several modules (eg. several Telemetry modules, StoreForward, Paxcounter)

**Comment by caveman99** [comment]
This will be in next release
