### ISSUE TITLE
[Bug]: mapTopic mqtt path is built incorrectly

### ISSUE THREAD

**Issue by AeroXuk** [meshtastic/firmware#3382]
When building the `mapTopic` variable with a mqtt root set, it appends the `jsonTopic` variable instead of the `mapTopic` variable resulting in incorrect mqtt path.

https://github.com/meshtastic/firmware/blob/5f47ca1f32dd283739c4d78a4e08f20a9bd60fa1/src/mqtt/MQTT.cpp#L188

Example console output:
```
INFO | 02:00:33 900 [mqtt] MQTT Publish map report to msh/EU_868msh/EU_868/2/json/
```

Expected console output:
```
INFO | 02:00:33 900 [mqtt] MQTT Publish map report to msh/EU_868/2/map/
```

**Comment by garthvh** [comment]
This is a lightweight way to connect to web maps.
