### ISSUE TITLE
[Bug]: Make sure Locations are only sent on update, if Fixed Position is not enabled

### ISSUE THREAD

**Issue by jp-bennett** [meshtastic/firmware#3401]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.2.24

### Description

As per Discord GNSS discussion

**Comment by jp-bennett** [comment]
This is unconfirmed, but making a note here as a reminder to revisit.

**Comment by fifieldt** [comment]
@jp-bennett - still want to keep this one open?

**Comment by jp-bennett** [comment]
@fifieldt Thanks for the ping. There's been refactoring since this. I need to look into it again.

**Comment by fifieldt** [comment]
I went back and read the original discord comments from March. This doesn't seem to be a thing.
