### ISSUE TITLE
[Bug]: Router mode issues with new deep sleep default

### ISSUE THREAD

**Issue by bmunger** [meshtastic/firmware#3402]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.2.24.e6a2c06

### Description

This applies to version 2.3.0 as well.
The device is in ROUTER mode.

Since pull request https://github.com/meshtastic/firmware/pull/3251 was merged, it appears that the Heltec board loses a lot of lora packets.  It often takes up to 4 trace routes for it to respond.  This doesn't happen in version 2.2.23.  I don't know if this affects any other device, since I don't have any other models to test with.  Reverting to 2.2.23 restores expected behavior.

As a side note, it might be better to make deep sleep an option.  There are situations where power usage is not a concern.

**Comment by andrekir** [comment]
we're tracking this in #3391, please add any additional details or follow the progress there.
