### ISSUE TITLE
[Feature Request]: Better Validation around Changes to the Primary channel

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#3407]
### Platform

NRF52, ESP32

### Description

Don't allow changes to the role or index of the primary channel.

**Comment by jp-bennett** [comment]
It's been found that the web client can set a non-0 index channel to be primary, and the firmware gets very grumpy at this.

**Comment by thebentern** [comment]
Boooo!

**Comment by fifieldt** [comment]
Fixed in Web:

https://github.com/meshtastic/web/pull/300
