### ISSUE TITLE
Remove channel disambiguation suffix 

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#3428]
https://github.com/meshtastic/firmware/blob/13cc1b0252b5fdae9a195412039ea46b0288d634/src/mesh/Channels.h#L65

The channel disambiguation suffix is no longer necessary as all clients now have a channel editor available, allowing users to easily modify and manage channels. With this functionality in place, the additional suffix becomes redundant and can lead to confusion -- especially since it's not universally adopted by all clients. As a result, it is my recommendation to remove this feature to streamline the user experience.

**Comment by garthvh** [comment]
I like this plan!

**Comment by thebentern** [comment]
I completely agree. If @sachaw @andrekir are on board, I'm for removing this point of confusion.

**Comment by sachaw** [comment]
Axe it

**Comment by andrekir** [comment]
sure
