### ISSUE TITLE
[Bug]: Traceroutes fail, most of the time, to register on the app with fw 2.3.0... 2.2.24 traceroutes show up on the android app.

### ISSUE THREAD

**Issue by eldoctorcool** [meshtastic/firmware#3429]
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.3.0

### Description

Traceroutes don't register on the Android app. They work with fw 2.2.24. but not with 2.3.0

**Comment by eldoctorcool** [comment]
Android app is 2.2.24.

**Comment by eldoctorcool** [comment]
Well, I've managed to get a Traceroute to pop up after trying 18 times... this never happened before.

**Comment by eldoctorcool** [comment]
I am able to traceroute from a 2.3.0 node to any of my 2.2.24 fw nodes just fine, but if I try anything that has fw 2.3.0 from a 2.3.0 node it simply won't show a traceroute.

**Comment by eldoctorcool** [comment]
Repro steps: 
-Need 3 nodes and Android version 2.2.24.
-Install 2.3.0 on two nodes.
-Install 2.2.24 on one node.
-From the 2.3.0 node send a Traceroute to the 2.2.24. You'll see the Traceroute register.
-From the 2.3.0 node send a Traceroute to the 2.3.0 node, Traceroutes won't register at all on the app.

**Comment by GUVWAF** [comment]
Maybe this is related to https://github.com/meshtastic/Meshtastic-Android/issues/916, but I am unable to reproduce. Traceroutes work for me with a node using firmware 2.2.24 and another 2.3.0, and also between two 2.3.0 nodes.

**Comment by eldoctorcool** [comment]
The interesting detail I noticed is that the node that was pinged goes to the top of the node list, like when packet comes from the mesh... but it doesn't acknowledge it as a Traceroute on the app... so, maybe this is an app issue? Packet garbled could be? Maybe we could test the hop count not changed as suggested on the other bug?

**Comment by GiuStel** [comment]
Here with android app and fw on 2.3.x , doensn't matter the patch version, traceroutes always show up, but always show 1 hop only: the target node.

**Comment by GUVWAF** [comment]
Let's continue this in #3452.
