### ISSUE TITLE
[Feature Request]: "Who can see me" broadcast?

### ISSUE THREAD

**Issue by Slyke** [meshtastic/firmware#3431]
### Platform

ESP32

### Description

Was thinking about this for finding the optimal position to place a new node. It's basically a feature that makes your node send out a broadcast, asking "Who can see me?" And everyone who can, replies with their ID, how well they received the signal, and their location (if available), plus any other relevant info. This should be optionally (dis/en)abled by repliers, and there should be configurable rate limiting from the replying ends.

This broadcast should not be forwarded or rebroadcasted. Other nodes should only reply if they are of the role:
* Client
* Client Mute
* Router
* Router_Client

**Comment by garthvh** [comment]
This already happens

**Comment by Slyke** [comment]
@garthvh How to make it broadcast?

**Comment by Slyke** [comment]
@rcarteraz is clearing the NodeDB the best way to produce a new broadcast to test a new location?

**Comment by garthvh** [comment]
No need to do anything, it happens automatically

**Comment by Slyke** [comment]
@garthvh this is specifically for determining the best place to place a Meshtastic Node. How would Meshtastic know that I've moved the node and want to now see who it can see? I don't understand how it would automatically know this, especially if it has already learned some nodes from previous attempts and may no longer be able to see them at a new location.

**Comment by Slyke** [comment]
Awesome, thanks for the info!
