### ISSUE TITLE
[Feature Request]: Don't Save MQTT Nodes to the NodeDB if IgnoreMqtt is on

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#3438]
### Platform

NRF52, ESP32

### Description

Right now my router node is set to ignore MQTT to not annoy my many nearby lora friends, but it still collects MQTT nodes in the nodedb.

**Comment by tavdog** [comment]
Why have mqtt enabled if you want to ignore everything ?

**Comment by garthvh** [comment]
Seems to be honoring the ignore mqtt for rebroadcasting, but not the node infos

**Comment by tavdog** [comment]
the from_mqtt flag must not be getting set somewhere in the network.  In my test I just had client bridge on and tested by sending packets and nodinfo via python client. It ignored all packets including nodeinfos.  But when I had other nodes possibly repeating nodeinfos they did make it in and I could see that the from_mqtt flag wasn't set.

**Comment by zapewne** [comment]
From my observations, if you disable MQTT then your node will not appear on the map.
