### ISSUE TITLE
[Bug]: Deck seems to disconnect from wifi after a period of time on USB power with battery. Requires reboot

### ISSUE THREAD

**Issue by shleeable** [meshtastic/firmware#3442]
### Category

WiFi

### Hardware

T-Deck

### Firmware Version

2.2.24

### Description

I've got a client running from a tdeck connected to my WIFI for MQTT...

If I leave the client running for more than a day or so. I notice the web client drops off and I need to restart the device.

**Comment by shleeable** [comment]
I don't think this is a dupe of #3129 .. but might be related? I'm not using any mobile client.. this is just http://meshtastic.local/ over wifi

**Comment by caveman99** [comment]
the other bug is fixed with the next release. If the problem persists afterwards we can investigate. Needs debug logs.
