### ISSUE TITLE
[Feature Request]: Default secondary channel

### ISSUE THREAD

**Issue by shleeable** [meshtastic/firmware#3443]
### Platform

NRF52, ESP32

### Description

Meshtastic has become very popular recently with the MQTT support... I've noticed the primary channel is full of "testing testing"

I think a public secondary channel would help keep the primary channel clean.

**Comment by garthvh** [comment]
You can do this already using a private primary channel and the default channel as a secondary

**Comment by shleeable** [comment]
What?
