### ISSUE TITLE
[Bug]: Issue Receiving certain messages 

### ISSUE THREAD

**Issue by grahamrobertslx** [meshtastic/firmware#3447]
[meshtastic-log-2024-03-19T22-31-28.408Z.log](https://github.com/meshtastic/firmware/files/14657575/meshtastic-log-2024-03-19T22-31-28.408Z.log)
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.2.24

### Description

When sending messages to my other node i keep getting the payload \020\224\251\331\322\r which gives me  message of ???? in diamond boxes. One node is on 2.2.24 and the other on 2.3.0. Both are T-Beams
<img width="158" alt="Screenshot 2024-03-19 at 19 53 21" src="https://github.com/meshtastic/firmware/assets/70817634/2650ccd8-1c96-424f-8c1b-e22bb29f6faa">
<img width="319" alt="Screenshot 2024-03-19 at 22 19 51" src="https://github.com/meshtastic/firmware/assets/70817634/2e324d4a-4dba-41bf-84da-b3f3931d598f">

**Comment by paoloponzano** [comment]
Happening to me too

**Comment by andrekir** [comment]
we're tracking this in #3452, please add any additional details or follow the progress there.
