### ISSUE TITLE
[Bug]: MapInfo being sent multiple times per second

### ISSUE THREAD

**Issue by AeroXuk** [meshtastic/firmware#3458]
### Firmware Version

2.3.1.4fa7f5a0

### Description

Using MQTT Explorer I can see that some nodes are sending their mapInfo multiple times per second.

I do not know the reason for this at the moment, it could be misconfigured nodes (in which case maybe we need to enforce a minimum refresh rate), or it could be a bug.

Bad Node Examples:
![image](https://github.com/meshtastic/firmware/assets/9274396/258d350f-0d0f-410d-aa9b-88f51a8efd7e)

![image](https://github.com/meshtastic/firmware/assets/9274396/4d669f0e-d931-4f3a-ae54-e9244550c733)

Topic Summary:
![image](https://github.com/meshtastic/firmware/assets/9274396/2e2ef705-50e7-4a9a-884c-9888ddb3afca)

"Bad" nodes are sending hundereds to thousands of messages per minute. Where as "good" nodes are only sending every 15 mins.

**Comment by GUVWAF** [comment]
I think somehow they did have MapReport settings, but the interval was set to 0. #3459 should fix this.
