### ISSUE TITLE
heltec v3 wont conn when trying to flash [Board]: 

### ISSUE THREAD

**Issue by Winbuck1** [meshtastic/firmware#3481]
### SOC

ESP32

### Lora IC

heltec v3

### Product Link

online

### Description

tried different usb cable,different computer different browsers even different v3 board.when starting up v3 sreen comes on with heltec then connecting then fail.

**Comment by thebentern** [comment]
Try following the guide here: https://meshtastic.org/docs/getting-started/flashing-firmware/esp32/

**Comment by Winbuck1** [comment]
Thanks
