### ISSUE TITLE
[Feature Request]: unpower gps module via device shutdown

### ISSUE THREAD

**Issue by cracky22** [meshtastic/firmware#3513]
### Platform

ESP32

### Description

Is it possible to unpower the GPS module when shutting down the Heltec V3 board? I use the goouuu tech gt-u7 module

**Comment by 5kamisama5** [comment]
yes but you need to install a NPN transistor as such for the node to shut it down. 
![HeltecESP32-V3 gps-module](https://github.com/meshtastic/firmware/assets/116696711/7e6376fb-a4e1-4b0d-a0fb-4d1cc9acee0d)

Look at this 
https://meshtastic.org/docs/hardware/devices/heltec/peripherals/?heltecESP32V3=GPS
