### ISSUE TITLE
[Bug]: Fixed location resetting to 0.0 with v2.3.2.63df972 firmware

### ISSUE THREAD

**Issue by Danie10** [meshtastic/firmware#3514]
### Category

Other

### Hardware

Other

### Firmware Version

2.3.2.63df972

### Description

Since updating to v.2.3.2.63df972 firmware my node keeps losing its fixed position. 'Provide phone location' is off, as well as smart beaconing. I just put in my latitude and longitude and altitude and send to device. If I go out at that setting and back in, it shows 0.0 lat and long. I did do a full wipe of my device when flashing. This is on both my Heltec WSL V3's. Am using Android v2.3.2 but was working fine before I upgraded firmware.

'Provide phone location' on does update location, but is no good for my home radio while I'm away. As I say, it was working 100% before the firmware update.

**Comment by caveman99** [comment]
disable fixed location, then set the coordinates, then re-enable it. This is being reworked currently.

**Comment by Danie10** [comment]
Thanks that worked!

**Comment by joneyes** [comment]
Using the workaround does save fixed location data with export/import of settings

**Comment by Makuna** [comment]
I found that that with a fixed position, if Smart Position is turned off, just the Altitude gets set to zero. It takes time to reset, like next position update.  Turn on Smart Position, fixed altitude stays around.

I figured it was related to this issue, so I just added to it.
