### ISSUE TITLE
[Bug]: wrong rssi/snr reading

### ISSUE THREAD

**Issue by lucidnx** [meshtastic/firmware#3526]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.2.24.e6a2c06

### Description

Sometimes I see node that's 5km away from me with rssi around -27dbi and snr 6-7 and that's not possible. I have started digging around and it seems to be showing rssi from router forwarding that message instead of usual target node. I am able to see bad rssi and snr in debug logs too so it's probably node not reading correct value or router sending wrong value?

all nodes are on same version. with NeighborInfo enabled

### Relevant log output

```Shell
from: 2609459240 (!9b893028)
to: 973326960 (!3a03ca70)
channel: 2
decoded {
  portnum: ROUTING_APP
  payload: "\030\000"
  request_id: 1782341045
}
id: 909505766
rx_time: 1711950676
rx_snr: 6.25
hop_limit: 2
rx_rssi: -27
```

**Comment by garthvh** [comment]
It is recorded on receive and not sent over the mesh, it os not data for the whole route, just the last packet.

**Comment by lucidnx** [comment]
Got it. I thought that it's sent over mesh. Sometimes I am getting -120 rssi, but as I am thinking about that, it is probably random direct connection.

**Comment by jp-bennett** [comment]
> It is recorded on receive and not sent over the mesh, it is not data for the whole route, just the last packet.

We might be able to leverage the new hopStart field to only report true snr values. Worth considering?
