### ISSUE TITLE
[Bug]: Wrong distance shown on OLED display

### ISSUE THREAD

**Issue by lucidnx** [meshtastic/firmware#3527]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.2.24.e6a2c06

### Description

I am getting wrong distance to node on OLED display. It shows 458 meters instead of almost 4km. Android app is showing correct distance.

**Comment by GUVWAF** [comment]
I believe this was already fixed by #3361. Please update to the latest beta (2.3.2) firmware.

**Comment by lucidnx** [comment]
Yeah, fixed. sorry
