### ISSUE TITLE
[Bug]: T-Deck canned messages only send to primary channel

### ISSUE THREAD

**Issue by irreverends** [meshtastic/firmware#3543]
### Category

Hardware Compatibility, Other

### Hardware

T-Deck

### Firmware Version

2.3.2

### Description

Sending a canned message when choosing a node to send it to, seems to only send it to the primary channel.

**Comment by HarukiToreda** [comment]
when you press Tab, it allows you to select the node pressing left or right, Press Tab again and it allows you to choose the other channels, just press left and right these show you which you're modifying ><

**Comment by irreverends** [comment]
> when you press Tab, it allows you to select the node pressing left or right, Press Tab again and it allows you to choose the other channels, just press left and right these show you which you're modifying ><

Swiping left or right on the screen, or using the track ball changes the node it's supposed to send to at the top, but it still just sends to the primary channel.

**Comment by thebentern** [comment]
This will eventually be addressed in the TFT UI rework

**Comment by mverch67** [comment]
This PR #3536 may solve it. It emulates the tab key on T-Deck.
