### ISSUE TITLE
[Bug]: Messages unencrypted if MQTT enabled on the device

### ISSUE THREAD

**Issue by cyberorg** [meshtastic/firmware#3549]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.3.2

### Description

Steps to reproduce:
1. Set up an encrypted channel
2. Enable mqtt on a device sending messages
3. Check mqtt debug "Text" log on nodered. https://github.com/scruplelesswizard/meshtastic-node-red flow for example.
4. Or however you can read mqtt messages after protobuf decode.

The messages originating from device where mqtt is enabled are visible in plain text/unencrypted on mqtt broker.

**Comment by GUVWAF** [comment]
Where is your [`mqtt.encryption_enabled`](https://meshtastic.org/docs/configuration/module/mqtt/#encryption-enabled) setting set to?

**Comment by cyberorg** [comment]
It is set to off.

Does setting it to on send unencrypted messages unencrypted and encrypted one’s encrypted? I want to send location, unencrypted channel messages etc. unencrypted to mqtt. Just not the encrypted channel messages.

**Comment by cyberorg** [comment]
Where do I specify sending “Position” which we use for live tracking unencrypted?

**Comment by GUVWAF** [comment]
You'd have to remove the key on the primary channel (set it to `none`).

**Comment by cyberorg** [comment]
Great, thanks for clarifying. Will send a PR later adding this to the doc.

**Comment by cyberorg** [comment]
All messages are encrypted if mqtt encryption is enabled. There doesn’t seem to be any way to keep LongFast unencrypted.

Disabling encryption in mqtt makes even channels with encryption key plain text.

Channel configuration.

![IMG_2413](https://github.com/meshtastic/firmware/assets/1300602/1715d2d4-4e60-4d33-aadc-1ce888645a5c)

Mqtt configuration 
![IMG_2414](https://github.com/meshtastic/firmware/assets/1300602/47f2e9f4-d616-4010-9250-6c2afda4220a)

Lonfast is encrypted, it should not be.
![IMG_2415](https://github.com/meshtastic/firmware/assets/1300602/4cb1c66a-2c05-4694-9769-383f1fafe56c)

**Comment by GUVWAF** [comment]
If it doesn't have a key, the "encrypted" part is already a [`Data` message](https://github.com/meshtastic/protobufs/blob/6157a5723745b3a750720b94676198a7f3839e2a/meshtastic/mesh.proto#L697), but that is still a protobuf encoded message. Depending on the portnum, you can decode the payload. You should see the text in it already if you send a text message.

**Comment by cyberorg** [comment]
The nodered flow already does decode, when mqtt encryption is not set. This shows up if mqtt encryption is set even on a channel where no key is set.

**Comment by GUVWAF** [comment]
Yes, so now you should let the NodeRED flow also decode the part that is "encrypted" if channel is 0, because that doesn't have a key now.

**Comment by cyberorg** [comment]
Image attached with "https://maps.app.goo.gl/1XwAtZJavero6p2a8" is after it runs through decode. Let me know if you need access to this nodered and mqtt server if you want to test sending position and text with mqtt encryption enabled and disabled, can share credential.

**Comment by GUVWAF** [comment]
You want MQTT encryption enabled (because you want text from other channels end up encrypted on the MQTT server), but then you have to instruct NodeRED to decode the "encrypted" field for channel 0 just like it does when it says "decoded".

**Comment by cyberorg** [comment]
Yes, regardless of change on the node to send encrypted or not to mqtt, all messages go through "decode". When encryption is on, it shows Channel 0 without key set messages also encrypted.

Do you mean to say I need to pass those through "decode" twice?

**Comment by GUVWAF** [comment]
I’m saying that somewhere the NodeRED flow does not decode the “encrypted” part of the MeshPacket, but it should do that when the channel is 0, because it has no key.

**Comment by cyberorg** [comment]
Nodered shouldn't need to decrypt those if they are forwarded to mqtt unencrypted, it would work just as if they do when mqtt encryption is not enabled. "Decode" and "Decrypt" are two different things. All messages go through protobuf decode, no decryption is done in nodered flow.

**Comment by GUVWAF** [comment]
I’m not saying it should decrypt them. Yes, NodeRED always decodes the MeshPacket, but apparently it doesn’t decode the “encrypted” part.

If you enable MQTT encryption, the Data message will always show up as “encrypted”, for all channels. However, I told you you have to instruct NodeRED to decode this part of the message as well (using the Data message just like it does when the field is called "decoded") for channel 0.

**Comment by GUVWAF** [comment]
Well, that's a different question. Currently it's implemented like this, probably as a safety measure. A packet is never send in the "decoded" state if you enable encryption, it doesn't actually check if it has a key or not.

**Comment by GUVWAF** [comment]
Port 24?
After you decoded the "encrypted" field with the `Data` message, it shows which portnumber it is (so e.g. position or text) and then you can decode the `payload`.

**Comment by cyberorg** [comment]
alright, let me ask chatgpt.
