### ISSUE TITLE
[Bug]: Shortname overflow potential if unicode characters included

### ISSUE THREAD

**Issue by apt105** [meshtastic/firmware#3553]
### Category

Other

### Hardware

Other

### Firmware Version

2.3.2.63df972d

### Description

Using meshtasticd on a raspberrypi zero with adafruit RF95 hat. When altering the short name using the web client, including a unicode character as one of the four characters causes a string overflow. This is likely due to a unicode character using more than one byte, some unicode characters can fit in the short name with two other ascii characters, but I haven't done extensive testing.

### Relevant log output

```Shell
[Router] Can't decode protobuf reason='string overflow', pb_msgdesc 0x2c2c400
 [Router] Error decoding protobuf module!
 [Router] Can't decode protobuf reason='string overflow', pb_msgdesc 0x2c2c400
 [Router] Error decoding protobuf module!
```

**Comment by jp-bennett** [comment]
I think the real problem is the silent failure, rather than the client detecting and giving a useful response.
