### ISSUE TITLE
[Feature Request]: Ability to shutdown module before device is set up through app or CLI.

### ISSUE THREAD

**Issue by djripcord** [meshtastic/firmware#3569]
### Platform

ESP32

### Description

A useful feature of the firmware would be the ability to shutdown the module (the traditional way by holding PRG for 5 seconds) immediately after flashing of fresh firmware. This would allow for modules to be flashed in bulk easily without the need to connect them to a device for setup. Additionally, it resolves the concern for leaving the unit powered up without an antenna connected. If this feature is implemented, modules can be flashed and immediately stored for later use.

**Comment by thebentern** [comment]
Devices don't transmit until a lora region is set. You can also set lora.tx_enabled = false to make sure that an already provisioned device doesn't transmit
