### ISSUE TITLE
[Bug]: Send UTC time over the phone API

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#3575]
### Category

BLE

### Hardware

Not Applicable

### Firmware Version

2.2.34

### Description

The phone api seems to be sending times with the firmware timezone adjustment, this is all managed by iOS and need to be UTC time.

**Comment by caveman99** [comment]
can you pinpoint a specific message where this is the case?

**Comment by garthvh** [comment]
Fixed by #3576
