### ISSUE TITLE
[Board]: T-Deck_LR62XE

### ISSUE THREAD

**Issue by Mambo430** [meshtastic/firmware#3589]
### SOC

ESP32

### Lora IC

LR62XE

### Product Link

https://www.fanstel.com/lr62xe

### Description

The LR62XE was added to the T-Deck without a LoRa radio. The firmware needed a slight modification in order to allow proper communication. I had to comment out the DIO3 sections as this module does not have one readily available.

**Comment by Mambo430** [comment]
Modifying the following allows the radio to be detected.
#define SX126X_DIO3_TCXO_VOLTAGE 0

**Comment by thebentern** [comment]
Sounds like some really neat DIY hardware setup. Probably not going to add mainline support for it though.
