### ISSUE TITLE
[Feature Request]: Location Privacy

### ISSUE THREAD

**Issue by JordanEJ** [meshtastic/firmware#3594]
### Platform

NRF52, ESP32

### Description

I would like to suggest a feature that allows a user to set privacy zones. For example, when I get within 500m of home, the broadcasted location from the node should then default to a specific location that I have set. (Somewhere within that 500m but not my house e.g. a park)

**Comment by thebentern** [comment]
This is already being tracked in https://github.com/meshtastic/protobufs/issues/463
