### ISSUE TITLE
[Feature Request]: Add support for Adafruit 128x64 OLED Bonnet for Raspberry Pi

### ISSUE THREAD

**Issue by brigante91** [meshtastic/firmware#3603]
### Platform

NRF52, ESP32

### Description

The display is correctly identified and lights up. but from the device configuration if I set "Button pin override" with one of the pins of the adafruit HAT it doesn't work or rather it moves between the various screens.

**Comment by thebentern** [comment]
Can you post your config yaml? Sounds like a GPIO pin or two are off
