### ISSUE TITLE
[Feature Request]: HT1818Z3G5L GPS support

### ISSUE THREAD

**Issue by hpsaturn** [meshtastic/firmware#3616]
### Platform

ESP32 T-Deck firmware (beta and alpha versions)

## Overview

I have some radios ready with Meshtastic, and I was testing the T-Deck hardware with this [GPS module HT1818Z3G5L](https://de.aliexpress.com/item/1005001634086877.html), but I notice that the GPS is detected but the firmware can not retrieve the info maybe. I have using this module in [other development](https://github.com/jgauchia/IceNav-v3) and works fine with the TinyGPS library for example. 

I'm relative new around the Meshtastic development, I did some PR in the Android app of it, and I know some things around the ESP32 development. What is the way or the first steps to try to contribute with support this module? Thanks in advance.

## Serial output

```bash
WARN  | ??:??:?? 762 [GPS] 3 new GPS checksum failures, for a total of 17948.
WARN  | ??:??:?? 762 [GPS] 7 new GPS checksum failures, for a total of 17955.
WARN  | ??:??:?? 762 [GPS] 1 new GPS checksum failures, for a total of 17956.
``` 

## Extra context

Here a video showing the issue:
https://github.com/meshtastic/firmware/assets/423856/89fe4116-e3f4-47ae-8ec0-b3935f05c1e1

**Comment by GPSFan** [comment]
The AT6558 chipset is a Casic protocol chip and is not currently supported, but has a PR to add support. See PR #3610.
