### ISSUE TITLE
[Bug]: Dockerfile: --hwid: (PROGRAM ERROR) Option should have been recognized!?

### ISSUE THREAD

**Issue by micheljung** [meshtastic/firmware#3619]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

n/a

### Description

If you follow [Usage with Docker](https://meshtastic.org/docs/software/linux-native/#usage-with-docker) and execute:

    docker run --rm -p 4403:4403 meshtastic/device

You get:

    meshtasticd: --hwid: (PROGRAM ERROR) Option should have been recognized!?

Because of this in the Dockerfile:

    --hwid=${HWID:-$RANDOM}

But neither of these variables are set and I'm not sure how this is supposed to work. I assume `HWID` should be a build argument but what about `RANDOM`?

**Comment by ymilord** [comment]
Ran into the same issue. How do I go about fixing this?

**Comment by micheljung** [comment]
@ymilord remove `--hwid=${HWID:-$RANDOM}` from the Dockerfile and build the image again

**Comment by ymilord** [comment]
Thanks
