### ISSUE TITLE
[Bug]: T-Deck Delay on typing

### ISSUE THREAD

**Issue by KyleMaas** [meshtastic/firmware#3623]
### Category

Other

### Hardware

T-Deck

### Firmware Version

2.3.3

### Description

When typing out a new message on the T-Deck keyboard, there is a substantial delay between when each key is pressed and when it registers and shows up on screen.  If you start typing another key before the first one shows up on screen, the intervening key presses are ignored.  This results in needing to type each key individually at a very slow pace if you don't want letters dropped.

**Comment by thebentern** [comment]
This is a hardware limitation

**Comment by KyleMaas** [comment]
@thebentern Could you explain a little bit as to why this is a hardware limitation?  CPU-bound?  Screen refresh taking so long that keyboard scanning can't happen?

**Comment by KyleMaas** [comment]
So then is this considered a hardware issue because the delay is actually coming from the keyboard microcontroller being slow to process keypresses?

**Comment by KyleMaas** [comment]
It's fixed in the new device-ui stuff - keyboard's immediately responsive.  So I think when that hits the mainline this should be fixed.
