### ISSUE TITLE
[Bug]: If a message fails to send while you're typing a new message, the new message in-progress is cleared

### ISSUE THREAD

**Issue by KyleMaas** [meshtastic/firmware#3624]
### Category

Other

### Hardware

T-Deck

### Firmware Version

2.3.3

### Description

I believe this is most easily reproduced using the Long-Slow preset.

Type out a message, send it, and then start typing another message.  If the first message fails to send (like if you're out of range of any other nodes), the failed error message pops up on screen.  When that happens, it clears the message that was being typed so you have to type it again from the start.

**Comment by KyleMaas** [comment]
I should note that I think Long-Slow makes this more frequent due to the amount of time it takes to send messages putting the error message squarely in the realm of where another message has already been started.

**Comment by fifieldt** [comment]
@KyleMaas  Is this for Android, IoS, or Web app?

**Comment by KyleMaas** [comment]
@fifieldt This is on the T-Deck itself.

**Comment by HarukiToreda** [comment]
https://github.com/user-attachments/assets/e03695eb-02d4-4f2e-be1e-d42d84da7d1e

this is no longer an issue as seen this video, message received and it was not cleared
