### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by bilau20** [meshtastic/firmware#3626]
### Platform

ESP32

### Description

I have just received a Heltec Wireless Tracker V1.1, and I need to modify the meshtastic code on what is printed on the LCD and I also need it to connect to wifi to transmit GPS data(coordinates, altitude, speed and # of satelites) to ThingSpeak. How would I change the codes to achieve this functionality? Do I need to download all the files and just make my changes in the screen.cpp? ANd how do I flash it to my device afterwards? when I use my zip file in meshtastic web flasher nothing happens. Myabe I left too many files in the folder from the Github code download.

**Comment by todd-herbert** [comment]
You can find instructions for building Meshtastic here: https://meshtastic.org/docs/development/firmware/build/
