### ISSUE TITLE
[Bug]: T-Beam S3 blocks during boot

### ISSUE THREAD

**Issue by oseiler2** [meshtastic/firmware#3650]
### Category

Hardware Compatibility, Serial

### Hardware

T-Beam S3

### Firmware Version

v2.3.5.2f9b68e

### Description

T-Beam S3 devices can hang at boot until a serial connection is established on the USB CDC interface.
This was likely introduced by https://github.com/meshtastic/firmware/pull/3597
Also see https://github.com/meshtastic/firmware/pull/3597#issuecomment-2058845144

It hangs after the below logs for me. When I connect a serial on the USB CDC port it continues booting.

FWIW, I don't think it is necessarily related to this https://github.com/espressif/arduino-esp32/issues/7554
I have checked all `flush()` calls on the relevant HWCDC and couldn't isolate the issue by doing so.

### Relevant log output

```Shell
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x3ac
load:0x403c9700,len:0x9b4
load:0x403cc700,len:0x28d8
entry 0x403c98bc
E (414) esp_core_dump_flash: No core dump partition found!
E (414) esp_core_dump_flash: No core dump partition found!
[  1304][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
```

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/t-beam-wont-power-on-without-usb/12043/2
