### ISSUE TITLE
[Bug]: Unknown Timestamp on firmware > 2.2.23

### ISSUE THREAD

**Issue by thelamedia** [meshtastic/firmware#3669]
### Category

BLE

### Hardware

Rak4631, Heltec V3

### Firmware Version

2.3.2 and above

### Description

For devices that do not have RTC modules, the timestamp is no longer available beyond firmware 2.3.2.  When rolling back to 2.2.23, the timestamp returns.  Tested on Heltec v3 and Rak 4631 on multiple units.

**Comment by garthvh** [comment]
A RTC by itself is not a source of time, what is your time source?

**Comment by thebentern** [comment]
The only thing that could have possible affected this from the 2.2.24 release is the position precision feature's skipping of position broadcast for precision set to zero, in which case you should see this in the logs:
`Skipping location send because precision is set to 0!`

**Comment by thelamedia** [comment]
My assumption is that the timestamp was previously being pulled from the Meshtastic app over BLE using the device GPS.  However after updating the firmware, none of the position settings transfer that data.

When looking at the position logs, Lat and Long are there, but timestamp shows as "unknown age"

**Comment by thebentern** [comment]
Which app are you using, and can you grab some serial logs?

The web flasher now has a serial monitor if you need one https://flasher.meshtastic.org/

**Comment by thelamedia** [comment]
> Which app are you using, and can you grab some serial logs?
> 
> The web flasher now has a serial monitor if you need one https://flasher.meshtastic.org/

I am using the iOS app.  I have pulled a few logs and don't see any position items listed, including the "skipping location send" mentioned above.  I have Channel 0 set to allow position and precise position is toggled.  Smart update is turned off and set to send every 5 minutes.  For the device GPS, settings are "not present" and "fixed position" is enabled.

**Comment by thebentern** [comment]
> Here are some logs from a fresh reboot:

These logs didn't capture any position packets from the phone or the device. 

Since you're using GPS not present and fixed position, I'm assuming this is intended to be a well placed node in a static location, in which case the expectation is that the position remains "fixed" and the phone's position packets will only update the node's time. This is how it is _supposed to_ behave anyway.

**Comment by thelamedia** [comment]
> Since you're using GPS not present and fixed position, I'm assuming this is intended to be a well placed node in a static location, in which case the expectation is that the position remains "fixed" and the phone's position packets will only update the node's time. This is how it is supposed to behave anyway.

Correct, but no time is updated in the current location, and even when moved I'm not seeing position or time updates. 

However in previous firmware it was working as intended.
