### ISSUE TITLE
[Feature Request]:  Mute channel

### ISSUE THREAD

**Issue by thatSFguy** [meshtastic/firmware#3672]
### Platform

ESP32

### Description

The request is to add a mute option to a channel, so users can mute a busy channel without removing the channel itself.  I realize that this would require a flag on the channel level and then changes to respect that flag at the external notification model.   
Thanks for the consideration!

**Comment by thebentern** [comment]
Channels already have a disabled state, which affectively ignores them. This type of thing really should be handled at the application level rather than a firmware level. The firmware is already responsible for too much.

**Comment by KyleMaas** [comment]
I'd argue that this would be a useful feature on devices with a built-in UI, such as the T-Deck.  Although maybe that would be a better to-do task for https://github.com/meshtastic/device-ui
