### ISSUE TITLE
PMSA Sensor no detected[Bug]: 

### ISSUE THREAD

**Issue by MALAONE1** [meshtastic/firmware#3690]
### Category

Hardware Compatibility

### Hardware

RAK 4631, TTGOs

### Firmware Version

2.3.6

### Description

I have two PMSA 0031 sensors that are supposed to be Meshtastic compatible. I have one from RAK Wisbock that I can plug in directly and I have one that I can solder to the I2C interface. The sensor is not recognized or auto detected by the RAK 4631, Lora T3S3 and TTGO Lora32 1.6. The air quality module has been enabled in the telemetry module. This was not recognized in the previous firmware either

**Comment by shodan8192** [comment]
Hello, I have RAK4631 with RAK12039 (PMSA003I). This sensor become detectable on I2C bus after ~3 seconds from powering up, when scan is already finished.

Inserting `delay(4000)` after `digitalWrite(AQ_SET_PIN, HIGH)` in this code should help : https://github.com/meshtastic/firmware/blob/75dc8cccecd52da78f1d69eeb4eb017fbc68f26c/src/main.cpp#L371-L375
