### ISSUE TITLE
[Bug]:  Hops Away not present in JSON MQTT output

### ISSUE THREAD

**Issue by slash-bit** [meshtastic/firmware#3744]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.6.7a3570a

### Description

Inconsistency of what you see in the Android app -  Hops Away : 2 and No RSSI and JSON output in MQTT not showing Hops Away and still showing RSSI.
There is no way to calculate Hops Away from JSON as hop_limt and hop_start also not present.
{
    "channel": 0,
    "from": 3664096736,
    "id": 1186871389,
    "payload": {
        "altitude": 85,
        "latitude_i": 517720000,
        "longitude_i": 395000,
        "precision_bits": 32,
        "time": 1714295445
    },
    "rssi": -124,
    "sender": "!da656a30",
    "snr": -18,
    "timestamp": 1714295459,
    "to": 4294967295,
    "type": "position"
}

![photo_5868455005164519139_y](https://github.com/meshtastic/firmware/assets/77391720/9bfddfeb-216f-43ac-b32a-27a68b15a639)

**Comment by thebentern** [comment]
Hops away is already calculate in the firmware and placed onto the json payload, if it is non-zero.
![image](https://github.com/meshtastic/firmware/assets/9000580/f3ccc607-c18e-4a95-aac0-5f25e7c10046)
