### ISSUE TITLE
[Bug]: Suspected duplicate device identifier

### ISSUE THREAD

**Issue by grinco** [meshtastic/firmware#3746]
### Category

Other

### Hardware

Other

### Firmware Version

2.3.6.7a3570a

### Description

My device has been heard on another continent. See screenshots. I suspect that it's an ID overlap.
![Screenshot_20240428_154514_Meshtastic](https://github.com/meshtastic/firmware/assets/5553528/5baf0d13-d640-4246-be9b-0085cebe1ef2)
![MeshMap - Meshtastic Node Map (28 04 2024 16_38)](https://github.com/meshtastic/firmware/assets/5553528/55431425-b163-43b3-b25b-d517aeac0f6c)
![MeshMap - Meshtastic Node Map (28 04 2024 16_36)](https://github.com/meshtastic/firmware/assets/5553528/1fcc81e3-e8a4-40fd-98ba-deb1e5d00eb2)

**Comment by GUVWAF** [comment]
According to Meshmap it's not the same Node ID. It shows different user IDs (`!327b23ca` and `!da575630`), which is derived from this. But I assume you don't have it set to US region when you're in Czech Republic? So then something else is wrong.

I see you run the Linux Native application (it says `PORTDUINO`) which uses a random ID if it doesn't has Bluetooth, but you can specify it with `--hwid`.

**Comment by thebentern** [comment]
Meshmap is also not an official meshtastic source, though I do believe much of the data comes from our mqtt.
