### ISSUE TITLE
Enhancement: Air Quality values getting cut off

### ISSUE THREAD

**Issue by HarukiToreda** [meshtastic/firmware#3751]
When Telemetry is turned on, the Air quality values are getting cut off at the bottom of the screen. I think reducing the header size will give enough room for this to show on smaller screens like on the Heltec V3.

![20240430_000502](https://github.com/meshtastic/firmware/assets/116696711/4aa99a4a-1b2d-4396-8053-04557f1ed022)

**Comment by todd-herbert** [comment]
In EnvironmentTelemetry.cpp, it might be an idea to modify the `drawFrame` method, so that it checks `display->height()`. If the height is below some value, could then use`FONT_SMALL` everywhere `FONT_MEDIUM` is used?

**Comment by HarukiToreda** [comment]
> In EnvironmentTelemetry.cpp, it might be an idea to modify the `drawFrame` method, so that it checks `display->height()`. If the height is below some value, could then use`FONT_SMALL` everywhere `FONT_MEDIUM` is used?

Thank you, I think I have a working rough draft, I will wait for my other pull request to post the fix for this. 

![20240430_011336](https://github.com/meshtastic/firmware/assets/116696711/ebed7847-6d41-4ddd-bd4d-4976f1720f91)

**Comment by paoloponzano** [comment]
Very nice fix, thank you :)

**Comment by thebentern** [comment]
Closed by #3785
