### ISSUE TITLE
[Bug]: GPS coordinates are not saved

### ISSUE THREAD

**Issue by ozmy** [meshtastic/firmware#3781]
### Category

Other

### Hardware

DIY

### Firmware Version

2.3.7.30fbcab

### Description

GPS coordinates are not saved when using fixed values

### Relevant log output

```Shell
GPS coordinates are not saved when using fixed values.
after reboot the values become zero
```

**Comment by scottjpalmer** [comment]
The workaround seems to be turn fixed position off, send to node, after reboot turn fixed position on then add the coordinates and it behaves as it should

**Comment by garthvh** [comment]
Yes this is working as expected, once set fixed position coordinates can't be updated until fixed position is off
