### ISSUE TITLE
[Bug]: ESP32 BLE Sleep Regression

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#3808]
### Category

BLE

### Hardware

Not Applicable

### Firmware Version

2.3.7

### Description

Some of our recent ESP32 BLE updates have introduced a pretty painful BLE regression where the BLE radio seems to be powered off and is not started back up.  There is no sleep state with BLE, it is either off or on and it seems like it never comes back on.  If a role offers BLE, it should not be turned off as user intervention is required to turn it back on.

**Comment by thebentern** [comment]
For the T-Beam Supreme issue reported in Discord, I believe that #3764 re-introduced this issue #2793
