### ISSUE TITLE
🐞 [Bug]: Power Metrics Telemetry not reported correctly for INA219BID

### ISSUE THREAD

**Issue by eric-becker** [meshtastic/firmware#3820]
### Firmware Version

2.3.8

### What did you do?

On two separate nodes, I installed a RAK16000 DC Current Module (INA219BID) on the IO slot of a RAK19007 board with RAK4631 Core and toggled on  Telemetry -> Power Options -> Enabled. The sensor has vin+ connected to the positive lead from a RAK Unify solar panel and vin- connected to the positive lead going to the solar port. Both ground leads are connected to GND on the module.

![image](https://github.com/meshtastic/Meshtastic-Apple/assets/2933063/a6b06d0d-71e4-4ba1-aa12-5d0e9d7831c2)

### Expected Behavior

DC Current values to be displayed in the Apple client similar to the Android client.

![image](https://github.com/meshtastic/firmware/assets/2933063/f62db363-b074-4149-8a5f-3d0aff504f53)

### Current Behavior

The client receives standard telemetry alternating with incorrect zero or null values resulting in 0% battery sometimes displayed for the node as well as a sawtooth pattern for the graphs.  

![image](https://github.com/meshtastic/Meshtastic-Apple/assets/2933063/c5c1714a-c9f6-440e-934b-2b7bc6d8e1a1)
![image](https://github.com/meshtastic/Meshtastic-Apple/assets/2933063/3f95874f-e01d-478b-a4fa-b48078f7138c)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This is fixed in the latest TestFlight release, the power telemetry data still needs a lot of work in the firmware.

**Comment by gretel** [comment]
> This is fixed in the latest TestFlight release, the power telemetry data still needs a lot of work in the firmware.

cool, this will help my solar node. can you share the testflight link, please?
