### ISSUE TITLE
[Bug]: unPhone BLE Pairing Method Defaults to `FIXED_PIN` instead of `RANDOM`

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/firmware#3822]
### Category

BLE

### Hardware

Other

### Firmware Version

2.3.7

### Description

unPhone BLE Pairing Method Defaults to `FIXED_PIN` instead of `RANDOM` which it should default to considering it has an attached screen.

**Comment by caveman99** [comment]
i think that's just the preloaded config when they send it out. Mine was also set to EU_868 already. if you factory reset it will revert to standard behaviour.

**Comment by caveman99** [comment]
Looks like i was mistaken ... ;-)
