### ISSUE TITLE
RAK14000 ink display is broken

### ISSUE THREAD

**Issue by miodzicho** [meshtastic/firmware#3843]
I have meshtastic starter, connected RAK14000 with ink display, but it seems all wrong (attached photo). No GPS connected. ![IMG20240509121732.jpg](https://github.com/meshtastic/firmware/assets/1526145/b3cdbae6-9d1d-47fd-a22d-9f8fa37ba7b3)

**Comment by caveman99** [comment]
Looks like you got the three-color version of that device. I don't think this is supported yet.

**Comment by miodzicho** [comment]
Seems indeed that could be not supported yet. I hope that it will be supported at some point.

**Comment by markbirss** [comment]
> Seems indeed that could be not supported yet. I hope that it will be supported at some point.

Tricolor display can't refresh fast enough to be usable with meshtastic

They don't support partial or fast updates and takes upto 18s to just to full refresh a single page

**Comment by markbirss** [comment]
not planned
