### ISSUE TITLE
[Bug]: Heltec LoRa setting mismatch

### ISSUE THREAD

**Issue by memo-567** [meshtastic/firmware#3852]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.9.f06c56a alpha

### Description

After updating to FW 2.3.9.f06c56a Alpha, LoRa setting on Heltec V3 is EU_868 MHz instead of EU_433 MHz.

**Comment by thebentern** [comment]
What happens if you set the LoRA region back to EU_433MHz?
I don't understand how this is possible with just a firmware upgrade, especially considering that the part of the codebase that deals with this is unaffected.

**Comment by memo-567** [comment]
> "What happens if you set the LoRA region back to EU_433MHz?"

Of course I did that. I will continue to monitor this and inform you after the next update or close this issue.

**Comment by memo-567** [comment]
It happened again  ¯\\\_(ツ)_/¯
After updating to Meshtastic Firmware 2.3.10.d19607b Alpha, the LoRa frequency was reset to EU_868 on both Heltecs.
It's not a big deal for me to change it manually again - but maybe there's a better way?

**Comment by thebentern** [comment]
I wonder if you downgrade to 2.3.9 again... if you can consistently reproduce. If so, could you grab some serial logs? If you use the web flasher we capture the log output immediately after resetting flashed device.

**Comment by memo-567** [comment]
I can do that right away. I'll start the downgrade to 2.3.9 now.

**Comment by memo-567** [comment]
Downgrading doesn't affect LoRa settings. I'm going to upgrade again now to 2.3.10.

**Comment by memo-567** [comment]
After updating to FW 2.3.11 everything was fine again.
