### ISSUE TITLE
[Bug]: Device screen: non-english characters

### ISSUE THREAD

**Issue by panayotoff** [meshtastic/firmware#3854]
### Category

Other

### Hardware

T-Beam S3, Heltec V3

### Firmware Version

2.3.6.7a3570a Beta

### Description

When users send non-english characters ( ex. Cyrillic letters ) the device display does not show them. Tested with T-Beam supreme / Heltec v3. Is it possible to have UTF-8 encoding for the screens? 
The iOS/Android app displays properly the characters. 

### Relevant log output

![meshtastic_encoding](https://github.com/meshtastic/firmware/assets/141830/64966eb3-e6d5-49c8-a9d2-58f403e363d6)

_No response_

**Comment by todd-herbert** [comment]
I remember someone added support for Ukrainian at some point. I think you have to [build the firmware](https://meshtastic.org/docs/development/firmware/build/) yourself, adding an extra line of code to enable it:

![image](https://github.com/meshtastic/firmware/assets/24772776/20afa8d5-c13a-4551-a5e6-6bc8e4104d57)
(Screenshot from discord)

**Comment by thebentern** [comment]
@todd-herbert is correct. You will have to compile your with the font macro
