### ISSUE TITLE
[Bug]: MQTT JSON message are not encrypted if Encrpyted is on

### ISSUE THREAD

**Issue by petrkr** [meshtastic/firmware#3919]
### Category

WiFi, Other

### Hardware

Not Applicable

### Firmware Version

2.3.6.7a3570a

### Description

If there is enabled JSON output in MQTT then payload in JSON is not encrypted regardless on "Encryption enabled" is on/off

in topic /e/ it encrypt if enabled, plain text if disabled.

Do not know if this is actually BUG or Feature. But node with JSON enabled output will send unencrypted plain text even encryption is enabled.

**Comment by caveman99** [comment]
JSON is never encrypted, that is intended behaviour. the encryption only affects the binary protobuf format payload.
