### ISSUE TITLE
[Bug]: Fixed position values get cleared upon nodedb reset

### ISSUE THREAD

**Issue by prokrypt** [meshtastic/firmware#3929]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.3.x

### Description

From https://github.com/meshtastic/Meshtastic-Android/issues/1044

**Comment by caveman99** [comment]
This is not just intended behaviour but also intentional behaviour and will not be changed. If this is not documented, documentation needs to be added.

**Comment by caveman99** [comment]
ref: https://github.com/meshtastic/firmware/pull/3451

**Comment by nicheath** [comment]
Is there an explanation why this is desired to be this way? I came here to report it because it was not what I was expecting at all. Discovered nodes (dynamic data) vs my node's configured position (configuration static data) seem like two different things.
