### ISSUE TITLE
[Feature Request]: in the web interface somehow show that a new message has been received

### ISSUE THREAD

**Issue by sq5bpf** [meshtastic/firmware#3952]
### Platform

Linux Native

### Description

In the web interface, when a new message arrives, somehow notify the user, and when "messages" is clicked show from which user or which channel it is from.

This feature request might be a general one, but i only have the linux native platform, so can't compare.

**Comment by jp-bennett** [comment]
Agreed that we want this in the web interface. Closing as we'll use meshtastic/web#183 to track it.
