### ISSUE TITLE
[Bug]: M5 Stack firmware not working with ESP32-S3 version of the M5 Stack

### ISSUE THREAD

**Issue by oliveres** [meshtastic/firmware#3970]
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

2.3.10

### Description

invalid header: 0xffffffff after flashing M5 Stack firmware to M5stack Core S3. Tried several times, also custom build in PlatformIO

### Relevant log output

```Shell
invalid header: 0xffffffff
```

**Comment by cocoaway** [comment]
Me too, Atom S3 Lite , adding relevant info.
MacBook Pro, OS version 14.5 Sonoma, chipset Apple Silicon
`invalid header: 0xfESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40048839`

**Comment by lboue** [comment]
Which variant have you build?
