### ISSUE TITLE
[Board]: Flipper zero (with Lora module)

### ISSUE THREAD

**Issue by robot-penguin34** [meshtastic/firmware#3987]
### SOC

Other

### Lora IC

unspecified

### Product Link

https://flipperzero.one/

### Description

Possibly display the qr code to connect apps on the flipper and run as a background process.

**Comment by thebentern** [comment]
Flipper Zero runs an unsupported STM32 core and most of the LoRA modules I've seen for it are UART unfortunately.

**Comment by robot-penguin34** [comment]
Ok, no worries. Thanks for your time.
