### ISSUE TITLE
[Bug]: Lillygo T-Lora T3S3 stuck in reboot un update

### ISSUE THREAD

**Issue by joneyes** [meshtastic/firmware#4028]
### Category

Other

### Hardware

Other

### Firmware Version

v2.3.10.d19607b

### Description

After sending updates to the device that initiate a reboot, the T3S3 shows "Rebooting", drops the USB connection and does not recover. Device has been erased and reflashed twice.
It is not possible to get logs from the issue, as the USB connection does not come back up until the power is cycled or device reset button pressed.
Issue does not occur on v2.3.11.2740a56, so might have been identified and fixed? (Though nothing obvious from v2.3.11.2740a56 bugfix list)

**Comment by thebentern** [comment]
It's likely we inadvertently fixed the issue with the espressif framework upgrade 😄
