### ISSUE TITLE
[Board]: Heltec Capsule Sensor V3

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [meshtastic/firmware#4081]
### SOC

ESP32

### Lora IC

SX1262

### Product Link

https://heltec.org/project/heltec-capsule-sensor-v3/

### Description

Capsule sensor is a portable sensor device with a small capacity battery inside. The sensor part is replaceable and can be used for Meshtatic networks.
![0cf0844c334b3b2a164c0754add96da](https://github.com/meshtastic/firmware/assets/32860565/84158dd4-59dc-4833-8b9f-8d2c7ed95ca1)

**Comment by caveman99** [comment]
You already seem to have meshtastic running on the device. We'd really like to port your changes to the mainline firmware tree. Can you submit the modified source or a pull requests so we can review?
