### ISSUE TITLE
[Feature Request]: Write owner.short_name " sleeping..." into device sleep screen (useful for e-paper)

### ISSUE THREAD

**Issue by Dorn8010** [meshtastic/firmware#4100]
### Platform

ESP32

### Description

Add owner.short_name in Screen.cpp line 289 to show the name of the device while sleeping (e-paper).
Useful when multiple E-paper devices in use, since they keep the screen info when off.

**Comment by todd-herbert** [comment]
@Dorn8010 Are you happy to put in a pull-request for this one?

**Comment by Dorn8010** [comment]
Would love to enter it myself, but now C++ coding experience - so it would be a mess ;)

**Comment by Dorn8010** [comment]
Changed my setup and the pull request to be in line with the trunk formatting to #4134.
