### ISSUE TITLE
[Feature Request]: Change Middle button for ESP32's

### ISSUE THREAD

**Issue by N1obu** [meshtastic/firmware#4110]
### Platform

ESP32

### Description

Could you please change the 'middle button' pin to something compatible with ESP32's?  I'm using an ESP-WROOM-32 and don't have pin 39 available.

Thanks
![20240615_070708](https://github.com/meshtastic/firmware/assets/100533255/35f24706-2d04-4276-9eb2-163a43e31c23)

**Comment by thebentern** [comment]
The DIY variants exist to be modified as desired by users.
