### ISSUE TITLE
[Feature Request]: --request-environment

### ISSUE THREAD

**Issue by joneyes** [meshtastic/firmware#4120]
### Platform

other

### Description

I raised this in the python section first and was referred back to firmware:

It is possible to request the following via CLI for a remote node:
--request-position (returns position co-ords & alt)
--request-telemetry (returns current device metrics)

Is it possible to add --request-environmental to query environmental metric data, when enabled?

**Comment by garthvh** [comment]
Should already be in the firmware, would need to send a environment telemetry packet to a node as a a dm and request a response

**Comment by joneyes** [comment]
Thanks Garth,
any idea what the syntax is for sending an environment telemetry packet is? - i did look and couldn't see anything that jumped out... Hence the post.

**Comment by GUVWAF** [comment]
Replies are not yet implemented in the firmware for Environmental Telemetry.

**Comment by joneyes** [comment]
This is marked as completed.
How do you intiate the query and what is the syntax, as i can't find any supporting documentation?
I was looking for a way to do this to a remote node, so is it via a DM, or CLI --request- command?

**Comment by GUVWAF** [comment]
It's implemented in the firmware. You can send a packet with the corresponding telemetry tag and set `want_response` to true, then it will respond. 

If you want to have it in the CLI, please open a feature request in that repository.

**Comment by joneyes** [comment]
> It's implemented in the firmware. You can send a packet with the corresponding telemetry tag and set `want_response` to true, then it will respond. 
> 
> If you want to have it in the CLI, please open a feature request in that repository.

👍
Did that there before raising it here.
