### ISSUE TITLE
[Bug]: multiple Typo ... mhz -> MHz

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#4126]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.3.12

### Description

multiple Typo "**mhz**" -> "**MHz**"
1) `config.pb.h` multiple in comments
2) `RadioInterface.cpp` L.525 (in LOG_INFO)
3) `sleep.cpp` line 65 (in comment) & line 72 (in LOG_DEBUG)

**Comment by caveman99** [comment]
config.pb.h is generated from the Protobufs directory, hence the comments have to be fixed there.
