### ISSUE TITLE
[Feature Request]: Expand compatibility with RAK WisBlock Sensor Modules

### ISSUE THREAD

**Issue by blue-plum** [meshtastic/firmware#4128]
### Platform

NRF52

### Description

Whilst I'm loving Meshtastic, I am finding that in my local area that the coverage is somewhat lacking. To rectify this, I am looking to implement a couple of solar powered nodes to allow me to bridge some of the gaps and connect our local collective of nodes to the wider mesh outside our little cluster. 

To this ends I have purchased a RAK4631 on a 19007 Base board, and I'm looking to position this (and others as needed) atop some hills in my local area to support these connections. I am however concerned about the "security" of these, and while they will be suitably stealthy, and hidden as best it is practicable to do so, I maintain concerns, which I no-doubt share with others too, about them being tinkered with or even pilfered.

As such, I would be grateful if there could be some consideration into the extension of the Meshtastic compatibility on the nRF52 platform with the wide array of Sensor Modules available. Notably, I was looking at the motion and accelerometer sensors, to use as a mechanism to identify if a node had been moved or tampered with, perhaps even supporting the provision of "alerts" through messages to another defined node. 

Thanks for the consideration.

**Comment by garthvh** [comment]
There is extensive support for wisblock sensors
