### ISSUE TITLE
[Bug]: QMC5883L Has the wrong address in the config

### ISSUE THREAD

**Issue by Africmod** [meshtastic/firmware#4144]
### Category

Hardware Compatibility

### Hardware

Not Applicable

### Firmware Version

2.3.12.24458a7

### Description

According to this datasheet: http://wiki.sunfounder.cc/images/7/72/QMC5883L-Datasheet-1.0.pdf
And also to my testing:
![image](https://github.com/meshtastic/firmware/assets/34478103/f77c9399-71f3-4d28-86ad-2cfe89e1a9ba)

The basic address of the QMC5883L is 0x0D. The current configuration.h file suggest it should be 0x1E.

**Comment by a57224812** [comment]
The basic address is 0x0D. It is suggested to include 0x1E, which one is correct

**Comment by Africmod** [comment]
The address on the QMC5883L is 0X0D I think the configuration.h file should match that.

**Comment by a57224812** [comment]
> QMC5883L上的地址是 0X0D我认为 configuration.h 文件应该匹配它。
Thank you for your answer, but I can't drive it now whether I use 0X0D or 0X1E. I don't know what the reason is

**Comment by fifieldt** [comment]
@caveman99 - you're in git blame for the 0x1E address for the QMC5883L. Did you have one to test with, or should we go with what the docs say?

**Comment by caveman99** [comment]
I have one but there's no support, I am just adding the sensor to detect. The actual implementation was done by somebody else it seems. I don't remember if I had it ever working.

**Comment by a57224812** [comment]
I'm glad to see your answer. I'm currently trying to implement this feature


杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meshtastic/firmware"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月17日(星期二) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meshtastic/firmware] [Bug]: QMC5883L Has the wrong address in the config (Issue #4144)





 
I have one but there's no support, I am just adding the sensor to detect. The actual implementation was done by somebody else it seems. I don't remember if I had it ever working.
