### ISSUE TITLE
[Bug]: very long "long name"

### ISSUE THREAD

**Issue by jranma** [meshtastic/firmware#4182]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.3.13

### Description

![image](https://github.com/meshtastic/firmware/assets/38426382/dc71a26d-7b52-4d73-9f6d-82f1856637f8)

Some user added many "/n" to his "long name", which causes display problems on every app. 
Shouldn't these special control characters be filtered?

**Comment by garthvh** [comment]
![IMG_2774](https://github.com/meshtastic/firmware/assets/1795163/9c2aedc9-fecc-434f-8c26-4725059e38e8)

I would have to allow them to work as line breaks on iOS

**Comment by Cisien** [comment]
The issue you're seeing has nothing to do with `/n` (which is just two normal characters and not a special escape sequence)

I tried reproducing by setting the name using several variations via the python cli with no impact on how the nodes table rendered.

![image](https://github.com/meshtastic/firmware/assets/4044356/e1c8f48c-adc6-4550-9574-55a7bfc22ea1)

![image](https://github.com/meshtastic/firmware/assets/4044356/d288f137-fa3e-4a08-949a-530227eac246)

![image](https://github.com/meshtastic/firmware/assets/4044356/087ee94e-2dab-4bc9-99c5-8371960d036e)

**Comment by garthvh** [comment]
They are newlines

**Comment by garthvh** [comment]
You can easily replicate this with 
meshtastic --set-owner '''tbeamer Line1
Line2
Line3'''

**Comment by Cisien** [comment]
`\n` is a new line,  `/n` is two regular ascii characters
and yes, i can replicate this on my nodes (images in the discord channel)

**Comment by garthvh** [comment]
@thebentern I think we need to replace \n with a space

**Comment by Cisien** [comment]
may want to do the same with other characters. `\t` for example does some "interesting" things
![image](https://github.com/meshtastic/firmware/assets/4044356/025bbb8d-017c-44b7-800a-71575a82778e)
in the IOS app it just looks like extra spaces

`--set-owner "Cisien $(echo -e '\t\t')Rak"`
