### ISSUE TITLE
[Bug,radiolib] wrong CMD_CalibrateImage sx1262

### ISSUE THREAD

**Issue by mrx23dot** [meshtastic/firmware#4193]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.13.83f5ba0

### Description

I did an SPI measurement

it sends out CMD_CalibrateImage
`98 D8 DB `

based on datasheet it should be D7 DB

![image](https://github.com/meshtastic/firmware/assets/4163396/cc2e45b5-ffc0-4599-8c69-f30bc8f936fc)

**Comment by thebentern** [comment]
We lean on RadioLib to handle this https://github.com/jgromes/RadioLib

**Comment by jp-bennett** [comment]
Something doesn't add up. 2.3.13 should have had the upstream fix.
