### ISSUE TITLE
[Bug]: HopStart not populated

### ISSUE THREAD

**Issue by mrx23dot** [meshtastic/firmware#4198]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

?unknown sender version

### Description

A HeltecV3 received
![2024-06-28_231328_9y](https://github.com/meshtastic/firmware/assets/4163396/f34c693b-7854-418c-b882-184815c342c4)

then it relayed it as:
`ff ff ff ff 7c 1e e5 e2 9c 20 3c 52 03 08 00 00 63 8c 48 c1 09 ad cc 0d d8 67 35 47 b6 1e 06 e1 01 5b ea 72 23`

based on protocol
https://meshtastic.org/docs/overview/mesh-algo/#packet-header-flags
[12]=(0x03) is Packet Header
HopLimit = 3  // 4-1 ok
**HopStart  = 0  (original HopLimit)  why isn't this populated via originator fw?**  should be 4..7

I assume other unknown node also uses meshtastic fw, but I don't know which version.

**Comment by GUVWAF** [comment]
`hopStart` was added in 2.3. The transmitter and all nodes on the path towards you need at least this firmware version, otherwise it will get lost.

**Comment by GUVWAF** [comment]
Then it would be incorrect when there are multiple nodes with old firmware on the path.

**Comment by GUVWAF** [comment]
I'd prefer being sure it's either correct data or no available data above not knowing for sure whether it's incorrect or not.

That said, please encourage your mesh users to update their firmware instead.
