### ISSUE TITLE
[Bug]: enabling GPS crashes wio-sdk-wm1110

### ISSUE THREAD

**Issue by fifieldt** [meshtastic/firmware#4223]
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

2.3.15.84088f39

### Description

Set GPS to ENABLED in settings on wio-sdk-wm1110.

Log will halt at:

"Probing for GPS at 9600"

and no more logging can be seen.

### Relevant log output

```Shell
"Probing for GPS at 9600"
```

**Comment by Dylanliacc** [comment]
Actually, it's not a bug. Our firmware does not support the nRF52's internal GPS module. We need to use an external Grove-GPS (Air530) to make sure the GPS function of WM1110 for Meshtastic works correctly.

**Comment by Dylanliacc** [comment]
You can find more details here: [Grove-GPS Air530](https://wiki.seeedstudio.com/Grove-GPS-Air530/). I'll also provide pictures of the device connection, app configuration, and working logs.  
![image](https://github.com/meshtastic/firmware/assets/167049793/5bafb107-dd3b-40d0-b964-1bfcad64b445)
![c64e99a49761eef660e6e0d613a9a22f](https://github.com/meshtastic/firmware/assets/167049793/faba94ec-6c1b-407e-9b02-ee72c4bc6c96)
![0a722495a42bbd5c66e847e6176ecf04](https://github.com/meshtastic/firmware/assets/167049793/c58875bf-ce9a-40e0-bfc7-43630f16d4a2)

**Comment by fifieldt** [comment]
@garthvh @Dylanliacc this is still an issue. Even with a Grove-GPS Air530 connected to the wio-sdk-wm1110, enabling GPS crashes the device. (NB: the wio-tracker-wm1110 pictured above works fine)


[meshtastic-log-2024-07-15T03-11-27.876Z.log](https://github.com/user-attachments/files/16229714/meshtastic-log-2024-07-15T03-11-27.876Z.log)

**Comment by thebentern** [comment]
We need to check the serial definitions. @fifieldt do you know off-hand if the grove UART connector might pin with the UART connected to the CH340? Otherwise we probably need to declare a secondary Serial for the GPS to scan instead

**Comment by fifieldt** [comment]
Taking a look...

**Comment by fifieldt** [comment]
My working theory:

#define GPS_RX_PIN PIN_SERIAL2_RX
#define GPS_TX_PIN PIN_SERIAL2_TX
#define GPS_BAUDRATE 115200

based on:

![image](https://github.com/user-attachments/assets/a0a89092-ea0f-43ce-8a73-be978b51d75b)

**Comment by fifieldt** [comment]
My attempt at setup code for the Air350:
```
+        } else if (gnssModel == GNSS_MODEL_AIROHA) {
+            // Set Normal Mode
+            _serial_gps->write("$PGKC105,0*37\r\n");
+            delay(250);
+            // Disable NMEA while we're configuring
+            _serial_gps->write("$PGKC242,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0*37\r\n");
+            // Set NMEAInterval to 1000ms
+            _serial_gps->write("$PGKC101,1000\r\n");
+            // Initialize the AIROHA Chip, use GPS + GLONASS + BEIDOU + GALILEO
+            _serial_gps->write("$PGKC115,1,1,1,1,0*2B\r\n");
+            delay(250);
+            // Enable NMEA, only ask for RMC and GGA
+            _serial_gps->write("$PGKC242,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0*37\r\n");
+            delay(250);
```

**Comment by fifieldt** [comment]
The recent changes to the probe code have fixed this I believe
