### ISSUE TITLE
[Feature Request]: Unlocked Licensed options and defaults

### ISSUE THREAD

**Issue by kchilton** [meshtastic/firmware#4224]
### Platform

NRF52, ESP32, RP2040, Linux Native, other

### Description

In the US, Amateur/Ham/Licensed operators have access to the 433MHz band for operations such as LoRa and Meshtastic.  However, there is no selection for a Region that provides defaults for this operation.  For example, in selecting EU_433, the duty cycle requirements are not necessary for hams in the US.  Rather than leave the US ham population to guess at a default set of settings, and require a set of command-line configurations not available on the UIs, I suggest that the selection of **IsLicensed** also opens new options for **lora.region**, which in this case may be US_433 with 100% duty cycle, TX power, MQTT, encryption, and other defaults set as appropriate for US hams.  Other regions may also enjoy this option where Amateur operators have privileges not available to the public.  The reason for making this option unlock additional regions, rather than just adding these as new regions, is to prevent unlicensed users of the hardware from unknowingly violating the local laws without clearly claiming to have a license, and tightly couple these new ham-related Regions to the ID and other requirements of **IsLicensed.**

**Comment by garthvh** [comment]
The chance that this change would substantially increase unlicensed use of ham mode is too high, we are like 80% US users.

**Comment by andrekir** [comment]
LoRa regions or frequency plans are for unlicensed use (typically ISM bands). for licensed use, frequency is set via `override_frequency` in the LoRa configs.

users are responsible for following their own local laws, rules and regulations. licensed operators, given their training and certification, are expected to have an even greater understanding and should already know the frequencies they are permitted to use.

**Comment by garthvh** [comment]
> > The chance that this change would substantially increase unlicensed use of ham mode is too high, we are like 80% US users.
> 
> This is why I suggest only turning on the option _only_ when the user selects the IsLicensed option. Then two things have to happen: they have to buy the 433 version of the hardware, and then they have to select that they have a license and input an alleged callsign. Since buying the 433 hardware and not returning it can already lead to unlicensed operation on 70cm by the user selecting EU_433 or MY_433, overriding the frequency, or another such selection without involving the IsLicensed option, there is no increase of abuse by my suggestion or likely increased unlicensed use. Amazon and other retailers gladly sell 433 hardware to anyone without checking licenses, including Heltec and LilyGo units.
> 
> However, my suggestion provides legitimate use and conformity among hams without leaving unlicensed operators with the impression that they are operating legally. It provides for increased Meshtastic use and experimentation within the US within the Amateur community. We already have the problem that the units are sold and usable for unlicensed operators, just as Baofengs and other 70cm rigs end up in the hands of non-hams, so that cat is already out of the bag. What I am suggesting is to help the hams adopt Meshtastic on 70cm _without_ making it easy for the non-hams to make an "innocent" mistake.
> 
> If you see another way to do this, please suggest it.

There is no way to keep it isolated just to the is licensed bool, the existing system works well considering how little ham usage there is, and the risk of accidental usage by having a second US preset.

**Comment by garthvh** [comment]
Most hams use meshtastic with encryption, the existing Ukraine 433 preset is fine, this has not been a barrier to adoption, the lack of encryption is the issue even for hams.

**Comment by garthvh** [comment]
The extra power is not of great benefit with these low power devices, hams can use encryption if they don't use any of their licensed privileges and most done.

**Comment by garthvh** [comment]
You have access to all the settings you need, a preset is just going to cause more unlicensed use of a tiny edge case, which is not what we want.

**Comment by blark** [comment]
In Canada it is perfectly legal for a HAM to encrypt communications as long as the key is known. While many users are American, it feels that ignoring the fact that the rules are different in other parts of the world isn't a great choice.
