### ISSUE TITLE
[Bug]: reboot @ 65 & 90W charger

### ISSUE THREAD

**Issue by cracky22** [meshtastic/firmware#4229]
### Category

Hardware Compatibility, Other

### Hardware

Heltec V3

### Firmware Version

2.3.14

### Description

I currently have the problem that when I connect a 65W and a 90W charger viva usb-C to my Heltec-v3 board, it restarts.

**Comment by thebentern** [comment]
This is likely the USB-PD circuit trying to negotiate a voltage with your Heltec which just wants +5V USB and it's pulling one of the USB to serial pins. Nothing we can do able it on the firmware side I'm afraid
