### ISSUE TITLE
[Feature Request]: Send nodeid, shortname, and longname, on all TEXT_MESSAGE_APP packets

### ISSUE THREAD

**Issue by brad28b** [meshtastic/firmware#4249]
### Platform

NRF52, ESP32

### Description

I run across this issue regularly. I don't think it's bug, it's likely intended behaviour, although I think it could be improved, so I've listed it as a feature request.

Often when a new node joins my Mesh, they will send me a text message, but because I have not yet received a nodeinfo packet from them, my node doesn't know their shortname or longname, so it appears as unknown. This seems to continue to occur until I receive 1 nodeinfo packet from them, then I can see their name.

Requesting if we can possibly send the nodeid, shortname and longname with all TEXT_MESSAGE_APP packets, to avoid this situation? Currently we only get a 'from' number, and if we have not yet received a nodeinfo packet from that node, we cannot use the from number to lookup their shortname and longname in the nodedb.

**Comment by garthvh** [comment]
Adding extra overhead to every packet is not a good idea, there is already packets in place to manage this.
