### ISSUE TITLE
[Feature Request]: (very) stable router firmware

### ISSUE THREAD

**Issue by jranma** [meshtastic/firmware#4269]
### Platform

other

### Description

It would be very useful to have an extensively tested version to flash devices that will be routers. 
These machines are often located on high, hard-to-reach points. A router doesn't necessarily need to have the latest features or sexy options, but stability is crucial. The latest "stable" versions have brought me a few surprises...
Why not release a "router" version every 6 or 8 months, for example, which has undergone a series of extensive tests?

**Comment by garthvh** [comment]
This is what the repeater role is for, it turns off almost everything and just repeats packets.
