### ISSUE TITLE
[Bug]: more conservative data transmission

### ISSUE THREAD

**Issue by jranma** [meshtastic/firmware#4271]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.3.13

### Description

Not really a bug, but not a feature proposal either...

As meshtastic starts to become more and more popular (kudos to the devs!), the issue of RF congestion becomes increasingly important. 

It's important that we all take responsibility for transmitting as little data as possible. Certain default values for data transmission seem to be unnecessarily high. 
In the case of a router, is it useful to send its telemetry every 900 seconds (15 min) in the air? A value of 4 hours seems a good compromise. 
The same question applies to localization. The default value, at least for fixed stations (router, relay....), should be reduced to 6 hours. And everyone is free to set higher values if they wish. 
The same goes for the default value for neighbor mode. A default value of 6 hours would be more than sufficient. 

Those who install solar nodes are of course also interested in this, as energy is saved.

**Comment by GUVWAF** [comment]
Making it more scalable is under active discussion. First two PRs are up: #4273 and #4274.
