### ISSUE TITLE
[Feature Request]: Network Status Widget Data Over the Phone API

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#4292]
### Platform

NRF52, ESP32, RP2040, Linux Native, other

### Description

It would be nice if we had a protobuf that was sent over the phone api on an interval that could be used to enable clients to build widgets and live activities using some network stats. (Nodes online, duty cycle, channel utilization and airtime etc.)

For iOS the live activity which does the best job at keeping the app running in the background needs an action that takes place on a timer, or server side notifications.  Since I want to avoid server side notifications I need something local with a longer timer than device metrics which come in every minute and cause a phone alert.

**Comment by thebentern** [comment]
Closed in #4431
