### ISSUE TITLE
Fancy Maps

### ISSUE THREAD

**Issue by squidjuice** [meshtastic/firmware#4306]
### Category

Other

### Hardware

T-Deck

### Firmware Version

2.4.1

### Description

Maps not working on fancy UI on t-deck. Also time can not be adjusted to my time zone

**Comment by thebentern** [comment]
The map is a placeholder and the new device UI is not released yet. It is too early for feeback.

**Comment by fifieldt** [comment]
There is a new firmware preview for T-Deck that is a significant improvement, I recommend trying it out: https://meshtastic.org/blog/meshtastic-2-6-preview/ !
