### ISSUE TITLE
[Bug]: "emoji" short names crashing Heltec V3 in "client" mode

### ISSUE THREAD

**Issue by martinbogo** [meshtastic/firmware#4309]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.15.deb7c27

### Description

On a deployed mesh, I have four nodes which use Heltec V3, all in client mode, OLED display enabled, MQTT disabled, GPS and all sensor-modes disabled for debugging.

The nodes had long names set to "Tanglewild Fire" "Tanglewild Strawberry" "Tanglewild TRK01" and "Tanglewild TRK02" respectively

The nodes had short names set to "🔥, 🍓, 📻, 👻" respectively.

I attempted to capture a debug log, but the crash is occurring somewhere before an output is created in debug.  I am currently attempting root-cause analysis by adding more debug code around areas where the short name is used.

I was getting rapid boot loops on all four nodes after updating to 2.3.15 which I was not getting in 2.3.14.  Changing the short names to "fire, strb, trk1, trk2" caused the nodes to continue operating normally.  Doing so required shutting down all but the node being updated so my assumption is that this crash is occurring somewhere during one of:

- construction of the node name for transmission
- reading of the node name from flash/ram
- transmission of the node name to another node
- display of a node name on the OLED display

Since this is not occuring in 2.1.14 I am looking at the difference patch-set between .14-.15.  There is a small chance this issue is around the deprecation of the client+router mode, but I'm somewhat doubtful that is the root cause.

### Relevant log output

```Shell
Gathering debug logs - will update once more I have implemented more debug code harnesses around short-name handling.
```

**Comment by todd-herbert** [comment]
My first thought is https://github.com/meshtastic/firmware/pull/4134. I'll dig into it later today.

**Comment by todd-herbert** [comment]
I'm having trouble replicating the issue here, although I don't have the exact same hardware for testing either.
Two quick thoughts:
* are you building with either the `OLED_UA` or `OLED_RU` flag?
* have you tried erasing the flash before installing 2.3.15?

**Comment by martinbogo** [comment]
Is erasing the flash a prerequisite for 2.3.15?   I will do so.

**Comment by todd-herbert** [comment]
> Is erasing the flash a prerequisite for 2.3.15? I will do so.

It really shouldn't be, it's just one of the first things I try myself if I get weird behaviour. Although, the fact that you're seeing the same issue on multiple nodes does make it sound more like a firmware bug.

I'm very interested to hear if you find any clues!

**Comment by ravenium** [comment]
My short name is 🤔 and I haven't noticed any crashes. Running .15 on a heltec v3.  Pretty vanilla otherwise but willing to help if I can!

**Comment by martinbogo** [comment]
Erasing the flash prior to upgrading to 2.3.15 does seem to have alleviated the issue on the Heltec V3 I just tried.  Will continue to test and get back on this.

**Comment by fifieldt** [comment]
Hi @martinbogo . Have you had time to look into this further? Otherwise, since yours is working now, maybe we should close this :)

**Comment by martinbogo** [comment]
Yeah definitely close it.
