### ISSUE TITLE
[Feature Request]: Disable external notifications by default before DefCon

### ISSUE THREAD

**Issue by jmarler** [meshtastic/firmware#4359]
### Platform

ESP32, other

### Description

External notifications that activate the buzzer on the T-Deck are enabled by default when you flash the firmware. For the sake of everyone's sanity at DefCon, can we please disable that by default? I am already anticipating hearing those buzzing noises constantly as people are either incapable of, or unable to, disable that default buzzer. More specifically, I am referring to the "Use I2S as Buzzer" setting.

**Comment by thebentern** [comment]
Merged into defcon release repo. Closing
