### ISSUE TITLE
[Bug]: Bluetooth connectivity drops repeatidly when MQTT JSON is activated

### ISSUE THREAD

**Issue by VA2XJM** [meshtastic/firmware#4388]
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.4.0.46d7b82 Beta

### Description

I have 2 T-Beams and a T-Lora board set to use MQTT and either Wi-Fi or Cellphone as proxy. So far so good, when out of RF range, MQTT is relaying messages.

However, I tried to set the "JSON Enabled" to true so I can integrate in an easy way some data to use with my home automation.

Once turned on and saved, the selected device reboot and reconnect to my mobile device for few seconds and the BLE connectivity drop for few seconds and comes back on. This stats loops until I am quick enough to disable the JSON output OR that I use another device through the admin channel to deactivate it.

The hardware device will not reboot, it continues to work as supposed except for the BLE connectivity.

### Relevant log output

```Shell
Not yet
```

**Comment by garthvh** [comment]
Once you have turned it n WiFi, BLE is off, they use the same radio.
