### ISSUE TITLE
[Feature Request]: Add SOS Alert when user button is pressing 1 time with GPS on Android IoS and Web client

### ISSUE THREAD

**Issue by Niranjoyyengkhom** [meshtastic/firmware#4403]
### Platform

NRF52

### Description

Hi I want an Feature to send an SOS Alert to Mesh network Using User Button this will help this product adoption in use cases like Coal mining, Fire Fighter Personal Tracking etc and other highly Risky areas

**Comment by thebentern** [comment]
This feature has come up before an unfortunately it's problematic from a legal perspective for the project
#3561 

My guidance would be to look at the detectionsensor module in the docs. Someone recently made "man down" switch using this.

**Comment by Niranjoyyengkhom** [comment]
> This feature has come up before an unfortunately it's problematic from a legal perspective for the project #3561
> 
> My guidance would be to look at the detectionsensor module in the docs. Someone recently made "man down" switch using this.

can you give me his contact info
