### ISSUE TITLE
[Feature Request]: Five-way button based on ADC

### ISSUE THREAD

**Issue by gjelsoe** [meshtastic/firmware#4407]
### Platform

ESP32

### Description

Devices from Radio Master aka Bandit lineup has a five-way button connected to a ADC input
adding it would increase the number of buttons and open up for Canned Messages on those devices.

For the Bandit ADC values are [3227, 0, 1961, 2668, 1290, 4095] and corresponds to [UP, DOWN, LEFT, RIGHT, ENTER, IDLE]

Could also be used on other devices which have free ADC pins.

**Comment by garthvh** [comment]
Should map fine to canned messages

**Comment by gjelsoe** [comment]
**WIP.**

It also needs to be working with both Canned and "Main Menu" that is normally is defined with BUTTON_PIN.
Got some code that needs some testing.

**Comment by gjelsoe** [comment]
This is how Radio Masters Bandits are using Five-way buttons.

![image](https://github.com/user-attachments/assets/b9104ba0-9e1d-491d-b6f0-30d63aa6f3b8)

**Comment by gjelsoe** [comment]
@todd-herbert Has/is working on some code for it and it looks very promising..

**Comment by todd-herbert** [comment]
Don't have the hardware, but had a go on behalf. Working from the [ExpressLRS source code](https://github.com/ExpressLRS/ExpressLRS/tree/d9f56f8bd6f9f7144d5f01caaca766383e1e0950/src/lib/SCREEN/FiveWayButton).

https://github.com/todd-herbert/meshtastic-firmware/tree/radiomaster-joystick
According to @gjelsoe, what's there is working for now. If anyone actually has the hardware themselves and wants to take over, please do!

Not sure what to do about "adhoc ping" / "toggle GPS". Is it worth implementing double / triple press for consistency with user button, or just do something else, like map to long-press up/down?
