### ISSUE TITLE
[Feature Request]: Please default to fuzzy GPS location on the Default Channel.

### ISSUE THREAD

**Issue by ADADarkpool** [meshtastic/firmware#4412]
### Platform

ESP32

### Description

Setting up and installing new firmware, I need to rush to disable precise location before my exact location gets broadcast out to the mesh.  This is insecure and not a good default. Please consider switching to a fuzzy location of 1 mile as the default.

**Comment by jp-bennett** [comment]
I thought it was defaulted to off altogether. Yeah, this should be changed.

**Comment by andrekir** [comment]
keep in mind the LoRa radio won't transmit until you change the region from UNSET, which is the factory default setting.
