### ISSUE TITLE
LiFePO4 Charge soupport 

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/firmware#4413]
### Platform

ESP32

### Description

On heltech v3 there is an onboard chip that takes care of charging. SH1.25-2. From the looks of it, it can be reprogrammed and it has its own memory, etc.  

Therefore,  due to the nature of meshtastic LiFePO4 battery cells are an excellent option for powering these devices. And having it as an option is more beneficial than either battery pouches or lithium ion battery cells. Due to the longevity and thermal stability. It can easily outperform long-term lithium ion batteries in the wilderness as a stand alone router.

Making the firmware compatable with LiFePO4 should not be too difficult as it is just changing a few values such as maximum charge voltage and certain charging patterns like trickling, etc. The actual maximum voltage is lower than the actual lithium ion battery. Therefore it should be more than capable of charging these type of batteries.

Although the  device will be slightly under volted it is still a good option and there can always be batteries put into series or parallel to circumvent these issues

**Comment by thebentern** [comment]
This is actually not possible on the Heltec V3 without hardware modification
