### ISSUE TITLE
[Bug]: No last seen time Raspberry PI with Waveshare Hat

### ISSUE THREAD

**Issue by Spogster** [meshtastic/firmware#4416]
### Category

Other

### Hardware

Other

### Firmware Version

2.4.1.394e0e1

### Description

On the Raspberry PI version the time since seen does not change from "Never". You can see in the image, at least 5 of the nodes have been contacted in the last couple of minutes.
![pinever](https://github.com/user-attachments/assets/152a50a5-594c-473f-a872-d7d84ae6b5a6)

**Comment by madeofstown** [comment]
I'm not seeing that problem on a Pi4. Times seem to update about every 5 seconds.

**Comment by Spogster** [comment]
It is A Pi4 running Bookworm Lite I also have a Pi3 also running Bookworm Lite with the same issue. If I look at the app it does show time until I disconnect then reconnect and the last seen reset to never. When I look at the web page it never give a time on the last seen.
I have reinstalled the Pi4 and it makes no difference.

**Comment by madeofstown** [comment]
> It is A Pi4 running Bookworm Lite I also have a Pi3 also running Bookworm Lite with the same issue. If I look at the app it does show time until I disconnect then reconnect and the last seen reset to never. When I look at the web page it never give a time on the last seen. I have reinstalled the Pi4 and it makes no difference.

Are you able to see if it works with RaspberryPi OS? Seems like it could be an OS issue since both of your Pis are running Bookworm Lite. Another thing to try would be building from source if you don't have a spare SD card and don't want to nuke your current OS.

**Comment by madeofstown** [comment]
I also just noticed that 5 of the nodes on your list are from MQTT. You aren't using the default channel right...?

**Comment by Spogster** [comment]
Strange occurrence for some reason a couple of days ago it started to work as expected. I have up dated to 2.4.3.efc27f2 and the problem is back. If you look at the image the ones at the top with times are from before the up date then the ones with never are the ones after the update. 

As soon as I have time I will start to look through the code to see if I can spot the problem.

![meshtastic 2](https://github.com/user-attachments/assets/3dde4fe0-a844-4edc-acd1-ad35ef5d23f6)

**Comment by armisis** [comment]
Raspberry PI Pico w with waveshare lora here does not get last seen
either, and wifi is not working and its not showing a bluetooth (I
need to look again if this thing even has bluetooth, i dont remember)
but i can see it when i hook up to serial port and bring up the web
interface and send messages through that.

**Comment by armisis** [comment]
Ok i will try again to get it online with wifi, I just cannot see the
bluetooth even though the config says it is turned on.... The web console
does not seem to work well for most of my devices so I prefer to configure
things on my android through bluetooth when I can.

**Comment by Spogster** [comment]
If you have WiFi turned on it will turn off the Bluetooth. I always configure my devices initially with the python script on the serial then via WiFi using the app on IP.

**Comment by jp-bennett** [comment]
Seems like this is probably fixed. Please re-open if it's still an issue.
