### ISSUE TITLE
[Bug]: The RF jammer caused the Techo LORA function(Meshtastic) to be paralyzed

### ISSUE THREAD

**Issue by Oliver0804** [meshtastic/firmware#4453]
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.4.1

### Description

After jammer, the Techo device was unable to operate normally until it was reset. In the video linked below, you can see two devices transmitting signals in the SDR. The lighter-colored one is the Tbeam, which I noticed is not affected and continues to work normally.

https://www.youtube.com/watch?v=zJGnJvP88mY

**Comment by thebentern** [comment]
I suspect this overloaded the front-end of the T-Echo and the reboot re-initializes the SX1262. It could be a hardware issue with poor implementation of the RF out stage of the transceiver,
