### ISSUE TITLE
[Bug]: MAC Address duplication

### ISSUE THREAD

**Issue by musznik** [meshtastic/firmware#4459]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.4.2

### Description

When using the nRF52840 (RAK19007 + RAK4630 ) chip, the MAC address is hard-coded and retrieved via NRF_FICR->DEVICEADDR, with no straightforward method to override or customize it. This limitation can lead to MAC address collisions, especially in scenarios where multiple devices with the same MAC prefix exist + MQTT node detection.

![Screenshot_1089](https://github.com/user-attachments/assets/f04bacfe-6bc8-4050-add0-3128a3d23db5)

**Expected Behavior:**

The firmware should allow customization of the MAC address, either by: Providing a method to set a custom MAC address in the software stack, respecting the vendor prefix (stored in local memory)

**Proposed Solution:**

Introduce a feature in the firmware that allows developers to set a custom MAC address programmatically, while still respecting the Nordic Semiconductor MAC address prefix (C0:98:E5).

**Impact:**

This issue impacts users who deploy multiple mesh-based devices and need unique MAC addresses to avoid conflicts in their network infrastructure (+MQTT and telemetry data).

**Comment by garthvh** [comment]
You need to do a factory reset and the actual Mac will surface, this is an issue with the way the firmware was flashed at the factory.
