### ISSUE TITLE
[Bug]: 2.4.3 Hotfix introduces NeighbourInfo Loop - Sending every second.

### ISSUE THREAD

**Issue by Talie5in** [meshtastic/firmware#4502]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.4.3.1 (Hotfix)

### Description

2.4.3.1 Hotfix introduces NeighbourInfo Loop - Sending every few seconds (7-10seconds)
NeighbourInfo set to 3600 seconds.

Noted on Graphs Collected causing high RF use and mention also in Discord thanks to tjr1
https://discord.com/channels/867578229534359593/919642584480112750/1274887561541713941

From my Graphs, you can see where I turned on NeighbourInfo at 01/01:30 AM and turned off again at 15:00 PM
![image](https://github.com/user-attachments/assets/4f3500bc-4fd8-44be-b59d-5d2db347bc67)

Last 6 hours data for another node I have on 2.4.3.1 (Hotfix) = ~7.9seconds per NeighbourInfo Packet.
![image](https://github.com/user-attachments/assets/22388249-a36e-4178-8690-a94f7763de60)

### Relevant log output
[meshtastic-log-2024-08-19T06-14-00.355Z.log](https://github.com/user-attachments/files/16656436/meshtastic-log-2024-08-19T06-14-00.355Z.log)

**Comment by Talie5in** [comment]
Note: After re-enabling with Debug Log it's no longer doing it, I have the same report from another user on the Mesh, dropped ChUtil from 40% back to sub 1%.

Just messing with device to see if it waits before it breaks/loops.

**Comment by Talie5in** [comment]
Logs attached to Original Post.

**Comment by thebentern** [comment]
Ironically, two characters differences produced the opposite of desired behavior
