### ISSUE TITLE
[Feature Request]: Create a CONTRIBUTING.md file for easier onboarding

### ISSUE THREAD

**Issue by Tzal3x** [meshtastic/firmware#4503]
### Platform

other

### Description

It would be nice to have a file like `CONTRIBUTING.md` that describes how to contribute to the project for faster and easier onboarding of new users. 

Example sections:
- How to build the project.
- What are the usual steps of adding a new board. 
- Any conventions used in the project that should be followed by everyone (add linters).

**Comment by fifieldt** [comment]
Related:
https://meshtastic.org/docs/development/firmware/build/


https://github.com/meshtastic/meshtastic/pull/1363

**Comment by jp-bennett** [comment]
I'm actually a +1 on adding the file to the source, even if it's not much more than a link to the web docs.
