### ISSUE TITLE
[Bug]: Apparently finding our own node num in the nodedb can cause us to pick a new nodenum!

### ISSUE THREAD

**Issue by geeksville** [meshtastic/firmware#4559]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

v2.5.0.ab7de7f and 2.4.x

### Description

Per investigation by @dm5tt in https://github.com/meshtastic/firmware/issues/4555#issuecomment-2309754360:

Repeatedly generating a new node ID due to (our) nodenum being found in the internal db is super bad.

Investigate and fix as needed.

**Comment by jp-bennett** [comment]
Do we have a known way to replicate this? I don't think I've seen it in my tests yet.

**Comment by dm5tt** [comment]
You could try reducing the the current limit of your power supply in a steep gradient in the early boot phase. This keep the ESP32 50% alive and 50% dead and sometimes it even jumps into the Bootloader mode (=SPI flash in a zombie state).

Then just doing a "normal" startup and check if the device name turned into a default name again.
