### ISSUE TITLE
[Bug]: Randomization in generatePacketId() breaks TX PacketQueue priority sorting

### ISSUE THREAD

**Issue by gitbisector** [meshtastic/firmware#4560]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.5.0.d6dac17

### Description

Recent commit https://github.com/meshtastic/firmware/commit/300c3d32aa7d8103f473c5b7233fbbf3409879f9 randomized MSBs of packetID whereas https://github.com/meshtastic/firmware/blob/master/src/mesh/MeshPacketQueue.cpp relies on them monotonically increasing for same-priority sorting. 

Under high channel utilization this seems to be causing random packets to see very long TX delays.

**Comment by thebentern** [comment]
Closed with #4561
