### ISSUE TITLE
[Bug]: GPS not recognized on RAK4631, w/ver. 2.5.0.ab7de7f, works fine on 2.5.0.d6dac17

### ISSUE THREAD

**Issue by magpie54** [meshtastic/firmware#4570]
### Category

Other

### Hardware

Rak4631

### Firmware Version

4.5.0

### Description

After updating firmware to 4.5.0 noticed that the RAK12500 was no longer recognized. Rolled firmware back to previous version and it works just fine.

**Comment by garthvh** [comment]
There is no firmware 4.5.0

**Comment by magpie54** [comment]
Sorry, 2.5.0.

**Comment by caveman99** [comment]
can you post a serial log snippet from the first few seconds after power up?

**Comment by magpie54** [comment]
I rolled back to the previous version. Give me a day or so and I’ll do it
again. I’m not totally sure how to get the serial log snippet. Thanks.

**Comment by magpie54** [comment]
Tried again and the GPS seems to be working fine. The difference...
2.5.0.ab7de7f - did not work
2.5.0.d6dacty - seems to work just fine.

**Comment by fifieldt** [comment]
Hi @magpie54 , thanks for the report.

To get a serial log go to https://flasher.meshtastic.org/ and click "Open Serial Monitor".

**Comment by magpie54** [comment]
Tom, thanks for the info on the serial log.
Dave

**Comment by fifieldt** [comment]
Couldn't find any obvious changes for GPS between those versions. However, since a firmware upgrade fixed this let's close it for now. I'll keep an eye on detection problems as while working on #4625 .

**Comment by magpie54** [comment]
Hi Tom,

Hoping you can give me some suggestions to a GPS problem that I have. About
three weeks ago I bought a RAK4631 Wisblock starter kit. It works great.
Today I received the RAK12500 GPS that I ordered last week. I installed it
but can't get it to work. I have two other RAK4631 nodes. One of the two
has a RAK12500 GPS that's been working great for a year or so. I have
compared the configuration in Meshtastic for both radios. They are
configured identically. Both are installed in Slot A.

My node that does not have the GPS can see the other two nodes. However,
the new RAK12500 on the new radio does not indicate positioning like the
year-old one.

Wondering if you have any suggestions to try that I may have missed.

Thanks,
Dave

**Comment by fifieldt** [comment]
Dave - Positions work, but are a bit weird? Maybe check the precision settings in the channel...

**Comment by magpie54** [comment]
Tom, thanks for responding so quickly. I’m a bit embarrassed to tell you
what I found. The module wasn’t seated well. Once I got it properly seated
it began to work just fine.

Thanks again for your response. All the best to you and your family and
Happy Holidays.

Dave
