### ISSUE TITLE
[Feature Request]: Split out packets that were not rebroadcast from errors 

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#4578]
### Platform

NRF52, ESP32, RP2040, Linux Native

### Description

In the local stats message currently we have a number of bad packets that includes the packets that were not rebroadcast because we have seen them before.  If would be good if we could add a new number and remove these packets from the error numbers so we can calculate a more accurate error rate.

**Comment by GUVWAF** [comment]
To be honest I don't think `rxBad` includes duplicates. It's only counted at the lowest level in `handleReceiveInterrupt()`. It may indicate there's a lot of packet collisions, or you're receiving packets on the edge of reception. 

It could also be we're getting "fake" `RX_DONE` interrupts. I've seen that there's at least a lot of false preamble detections, but I doubt it will pass the sync word and header checks *that* often.
