### ISSUE TITLE
[Bug]: Heltec tracker (or ESP32-S3 in general?) user button doesn't work while in light sleep

### ISSUE THREAD

**Issue by geeksville** [meshtastic/firmware#4579]
### Category

Hardware Compatibility

### Hardware

Heltec Wireless Tracker

### Firmware Version

2.5.? (a private build from today's master)

### Description

While working on #4154 I noticed that the heltec tracker board is not automatically waking  from light sleep when the user presses a button.

For instance (if board is configured as a router so that it sleeps and turns the screen off often), the last log messages seen before light sleep are:
```
DEBUG | ??:??:?? 7 [Screen] haveGlyphs=1
DEBUG | ??:??:?? 8 [Screen] haveGlyphs=1
INFO  | ??:??:?? 8 [PowerFSM] Turning off screen
INFO  | ??:??:?? 9 [PowerFSM] lsEnter begin, ls_secs=86400
INFO  | ??:??:?? 10 [PowerFSM] setup LORA_DIO1 (GPIO14) with wakeup by external source
```

The radio **is** able to wake the board (good), but also the user button on the board should also be sufficient for wake.  The wake does not occur if you press the button.  I suspect that something is wrong on the esp32-s3 gpio config for that button.  It should be configured to generate an interrupt to wake the CPU from sleep (so we can then run our regular button processing)

Alas, I don't think I'll have time to investigate this problem before I leave town.  So recording it so that it is known and perhaps someone else can dig into it as needed.

**Comment by todd-herbert** [comment]
Just as an initial report: I checked Heltec Wireless Paper with 2.5.0.d6dac17 from the web flasher, and the user button is waking the from light-sleep as expected, so this might be version specific or device specific.

**Comment by HarukiToreda** [comment]
I am seeing this on my nodes with cardkbs while in lite sleep.

**Comment by todd-herbert** [comment]
@HarukiToreda With Heltec V3, right?

**Comment by thebentern** [comment]
Seems like they're coming out of Deep Sleep just fine with the user button interrupt. Been using this on my V3 and Tracker. I wonder if we just need to A/B compare those.

**Comment by geeksville** [comment]
(btw: it is taking a bit longer to setup our new rental apartment than
expected, so I won't be back to recreational github meshtastic futzing
until about 10/17 :-( )
