### ISSUE TITLE
[Bug]: If no GPS lock within timeout, state goes ACTIVE->HARDSLEEP then immediately HARDSLEEP-ACTIVE

### ISSUE THREAD

**Issue by fifieldt** [meshtastic/firmware#4657]
### Category

Other

### Hardware

Other

### Firmware Version

2.5.0.bdc11c74

### Description
For shorter broadcast_interval_secs, if there's no GPS lock within the timeout  (scheduling.searchedTooLong - broadcast_interval_secs), the GPS state goes ACTIVE->HARDSLEEP, then immediately HARDSLEEP-ACTIVE :)

If it's " 0s until next search" we should probably not sleep.

### Relevant log output

```Shell
Couldn't publish a valid location: didn't get a GPS lock in time.

DEBUG | ??:??:?? 1132 [GPS] Took 60s to get lock

DEBUG | ??:??:?? 1132 [GPS] Predicting 60s to get next lock

DEBUG | ??:??:?? 1132 [GPS] 0s until next search

DEBUG | ??:??:?? 1132 [GPS] gps_update_interval >= 406s needed to justify hardsleep

INFO | ??:??:?? 1132 [GPS] GPS power state moving from ACTIVE to HARDSLEEP

DEBUG | ??:??:?? 1132 [GPS] publishing pos@0:2, hasVal=0, Sats=0, GPSlock=0

DEBUG | ??:??:?? 1132 [GPS] onGPSChanged() pos@0 time=0 lat=0 lon=0 alt=0

INFO | ??:??:?? 1132 [GPS] updatePosition LOCAL pos@0 time=0 lat=0 lon=0 alt=0

DEBUG | ??:??:?? 1132 [GPS] Setting local position: lat=0 lon=0 time=0 timestamp=0

DEBUG | ??:??:?? 1132 [GPS] Node status update: 69 online, 69 total

INFO | ??:??:?? 1137 [GPS] GPS power state moving from HARDSLEEP to ACTIVE

DEBUG | ??:??:?? 1137 [GPS]
```

**Comment by todd-herbert** [comment]
I think this discussion (https://github.com/meshtastic/firmware/issues/4340#issuecomment-2254327501) did come up after #4161, although I think you're probably right that something isn't working entirely correctly here either. I wasn't particularly clear either on exactly what is meant to happen in this situation.
