### ISSUE TITLE
[Feature Request]: Is there an option on/off bluetooth with q10 bb? 

### ISSUE THREAD

**Issue by sim1988son** [meshtastic/firmware#4687]
### Platform

ESP32

### Description

I'm searching through the entire program/code and I can't find the on/off bluetooth option from the device position?

**Comment by todd-herbert** [comment]
I think #4977 does a lot of the ground-work for this, but I think it probably only adds the hotkey for the M5Stack CardKB. 
It looks like Q10 BB / T-Deck keyboard would each need a few lines of code added to `input/kbI2cBase.cpp` (and someone to test).

**Comment by hayschan** [comment]
Is the open source hardware Blackberry keyboard adapter boar [solderparty/pmod_bbq10_keyboard](https://github.com/solderparty/pmod_bbq10_keyboard) supported by Meshtastic now?

![image](https://github.com/user-attachments/assets/3ebfe83e-e3d9-4012-b21c-54a38b97320e)
