### ISSUE TITLE
[Bug]: Heltec T114 Compass Size is too Big

### ISSUE THREAD

**Issue by Technologyman00** [meshtastic/firmware#4688]
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

2.5.0e470619

### Description

Just anytime the N is at the top of the screen it gets cutoff and barely visable
![PXL_20240911_181134744](https://github.com/user-attachments/assets/02e50d4e-df28-4225-9e23-1f8bd14ff50d)

**Comment by Szetya** [comment]
Perhaps a solution might be. I had a similar problem with the heltec vision master e290.
https://github.com/meshtastic/firmware/pull/4689
