### ISSUE TITLE
[Bug]: T-Echo BME 280 not functional on 2.5.09ac0e26 Alpha firmware if updated with telemetry off

### ISSUE THREAD

**Issue by Json-181** [meshtastic/firmware#4693]
### Category

Serial, Other

### Hardware

T-Echo

### Firmware Version

2.5.09ac0e26 Alpha

### Description

Node had Environmental telemetry initially off, updated from 2.3.15deb7c27 Beta to 2.5.09ac0e26 Alpha. went to enable env. telemetry, but the telemetry update would not take. flashed back to 2.4.3.91d6612 Alpha, and was able to in enable the env. telemetry. Then processed to flash up to 2.5.09ac0e26 Alpha. telemetry settings stayed and are functional.

**Comment by caveman99** [comment]
I can't repro this. The Config interface changed from 2.4.x to 2.5.0 - you probably tried to set the value with an app that didn't understand the 2.5.0 format of config yet.
