### ISSUE TITLE
[Bug]: Heltec T114 HW_VENDOR is set to generic nrf52840dk

### ISSUE THREAD

**Issue by dahanc** [meshtastic/firmware#4714]
### Category

Hardware Compatibility

### Hardware

Heltec Mesh Node T114

### Firmware Version

2.5.0.9ac0e26

### Description

The app shows Heltec T114 nodes as "nrf52840dk" (such as in the node list page and on the device connection page: "Connected to radio (nrf52840dk 2.5.0.9ac0e26)"). It looks like this is because while there's a specific [HW_VENDOR definition](https://github.com/meshtastic/firmware/blob/8893529653cb23060f88f3ff56b092e5291facac/src/platform/esp32/architecture.h#L168) for the T114, it's in the platform/esp32/architecture.h file. Seems like it should be in [platform/nrf52/architecture.h](https://github.com/meshtastic/firmware/blob/8893529653cb23060f88f3ff56b092e5291facac/src/platform/nrf52/architecture.h) instead.

**Comment by dahanc** [comment]
Also, https://github.com/meshtastic/firmware/blob/master/boards/heltec_mesh_node_t114.json has `"extra_flags": "-DARDUINO_NRF52840_PCA10056 -DNRF52840_XXAA",`. Should `-DARDUINO_NRF52840_PCA10056` be there?

**Comment by thebentern** [comment]
Good catch. We must have missed this in the initial PR from Heltec.
