### ISSUE TITLE
[Bug]: build dependency adafruit-nrfuitil.exe flagged by AV software

### ISSUE THREAD

**Issue by powersjcb** [meshtastic/firmware#4737]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

main

### Description

adafruit-nrfuitil.exe flagged by AV software

Blocks firmware dev work on any machine with locked down AV.

https://www.virustotal.com/gui/file/9637a4d099f4a99cbbdfb14142345776582dfbd11d4f357748055b75006ac8c6/details

Related issue https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/424 The fix seems to be using a different version of the library. TBD if that actually fixes the root cause or if the virus scan definitions just don't have the checksums for the latest master builds. :-\

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/472b3184-ad75-48aa-9296-87cdc9e9a7b2">

**Comment by powersjcb** [comment]
It generally sounds like this is an issue bc virus profiles commonly bundle python code into an .exe (as this dependency has)

Almost certainly a false positive, but it would still be nice to figure out a way to resolve this.

**Comment by garthvh** [comment]
What antivirus triggered the false positive? They all have a way to submit software, I have done windows defender for the old desktop flasher.

**Comment by powersjcb** [comment]
Multiple vendors are flagging it as malware per VirusTotal
* Sentinel One
* [Bkav Pro](https://www.bkav.com/bkav-pro)
* Skyhigh (SWG) (Zillya) [form to report false positives](https://www.avira.com/en/analysis/submit)
