### ISSUE TITLE
[Bug]: Detection sensor documentation inaccuracy

### ISSUE THREAD

**Issue by augustozanellato** [meshtastic/firmware#4753]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.4.2.5b45303

### Description

Detection sensor documentation says that state changes are sent to the mesh (https://meshtastic.org/docs/configuration/module/detection-sensor/#minimum-broadcast-interval), but in fact only transitions to not_triggered->triggered are broadcast.
There are two ways to fix this imho:
- make docs reflect actual behavior
- add support for sending a single `state: 0` on transition triggered->not_triggered, maybe gated behind a config option.
For my use case i'd probably prefer the 2nd way, if that's ok I can make a PR implementing that.

**Comment by caveman99** [comment]
Thanks for offering a solution to this, Pull Requests are welcome :-)
