### ISSUE TITLE
[Bug]: Heltec Wireless Tracker v1.1 Serial non-responsive after some time (sleep?)

### ISSUE THREAD

**Issue by 65a** [meshtastic/firmware#4758]
### Category

Serial

### Hardware

Heltec Wireless Tracker

### Firmware Version

2.5.0.9ac0e26

### Description

Serial works right after boot. If I leave it unattended for some time, and then try to connect serial, the serial terminal hangs and nothing is printed. It seems like the peripheral may be in a bad state after sleep or something.

### Relevant log output

```Shell
n/a (that's the problem)
```

**Comment by fifieldt** [comment]
testing.
* 30mins : OK

**Comment by 65a** [comment]
An easier way to reproduce here with two recent boards, is to let them boot and attach to /dev/ttyACM later. They seem to stay working if you attached serial "early" enough.

**Comment by fifieldt** [comment]
ah, good to know.

**Comment by fifieldt** [comment]
Hmm. I left one overnight and it came up OK. Trying again.

**Comment by 65a** [comment]
Interesting, thanks for trying. I will try a different computer/terminal emulator/cable, worried there's a USB power saving issue, or something else weird going on, but I've used the same machine extensively for embedded dev (e.g. t-beam works fine)

**Comment by fifieldt** [comment]
No problems - intermittent issues are hard!

Just put on the latest master and ran for an hour and it was still fine.

**Comment by caveman99** [comment]
> Interesting, thanks for trying. I will try a different computer/terminal emulator/cable, worried there's a USB power saving issue, or something else weird going on, but I've used the same machine extensively for embedded dev (e.g. t-beam works fine)

Difference could be T-BEam uses a hardware UART/USB Chip, while the Wireless Tracker uses a software UART from the ESP32-S3 CPU.

**Comment by 65a** [comment]
@fifieldt I flashed HEAD and I can't seem to reproduce this anymore locally, so that seems good. `2.5.0.9ac0e26` is still the alpha on flasher.meshtastic.org, with the serial issues it was quite hard to flash anything else, 1200bps reset was absolutely required before anything, including esptool. So if anyone else encounters this, flash a different version after doing 1200bps reset via the web flasher.
