### ISSUE TITLE
[Board]: M5Stack CoreS3 + LoRa868_V1.1 Module

### ISSUE THREAD

**Issue by lboue** [meshtastic/firmware#4768]
### SOC

ESP32

### Lora IC

[SX1276](https://www.semtech.com/products/wireless-rf/lora-connect/sx1276#documentation)

### Product Link

https://shop.m5stack.com/products/lora-module-868mhz-v1-1

### Description

Setup
- [M5Stack CoreS3](https://shop.m5stack.com/products/m5stack-cores3-esp32s3-lotdevelopment-kit)
- [LoRa868_V1.1 Module](https://shop.m5stack.com/products/lora-module-868mhz-v1-1)

### Features
- LCD Screen: 2.0"@320*240 ILITEK [ILI9342C](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/core/ILI9342C-ILITEK.pdf)
- FT6336U touch screen
- Built-in camera, proximity sensor, speaker, power indicator, RTC, I2S amplifier, dual microphone, condenser touch screen, power button, reset button, gyroscope (BMI270)
- TF card slot
- [AW9523B](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/products/core/CoreS3/AW9523B-EN.pdf): 16 Multi-function Led Driver and Gpio Controller
- AXP2101 power management, low power design
  - AXP2101_DO1 for LCD Backlight
    - [AXP2101_Example.ino](https://github.com/lewisxhe/XPowersLib/blob/master/examples/AXP2101_Example/AXP2101_Example.ino)

[Schematic](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/core/K128%20CoreS3/Sch_M5_CoreS3_v1.0.pdf)
![image](https://github.com/user-attachments/assets/063d5595-14ba-4126-a67e-2232913d3f2e)

- [M5StackCoreS3 Power_Class config](https://github.com/m5stack/M5Unified/blob/master/src/utility/Power_Class.cpp#L60-L74)

**Comment by Coopersmith-24601** [comment]
It's already being worked on.  I personally can't hardly wait to see it.  It's going to be an incredibly interesting opportunity to add a bajillion different types of sensors.

**Comment by lboue** [comment]
Do you know who's working on it? I was thinking of starting too.

**Comment by Coopersmith-24601** [comment]
Yes, NM.Patriot over on the Discord.

https://discord.com/channels/867578229534359593/931765413350613052/1285356293485494375

**Comment by lboue** [comment]
Thanks

**Comment by lboue** [comment]
M5Stack CoreS3 has AXP2101 power management like [tbeam-s3-core](https://github.com/meshtastic/firmware/blob/master/variants/tbeam-s3-core/variant.h) variant.

**Comment by lboue** [comment]
### AXP2101 usage
|           |M5Stack<BR>CoreS3  |           |
|:---------:|:--------------------:|:-----------------:|
| ALDO1     |VDD 1v8            | ALDO1     |
| ALDO2     |VDDA 3v3           | ALDO2     |
| ALDO3     |CAM 3v3            | ALDO3     |
| ALDO4     |TF 3v3             | ALDO4     |
| BLDO1     |AVDD               | BLDO1     |
| BLDO2     |DVDD               | BLDO2     |
| DLDO1/DC1 |LCD BL             | DLDO1/DC1 |
| DLDO2/DC2 | ---               | DLDO2/DC2 |
| BACKUP    |RTC BAT            | BACKUP    |

**Comment by Coopersmith-24601** [comment]
So, that's it then.  It just dies?

Sadness.
