### ISSUE TITLE
[Bug]: 2.5.1 random reboots on RAK and Station G2

### ISSUE THREAD

**Issue by smarsh-biolinq** [meshtastic/firmware#4833]
### Category

Hardware Compatibility, BLE

### Hardware

Rak4631, Station G2

### Firmware Version

2.5.1

### Description

On both units, i completely reset the install, and it will randomly reboot. I notice it when on BLE, but i am not certain it is not happening when not connected to BLE. Had to revert back to 2.5.0

**Comment by remowashere** [comment]
Same on Seeed Sensecap T1000 and T-Echo, but reboots only (seems to) happen when connected via BT (latest iOS app).

**Comment by thebentern** [comment]
Feel like trying an experimental build? This resolved the issue for me.
https://github.com/meshtastic/firmware/actions/runs/10999713818

**Comment by smarsh-biolinq** [comment]
> Feel like trying an experimental build? This resolved the issue for me. https://github.com/meshtastic/firmware/actions/runs/10999713818

Hi There, Thank you! i was looking at that build and was thinking of trying it as well... Thanks for the tip! BTW, aren't they all experimental builds at this point? ;-)

**Comment by remowashere** [comment]
> Feel like trying an experimental build? This resolved the issue for me. https://github.com/meshtastic/firmware/actions/runs/10999713818

Can confirm, on all mentioned devices this firmware works without a problem 👍

**Comment by thebentern** [comment]
Closed with #4834
