### ISSUE TITLE
[Housekeeping]: Get PR artifacts (posted in comments) working again

### ISSUE THREAD

**Issue by thebentern** [meshtastic/firmware#4838]
### Platform

other

### Description

@jp-bennett mentioned this https://github.com/PicoCentauri/comment-artifact maybe?

**Comment by thebentern** [comment]
Tagging @scruplelesswizard as well.

**Comment by scruplelesswizard** [comment]
[Relevant Workflow](https://github.com/meshtastic/firmware/blob/c442cd7267820681a2259d5b5b4531370af2377c/.github/workflows/main_matrix.yml#L219-L229)

**Comment by thebentern** [comment]
> [Relevant Workflow](https://github.com/meshtastic/firmware/blob/c442cd7267820681a2259d5b5b4531370af2377c/.github/workflows/main_matrix.yml#L219-L229)

One strategy we can look at, if we can't get an action that "does it all" like the existing one, is to break it up into a commit and push to the artifacts repo and then comment step separately, which we know works fine.
