### ISSUE TITLE
[Enhancement]: Disable onboard buzzer on wakeup

### ISSUE THREAD

**Issue by battlehax** [meshtastic/firmware#4844]
### Platform

ESP32

### Description

On devices with an onboard buzzer in their firmware, like the T1000-e, when the device wakes to transmit in SENSOR or TRACKER roles (possibly with other power settings?) it plays the bootup tune.
I brought this up on discord and @caveman99 mentioned that I should open a ticket because it was "counter productive" for these roles and I agree, it's likely an unintended edge-case. 
It would be nice to have either a setting to disable the bootup tune, or possibly, detect when waking with these roles enabled and know not play it.
I dunno about others, but I would be happy if my backpack didn't sing every 30 minutes :)

**Comment by caveman99** [comment]
yes, my idea was to skip the bootup tone on those 2 roles that only wake the device periodically.
