### ISSUE TITLE
[Bug]: GPS going to hardsleep even though update interval set to 180 seconds

### ISSUE THREAD

**Issue by b8b8** [meshtastic/firmware#4889]
### Category

Hardware Compatibility

### Hardware

Seeed Card Tracker T1000-E

### Firmware Version

2.5.2

### Description

The hardware GPS on my T1000E immediately goes into hardsleep, even when the update interval is set to 180 seconds. This i believe is causing the GPS to never have time to get a valid position. When sharing phone location (android) with the device, positions are updated and sent out correctly. 

### Relevant log output

```Shell
WARN | 16:56:20 306 [GPS] Couldn't publish a valid location: didn't get a GPS lock in time.
DEBUG | 16:56:20 306 [GPS] Took 60s to get lock
DEBUG | 16:56:20 306 [GPS] Predicting 60s to get next lock
DEBUG | 16:56:20 306 [GPS] 119s until next search
DEBUG | 16:56:20 306 [GPS] gps_update_interval >= 406s needed to justify hardsleep
INFO | 16:56:20 306 [GPS] GPS power state moving from ACTIVE to HARDSLEEP
DEBUG | 16:56:20 306 [GPS] publishing pos@0:2, hasVal=0, Sats=0, GPSlock=0
DEBUG | 16:56:20 306 [GPS] onGPSChanged() pos@0 time=1727481380 lat=0 lon=0 alt=0
INFO | 16:56:20 306 [GPS] updatePosition LOCAL pos@0 time=1727481380 lat=0 lon=0 alt=0
DEBUG | 16:56:20 306 [GPS] Setting local position: lat=0 lon=0 time=1727481380 timestamp=0
```

**Comment by GUVWAF** [comment]
Seems to be because `softsleepSupported` is false, the `gps_update_interval >= 406s needed to justify hardsleep` is a bit misleading.
