### ISSUE TITLE
[Bug]:  Strange artefacts on Message delivery confirmation page

### ISSUE THREAD

**Issue by lupusworax** [meshtastic/firmware#4902]
### Category

Other

### Hardware

Heltec Mesh Node T114

### Firmware Version

2.4.3 and newer

### Description

After Sending a Message with canned messages or remotely over phone, confirmation message that message got delivered shows with strange artefact on the bottom of the screen. 
![1727638072909](https://github.com/user-attachments/assets/1e21fd0f-3d6d-47e1-bb54-57ae4a65ada7)

**Comment by todd-herbert** [comment]
If I remember correctly, there's another line of text that shows up there, but probably the dimensions of the T114's display are confusing it
