### ISSUE TITLE
[Feature Request]:  Helltec WSL v3 oar any display less module : add  option to set display to enables

### ISSUE THREAD

**Issue by LanWolf** [meshtastic/firmware#4947]
### Platform

ESP32

### Description

On my Heltec wireless stick lite v3 I want to use. An 1.3 oled screen. Sadly it wil not work because in the build is screen=0
Would t be possible to change this, so an external screen can be used if wanted ?
Even better would be in the display options to be able to set if you want to use  the screen on any device, with or without standard display mounted.

**Comment by HarukiToreda** [comment]
what pins did you hook up the screen? i have a wsl with an oled attached with no issues
