### ISSUE TITLE
[Bug]: S&F not working

### ISSUE THREAD

**Issue by cracky22** [meshtastic/firmware#4961]
### Category

Other

### Hardware

T-Beam, Heltec V3

### Firmware Version

2.5.0.9ac0e26

### Description

From FW 2.5, S&F does not work if the clients also have FW 2.5 or higher, because direct messages go out via a fictitious channel 7 or 8. That's why the S&F server acknowledges with "** S&F - Not available on this channel.". However, with nodes with a key symbol (uses PKI), you cannot send on another channel, PKI is always used. I think one of you has an account on GitHub if I remember correctly. Thank you. Oh well, the solution would be to allow or implement it in the PKI direct channel.

**Comment by GUVWAF** [comment]
PKI packets use channel 0, so if that is the public channel on the S&F server, it indeed will not allow you to request the history. 
S&F is meant to be used on private channels only. If you remove the public channel on the S&F server, it should work.
