### ISSUE TITLE
[Bug]: Store & Forward (S&F) if server and client both have firmwear 2.5 and over S&F fails with ** S&F - Not available on this channel

### ISSUE THREAD

**Issue by adingbatponder** [meshtastic/firmware#4962]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.5

### Description

When the S&F server node and client node **both** have firmwear 2.5 and over
then it appears that S&F always fails with error
 ** S&F - Not available on this channel
Why?

**Comment by garthvh** [comment]
Store and forward is not available on the default channel key, you need to use a private channel if you want store and forward

**Comment by adingbatponder** [comment]
We are testing this in Munich and I posted the result of tester that said that 2.5 does not do S&F even if you do not use the default channel when both nodes are 2.5.

**Comment by GUVWAF** [comment]
I just tested this with the S&F server and a client on 2.5. After setting a random PSK (`meshtastic --no-time --ch-set psk random --ch-index 0`), I can request history.

**Comment by adingbatponder** [comment]
The person testing this said that he had to make, in the S&F node, the channel 0 be the channel with a non-default PSK, and the client nodes could have the normal order with channel 0 being LongFast, and then all was well. (This was different in 2.4 I think, where there was no such requirement, if that is indeed a requirement. )We are still perplexed as to how to advise the folks here in Munich to set up their S&F nodes for sure to work irrespective of which firmwear version is on their S&F client and irrespective of what the clients are running.

**Comment by GUVWAF** [comment]
To get it to work on all versions, use it only on private channels.
