### ISSUE TITLE
[Bug]: AHT20 sensor not reporting

### ISSUE THREAD

**Issue by Donnie650** [meshtastic/firmware#4975]
### Category

Hardware Compatibility

### Hardware

Heltec V3

### Firmware Version

2.5.5.e182ae7

### Description

Adafruit AHTX0@^2.0.5
This library is no longer working. Started on 2..5.0, no issue on 2.4.3. Sensor no longer reports.

**Comment by b8b8** [comment]
I have also noticed that the sensor below no longer reports humidity.

![image](https://github.com/user-attachments/assets/8f288481-fd09-4785-8a62-06e529fba2b5)

**Comment by Donnie650** [comment]
I am using this sensor also. BMP280 reports ok but AHT20 does not report.

**Comment by b8b8** [comment]
https://github.com/meshtastic/firmware/issues/3498
