### ISSUE TITLE
[Bug]: T-Deck does not wake up from light sleep via trackball button press

### ISSUE THREAD

**Issue by thebentern** [meshtastic/firmware#5021]
### Category

Other

### Hardware

T-Deck

### Firmware Version

2.5.X

### Description

T-Deck does not wake up from light sleep via trackball button press. This could affect some other hardware, but I have not witnessed it on the Heltec V3 for instance. 
The logs indicate that the LoRA interrupt gpios are registered but no buttons, so perhaps something shook loose in a recent wake up from sleep change.

**Comment by caveman99** [comment]
Can you add a debug log print? - err, nevermind ;-)

**Comment by thebentern** [comment]
Could not reproduce this issue on T-Deck plus. I suspect broken screen T-Deck is not a good test device
