### ISSUE TITLE
[Feature Request]: add "none" to rebroadcast mode for all* roles as a configurable option

### ISSUE THREAD

**Issue by b8b8** [meshtastic/firmware#5030]
### Platform

Cross-Platform

### Description

Right now the only role that truly doesnt participate in meshing is client_mute. 

I believe there should be a "no rebroadcast" option added to the drop-down list so that at least sensor and tracker role can use this.

A scenario where you have a room full of powered sensors or a single powered (always awake) weather station would benefit from the higher telemetry priority in the sensor role while still not wanting to contribute to meshing other packets and cause congestion. Currently if there is high channel utilization a client_mute device would stop sending or scale telemetry. This would mean a weather station would never be able to pass on data to the rest of the busy mesh. 

The same could can be said for always powered (car?) trackers that prioritize position data but we still dont want to participate in meshing. 

Client_Hidden_**mute** would also be configurable if this option was added.

**Comment by thebentern** [comment]
I like this idea. Prevents creation of unnecessary roles.

**Comment by b8b8** [comment]
yup, and i really like the idea of options to make everything "quieter" on the mesh.

**Comment by fifieldt** [comment]
Error if it's enabled on router or repeater roles?

**Comment by b8b8** [comment]
> Error if it's enabled on router or repeater roles?

yes that makes sense or at least greyed out on the two apps.

**Comment by caveman99** [comment]
@thebentern added this before i saw you took this :-) https://github.com/meshtastic/protobufs/pull/599
