### ISSUE TITLE
[Bug]: Web client not bundled with 2.5.5 release served via Web Flasher

### ISSUE THREAD

**Issue by todd-herbert** [meshtastic/firmware#5035]
### Category

WiFi

### Hardware

Not Applicable

### Firmware Version

2.5.5.e182ae7

### Description

Discord user tenhorac reports that the 2.5.5 build served by the web flasher does not include the web client, instead showing the `Web server is running.` message. I can confirm that this is also the case with the 2.5.5 build served for Wireless Paper.

Versions 2.5.4 and 2.5.6 are both working correctly; it seems that only 2.5.5 was affected.

### Relevant log output

```Shell
[HTTPS:I] New connection. Socket FID=52
[HTTPS:I] Request: GET / (FID=52)
[169432][E][vfs_api.cpp:105] open(): /littlefs/static/index.html does not exist, no permits for creation
[169443][E][vfs_api.cpp:105] open(): /littlefs/static/index.html.gz does not exist, no permits for creation
[169454][E][vfs_api.cpp:105] open(): /littlefs/static/index.html.gz does not exist, no permits for creation
WARN  | 12:40:47 169 [WebServerThread] File not available - /static/index.html.gz
```

**Comment by thebentern** [comment]
Something perhaps went wrong with the pulling of web build.tar from assets. Since this is resolved upstream in the latest version, ok if I close this and leave an admonition on the 2.5.5 release?

**Comment by caveman99** [comment]
i think we need to fail the build when the pull does not succeed.

**Comment by thebentern** [comment]
> i think we need to fail the build when the pull does not succeed.

I agree. We need to take a look and see if there are any obvious failures in the build logs for the offending release

**Comment by tomaszrondio** [comment]
I am affected by this bug using 2.5.20

**Comment by fifieldt** [comment]
@tomaszrondio , please see: https://github.com/meshtastic/firmware/discussions/5381

**Comment by tomaszrondio** [comment]
Is it even possible to manage this node over wifi?

**Comment by fifieldt** [comment]
Yup! Just flash the firmware at flasher.meshtastic.org, tick the full erase and tick the website button. It'll all work just like it use to.

**Comment by tomaszrondio** [comment]
Beautiful! Thank you

**Comment by Phobos-7** [comment]
Still doesn't work on T-Beam Supreme

Web server is running.
The content you are looking for can't be found. Please see: [FAQ](https://meshtastic.org/docs/software/web-client/).
[admin](http://meshtastic.local/admin)
