### ISSUE TITLE
[Bug]: rak4631 with lan does not open webserver only port 4403

### ISSUE THREAD

**Issue by mogorman** [meshtastic/firmware#5079]
### Category

Other

### Hardware

Rak4631

### Firmware Version

firmware-rak4631-2.5.4.8d288d5 and later 

### Description

I have a rak4631 I setup with ethernet.  but I can only connect to it over the android ip client. I can't get it working with web interface. I tried 2.5.5, and 2.5.6 releases to no luck.

**Comment by Talie5in** [comment]
There is no webserver on the Rak4631 (or any nRF52 based Meshtastic Devices) so the web client (client.meshtastic.org) is not usable over IP, it is only usable over BLE.

As per documentation:
https://meshtastic.org/docs/software/web-client/#http
**```This method of connecting is limited to esp32 devices.```**
