### ISSUE TITLE
[Feature Request]: Implement "Lazy Sending" of telemetry data if Power Saving is enabled

### ISSUE THREAD

**Issue by JumpingCatRabbit** [meshtastic/firmware#5134]
### Platform

ESP32

### Description

Following this (https://github.com/meshtastic/firmware/discussions/5117) it would be great to have some kind of "Lazy Sending" of telemetry data if we are using Power Saving.

Means: if we are in Light Sleep and the LoRa module wakes us up - send waiting telemetry and check if we are hitting some rate limiting per hour.

It's better to get irregular telemetry than none.

**Comment by Dude5101** [comment]
+1

**Comment by garthvh** [comment]
Telemetry is not sent in power saving mode
