### ISSUE TITLE
[Bug]: T-Deck locks up on builds 2.5.7 and 2.5.8

### ISSUE THREAD

**Issue by N1obu** [meshtastic/firmware#5150]
### Category

Hardware Compatibility

### Hardware

T-Deck

### Firmware Version

2.5.7

### Description

Upgraded from 2.5.6 to 2.5.8 and the T-Deck locks up.  Both keyboard and serial interface won't work.  Tried to downgrade to 2.5.7 with the same results.  Downgraded back to 2.5.6 and everything works fine.

**Comment by caveman99** [comment]
is this a T-Deck or a T-Deck Plus?

**Comment by N1obu** [comment]
It's just a regular T-Deck

**Comment by agajdosi** [comment]
I have a similar issue. My non-Plus T-Deck gets stuck and then reboots quite randomly. Happens only when I touch the screen/buttons, when using it via Android app it is stable.

**Comment by N1obu** [comment]
I just tried 2.5.12        Still locks up.     Downgraded back to 2.5.6

**Comment by brad28b** [comment]
Go into your "Power" settings, make sure the option to conserve power if on a limited source ie solar, is turned OFF.

**Comment by thebentern** [comment]
Closed with #5422
