### ISSUE TITLE
[Bug]: iPhone 12 iOS 17.7.1 not detecting BT of Heltec’s new board v3.2

### ISSUE THREAD

**Issue by meekowai** [meshtastic/firmware#5183]
### Category

BLE

### Hardware

Heltec V3

### Firmware Version

2.5.6.d55c08d

### Description

My iPhone 12 mini won’t detect new Heltec board v3.2 in phone’s Settings>Bluetooth. This does not apply to rubbish old LG Spirit Android phone running some expired Lineage OS dated 2018.  
12 mini does support BLE and I had no issues using smart bands with it. Heltec won’t work. May this be related to new board layout?

**Comment by meekowai** [comment]
Could you articulate the reason why it’s being closed?

**Comment by fromthebeanbag** [comment]
If you think this is a software bug, you possibly need to articulate why this is a meshtasic firmware issue and not a hardware issue or an iPhone issue. As I suspect it got closed as it doesn't sound like a meshtasic issue from what you have described.  With the limited information provided, I suspect it's more likely a setting on the iPhone or iphone related.

**Comment by meekowai** [comment]
I know for a fact my iPhone has no issues connecting to any BT/BLE devices. I can connect to smartbands, Casio mudmasters, scales, printers etc with no hassle, just turn on BT and there it is detected. Only having issues with this new heltec. Maybe I’m mistaken.
