### ISSUE TITLE
[Bug]: Telemetry received from transmitters running 2.5.5+ not publishing into MQTT

### ISSUE THREAD

**Issue by evenstephen** [meshtastic/firmware#5218]
### Category

Hardware Compatibility, Other

### Hardware

Rak4631

### Firmware Version

2.5.5+

### Description

I have a stationary node running 2.5.5 publishing messages to a local MQTT server.  I also have a mobile and a solar node all three are Rak4631 hardware.  After upgrading solar + mobile to the newest 2.5.8 firmware I noticed that telemetry messages from those nodes are no longer being published to MQTT even though the Mesh Log shows telemetry was received from those nodes.  Telemetry from other nodes in my area, including one that I know to be running 2.3.13 firmware, are still successfully published to MQTT.  Reverting back to 2.4.2 on the transmitting nodes eliminates the issue.

**Comment by GUVWAF** [comment]
Did you enable "OK to MQTT" in the LoRa settings? It's a new setting since 2.5: https://meshtastic.org/docs/configuration/radio/lora/#ok-to-mqtt
