### ISSUE TITLE
[Feature Request]: nRF52832 support

### ISSUE THREAD

**Issue by Kezii** [meshtastic/firmware#5268]
### Platform

NRF52

### Description

I see that nRF52832 support was removed from this repo in the past

I find that unfortunate, since there are a lot of devices with nRF52832 that can be used

I see that, compiling nRF52840 target and disabling some features, the code can still fit inside an nRF52832

why is it impossible to have the nRF52832 supported?

https://github.com/meshtastic/firmware/issues/3921#issuecomment-2352897199

**Comment by garthvh** [comment]
As it says, not enough resources.

**Comment by Kezii** [comment]
have you even read my message? lol

**Comment by fifieldt** [comment]
Flash. nRF52832 just doesn't have enough.

![image](https://github.com/user-attachments/assets/204b086b-8f43-48ef-912f-8530625b55bc)

**Comment by thebentern** [comment]
Right. We removed support for these because it just wasn't enough resources for Meshtastic and the NRF52840 is only marginally more expensive from a BoM perspective.
