### ISSUE TITLE
[Feature Request]: Define default board's bluetooth name

### ISSUE THREAD

**Issue by CypressXt** [meshtastic/firmware#5296]
### Platform

Cross-Platform

### Description

Hi Hi :wave:,

To ease fleet management, it would be awesome to be able to define board's Bluetooth identifier to match an enclosure distinctive number. Being able to persist this Bluetooth device name through reset would also be very handy.

**Comment by garthvh** [comment]
The ble name always contains the last 4 of the MAC address, so that is what you should put on an enclosure.
