### ISSUE TITLE
[Feature Request]: Add ".local" addresses to isPrivateIpAddress()

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/firmware#5306]
### Platform

Cross-Platform

### Description

[isPrivateIpAddress](https://github.com/meshtastic/firmware/blob/ad214ea42a8c484f1ff90cd76dd58c89408e33fc/src/mqtt/MQTT.cpp#L707) checks for local IP address octets but does not include a check for .local addresses.

**Comment by fifieldt** [comment]
https://datatracker.ietf.org/doc/html/rfc6762

**Comment by fifieldt** [comment]
Just checking, @pdxlocations - do you use this domain for mqtt or know of people that do, or is this more of a request to make the function "complete" ?

**Comment by pdxlocations** [comment]
I had been using, for example: raspberrypi.local to connect to my broker.  I've since changed to using the IP address to take advantage of the iPrivateIpAddress function. 

The feature request is not dire but as you said to make the function "complete".  If we want to honor "All" local addresses adding .local may save a user some frustration.  Alternatively, or in addition to, I'd be happy to write something up for the docs listing the allowable formats.

**Comment by fifieldt** [comment]
I think let's go with the doc solution?

**Comment by esev** [comment]
I've run across a similar issue as well. I have MQTT in a docker container that I refer to with a host name (not a `.local`) that resolves to a RFC 1918 private IP address. It would be nice if the code could check the IP address after mDNS/DNS resolution. But I didn't see any straightforward way to do this.

For now, I've just hacked my local firmware with this one-liner:

```c++
isMqttServerAddressPrivate = true; // isPrivateIpAddress(moduleConfig.mqtt.address);
```

**Comment by fifieldt** [comment]
Yup, I don't think we're going to be able to handle DNS names for this :( Marking this as shut.
