### ISSUE TITLE
[Bug]: HEAP memory leak in recent beta

### ISSUE THREAD

**Issue by LowVoltagePirate** [meshtastic/firmware#5307]
### Category

WiFi

### Hardware

T-Beam

### Firmware Version

2.5.11

### Description

I'm observing a memory leak with my t-beam with mqtt and wifi enabled. After approx 6-12 hours there's no heap memory left, WiFi disconnects and never reconnects, after a power cycle all is good again for those hours. It was fine with 2.4.5

**Comment by karamo** [comment]
FW 2.5.12 new compiled with options` -DDEBUG_HEAP` and `-DDEBUG_HEAP_MQTT`
multiple Heap-Leaks ...
top 2 are T-Beam, bottom left T-Deck, bottom right TLora T3_V1.6.1
![grafik](https://github.com/user-attachments/assets/bed7e210-47c6-40ab-9e74-59572301871d)

**Comment by GUVWAF** [comment]
I found one place where a memory leak would occur when using MQTT. That one should at least be fixed with #5311.

**Comment by karamo** [comment]
> I found one place where a memory leak would occur when using MQTT. That one should at least be fixed with #5311.

I will test it ...

**Comment by karamo** [comment]
the first one is gone, but there are more Heap-Leaks:
see #5316 and #5317

**Comment by derekpurdy** [comment]
what version will this be released in?

**Comment by fifieldt** [comment]
> what version will this be released in?

Probably 2.5.14

**Comment by GUVWAF** [comment]
It is already in 2.5.13.
