### ISSUE TITLE
[Bug]: one more Heap-Leak @Traceroute

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#5317]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.5.12 + fix

### Description

ther is one more Heap-Leak @Traceroute (red signs)
![leakTR](https://github.com/user-attachments/assets/4bf80f7d-d0ea-41fc-9b2f-a494de8e70fb)

**Scenario:**
FW 2.5.12 with fix PR https://github.com/meshtastic/firmware/pull/5311
3 T-Beam local direct with noch connection to other nodes.

**Comment by GUVWAF** [comment]
Is this when sending or receiving traceroutes? Also, might it be it also happens on other packet types like position requests or just text messages?

**Comment by karamo** [comment]
I made Traceroute with MeshSense.
Other actions not tested.

**Comment by karamo** [comment]
At starting Meshsense and connecting via IP to that node, there is a down-peak followd by a jump up of the Heap.
![MeshSense_Start](https://github.com/user-attachments/assets/ded7036d-62cf-4e78-9d19-13a6d99f2dac)

Log of Meshsense:
[MeshSense_Start_IP_4Nodes.zip](https://github.com/user-attachments/files/17715584/MeshSense_Start_IP_4Nodes.zip)

Scenario: 4 T-Beam local direkt active

**Comment by karamo** [comment]
At he 1st DM there is a peak down, followed by up an no permanent Heap-down.
![MEshSense_SendMsg](https://github.com/user-attachments/assets/331a021f-5c9d-419f-89ca-bab5858c9742)
Log: [MEshSense_SendMsg.zip](https://github.com/user-attachments/files/17715820/MEshSense_SendMsg.zip)

**Comment by karamo** [comment]
Sending Traceroute every 30s (FW limit), Heap permanently damaged:
![MeshSense_Send-Traceroute](https://github.com/user-attachments/assets/d2adb99f-d276-4fbe-b67c-2579755eff92)
Log: 
[MeshSense_Send-Traceroute.zip](https://github.com/user-attachments/files/17716076/MeshSense_Send-Traceroute.zip)

**Comment by karamo** [comment]
It seems to me that **TraceRoute** is interrupted if another packet is received in the meantime.

**Comment by karamo** [comment]
after ≈10 mins Heap partially recovered
![MeshSense_Heappartrecover](https://github.com/user-attachments/assets/bb7f1147-4e19-4171-a14a-dee47ffdd6fb)

**Comment by GUVWAF** [comment]
@karamo Many thanks for all the testing. 

Can you try if #5328 fixes it?

**Comment by karamo** [comment]
> Can you try if #5328 fixes it?

Yes, ist running ... wait 1 to 3 hours ...

**Comment by karamo** [comment]
ok, it looks good.
Reboot 2.5.12 + Fix1 + Fix2
Significant points:
picture 1:
19:36:49 - 52428 B - Reboot an heap down with first slope to
19:56:31 - 38424 B - begin 2nd slope to jump up at
20:42:56 - 35884 B ^^
21:17:01 - 40220 B - start of MeshSense (red 1 in 2nd picture)
picture 2:
27:17:41 - 47724 B - maximum following slow down
21:34:43 - 45044 B - start 1st Traceroute every ≈30s no significant Heap-Leak (red 2 in 2nd picture)
![MeshSense_IPconnect](https://github.com/user-attachments/assets/c5dcf47a-5932-4e9b-bd7f-8d11b7ddb679)
![MeshSense_Traceroute](https://github.com/user-attachments/assets/fb29cc87-4b85-41e0-95f2-86b4c354e689)
