### ISSUE TITLE
[New Board]: Programming on LILYGO T-Beam Supreme module using Arduino IDE

### ISSUE THREAD

**Issue by Tanay7** [meshtastic/firmware#5324]
### SOC

ESP32

### Lora IC

SX1262

### Product Link

https://www.lilygo.cc/products/t-beam-supreme-meshtastic?variant=43067943911605

### Description

How can I get the LILYGO T-Beam Supreme (SOC: ESP32-S3FN8) to work with custom code, such as displaying "Hello" on its OLED, generating random numbers, and reading from an externally attached AS7341 spectral sensor, using the Arduino IDE? 
I understand this isn't the standard setup for the Meshtastic firmware, but I need to use the board for other applications as well. 
Previously, I successfully used the LILYGO® TTGO LoRa32 V2.1_1.6 (selected via Tools -> Board -> ESP32 -> TTGO LoRA32-OLED) for various projects, including a random number generator/transmitter and an MMC5603 magnetometer Lora transmitter/receiver. 
I am able to upload similar code to the T-Beam Supreme by selecting 'ESP32S3 Dev Module' in Tools -> Board, as there is no specific option for the T-Beam Supreme in the Boards Manager. 
However, after uploading, neither the embedded OLED nor the LED activates, and there is no output in the Serial Monitor. Could you please help me troubleshoot this issue? Additionally, it would be great if you could add a T-Beam Supreme board option in the Arduino IDE's Boards Manager, along with some ready-made sketches—for example, to retrieve and display data from the embedded BME280/QMI8658 sensors on its OLED. 

For reference, here are some sample codes that worked with the LILYGO® TTGO LoRa32 V2.1_1.6: 
https://github.com/Tanay7/IoT

**Comment by caveman99** [comment]
Please refer to the sample code at https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/

Support for non-meshtastic code is out of scope of this project.
