### ISSUE TITLE
[Bug]: Input field validation - Section Power

### ISSUE THREAD

**Issue by Franselbaer** [meshtastic/firmware#5335]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.5.11

### Description

If you send an empty entry for the field "Shutdown on battery delay (seconds)" in power section via admin channel, the input field seems not to be validated but saved, which leads to constant reboot brick.

Should be set to "0" if empty (or unclear, e.g. not int 0-999999 or similar).

### Relevant log output

```Shell
None
```

**Comment by thebentern** [comment]
0 is empty for this protobuf field. The firmware actually ignores it if it is not above zero. I can put some minimum value coercion in there but seems like you have a different issue occurring. Can you post your --info?
