### ISSUE TITLE
[Feature Request]: Multiple WiFi network saved

### ISSUE THREAD

**Issue by RadioactivePotato** [meshtastic/firmware#5339]
### Platform

ESP32

### Description

For example, if I am at home, I would want it to connect to network1, 

but if it cannot connect to network1, it will connect to network2

This can be useful if I want the node to connect to my home network when I'm at home, but connect to my hotspot when I am away.

**Comment by thebentern** [comment]
Sadly there is not enough space in the network config to do this. It is already one of our largest config sections. Probably a good cases for a custom firmware compile
