### ISSUE TITLE
Distance in Environment Telemetry is not actually serialized into protobufs

### ISSUE THREAD

**Issue by ndoo** [meshtastic/firmware#5349]
Hi @caveman99, I think despite the addition of ultrasonic distance sensing during https://github.com/meshtastic/firmware/pull/3678 , /src/serialization/MeshPacketSerializer.cpp and possibly the nRF version of this file would need the meshtastic_PortNum_TELEMETRY_APP section updated to actually put the distance out into transmitted protobufs.

**Comment by caveman99** [comment]
The actual protobuf has the data field, like intended in the original PR, the files you mention just serialize into the JSON export format and only carry a subset of the available data. Looks like nobody needed that data point on the JSON yet.
