### ISSUE TITLE
[Bug]: Device does not save settings

### ISSUE THREAD

**Issue by liquidraver** [meshtastic/firmware#5354]
### Category

Other

### Hardware

Station G2

### Firmware Version

2.5.13

### Description

Hi!

After full wipe and reconfig, the device forgets fixed position and long/short name after a reboot.

### Relevant log output

```Shell
INFO  | ??:??:?? 6 Init NodeDB
ERROR | ??:??:?? 6 Could not open / read /prefs/db.proto
WARN  | ??:??:?? 6 Devicestate 0 is old, discard
INFO  | ??:??:?? 6 Install default DeviceState
```

**Comment by garthvh** [comment]
If you do a full wipe nothing is retained

**Comment by fifieldt** [comment]
We've recalled firmware version 2.5.13 due to this issue. Please downgrade to 2.5.12 and wait for a new version :)
