### ISSUE TITLE
[Bug]: RAK 11310 Ethernet port not working 

### ISSUE THREAD

**Issue by legobrick2x4** [meshtastic/firmware#5408]
### Category

Hardware Compatibility

### Hardware

Rak11310

### Firmware Version

2.5.11.8e2a3e5 Beta

### Description

RAK 11310 does not work with the Ethernet interface. 
I've tried both alpha and beta versions while installing the flash nuke in-between to eliminate possible variables. I know it isn't hardware related as I swapped the core for my RAK 4631 and it worked fine.

I cannot find anything saying it is incomparable so I believe this is a big of some kind. 

If you need more information please let me know.

**Comment by caveman99** [comment]
The Rak 11310 is not compatible with the Ethernet interface. When this code was written, the rak11310 didn't exist yet.
