### ISSUE TITLE
[Bug]: Store & Forward - Android - Direct Message - replies not permitted

### ISSUE THREAD

**Issue by pagex** [meshtastic/firmware#5427]
### Category

Other

### Hardware

T-Beam, T-Beam S3

### Firmware Version

2.5.13

### Description

Android client -> select S&F node -> Direct Message -> opens up new chat screen -> but preselects "0 - LongFast" despite client / server has private channels shared, sending SF replies with not permitted on public channel. No other way to change channel or direct message over private channel.
This works if first channel is private one and public is second then system preselects correct private channel on direct message.

**Comment by fifieldt** [comment]
Hi, thanks for writing in.

For bugs with the Android app, the best tracker to use is: https://github.com/meshtastic/Meshtastic-Android
