### ISSUE TITLE
[Feature Request]: SX1262 - optimize the PA clamping  threshold with TxClampConfig register.

### ISSUE THREAD

**Issue by meekowai** [meshtastic/firmware#5430]
### Platform

Cross-Platform

### Description

Please implement workaround for PA Tx Clamping as introduced in section15.2 of DS_SX1261-2_v1.2 datasheet.

15.2 Better Resistance of the SX1262 Tx to Antenna Mismatch

15.2.1 Description
 The SX1261/2 platform embeds a Power Amplifier (PA) clamping mechanism, backing-off the power when over-voltage 
conditions are detected internally. This method is put in place to protect the internal devices and ensure long-term 
reliability of the chip. Considering a high-power operation of the SX1262 (supporting +22dBm on-chip), these “clamping” 
devices are overly protective, causing the chip to back-down its output power when even a reasonable mismatch is 
detected at the PA output. The observation is typically 5 to 6 dB less output power than the expected.
Note: using the described workaround will improve the chip functionality, but is not required to ensure long-term reliability, 
which is guaranteed with or without workaround.

15.2.2 Workaround
 On the SX1262, during the chip initialization, the register TxClampConfig should be modified to optimize the PA clamping 
threshold. Bits 4-1 must be set to “1111” (default value “0100”).
 This register modification must be done after a Power On Reset, or a wake-up from cold Start.
 The following pseudo-code can be used as a reference to implement the fix:
`value = ReadRegister@0x08D8;`
`value = value | 0x1E;`
`WriteRegister(value)@0x08D8;`

**Comment by lyusupov** [comment]
It is already applied by use of the **RadioLib** component:

<br>


<img width="656" alt="image" src="https://github.com/user-attachments/assets/986c45d3-6b40-4bae-b37f-2f1adac86029">
