### ISSUE TITLE
[Bug]: Altitude keeps resetting to 0 when using Fixed Position

### ISSUE THREAD

**Issue by lagunacomputer** [meshtastic/firmware#5438]
### Category

Other

### Hardware

DIY

### Firmware Version

2.5.13.1a06f88

### Description

When using Fixed Position, and manually typing in a ## in meters in the (at least) the Android app, the Altitude resets to 0 after a few seconds.  Both in app Nodes detail section,  and in Radio Configuration -> Position.

Observed Conditions:
DIY tbeam clone with no GPS and GPS Disabled set.
using ##.##### number of digits for Long and Lat
2 digits for Altitude (ie 80)
2.5.13.1a06f88 fw
Defined in userPrefs.h when building:
#define USERPREFS_FIXED_GPS
#define USERPREFS_FIXED_GPS_LAT 33.#####
#define USERPREFS_FIXED_GPS_LON -117.#####
#define USERPREFS_FIXED_GPS_ALT 74

I also noticed that when defining to 5 decimal places in LON, that the Android app added a bunch of 99999's to the value ie -117.12345 became -117.123459999999

**Comment by lagunacomputer** [comment]
This issue may have gone away w 2.5.14. I am not seeing it anymore since updating today.

**Comment by fifieldt** [comment]
Thanks for letting us know!
