### ISSUE TITLE
[Bug]: Llilygo T-Deck wifi dropouts due to default power settings

### ISSUE THREAD

**Issue by brad28b** [meshtastic/firmware#5440]
### Category

WiFi

### Hardware

T-Deck

### Firmware Version

2.5.7

### Description

When I updated the firmware (and doing a full erase at the same time) on my Llilygo T-Deck to 2.5.*, the option under the "Power" config called "Select if powered from a low-current source (i.e. solar), to minimize power consumption as much as possible" is turned ON by default. With most other hardware I use (RAK4631, Heltec V3 etc), this is OFF by default. This option  being on causes the Wifi to only remain connected for around 10 secs at a time, then it disconnects for 10 secs (unreachable via ping), then reconnects, continually. I think this option should be OFF by default, optionally turned on, as it took me days to work out what was going on.

**Comment by garthvh** [comment]
I agree this is a bad default for the non fancy UI that most people are configuring with a phone, I get a lot of complaints about having to press the trackball to get it to reconnect
