### ISSUE TITLE
How to make a hex (boot+app)

### ISSUE THREAD

**Issue by DanielCao0** [meshtastic/firmware#5441]
### Platform

NRF52

### Description

At present, platform only app hex , how to make a hex (app+boot), can be used for a large number of production JLINK download

**Comment by fifieldt** [comment]
Something like?

bin/mergehex -m bin/s140_nrf52_7.3.0_softdevice.hex wio-sdk-wm1110/firmware.hex -o firmware.hex

**Comment by DanielCao0** [comment]
> s140_nrf52_7.3.0_softdevice

PS F:\Meshtap\firmware\bin> mergehex.exe -m s140_nrf52_7.3.0_softdevice.hex ..\.pio\build\rak_wismeshtap\firmware.hex -o factory.hex
Parsing input files.
Merging file "s140_nrf52_7.3.0_softdevice.hex" into output.
Merging file "firmware.hex" into output.
Overlapping segments detected at address 155648.ERROR: The hex files cannot be merged since there are conflicts.
PS F:\Meshtap\firmware\bin>

**Comment by markbirss** [comment]
https://github.com/meshtastic/firmware/blob/37da78919a679a632eea29f4b3d6d1a4cbbd84fb/bin/build-nrf52.sh#L38

**Comment by DanielCao0** [comment]
I want a full hex, including  ( dfu boot+ app + s140 ),  via jlink to a empty chip

**Comment by thebentern** [comment]
Meshtastic doesn't add bootloaders to the firmware hex.
