### ISSUE TITLE
[Feature Request]: Add Bluetooth service to identify Meshtastic devices

### ISSUE THREAD

**Issue by duhow** [meshtastic/firmware#5531]
### Platform

ESP32, other

### Description

Currently devices are only discoverable based on Bluetooth device name pattern.

https://github.com/meshtastic/Meshtastic-Android/blob/f08916764c3b925ca1b974f50d3ab79defefc3cb/app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothRepository.kt#L135

To easily integrate with other servcies (eg. discovering within Home Assistant), we should add a service UUID, manufacturer ID or data.

EDIT: I noticed there is this `MESH_SERVICE_UUID` which I understand should be the target one?

https://github.com/meshtastic/firmware/blob/f81d3b045dd1b7e3ca7870af3da915ff4399ea98/src/BluetoothCommon.h#L9

**Comment by garthvh** [comment]
This is a android choice for backwards compatibility, iOS uses the characteristic guid.
