### ISSUE TITLE
[Bug]: WiFi permanently disconnects after some time when using MQTT, reboot required to fix

### ISSUE THREAD

**Issue by chairmanfaust** [meshtastic/firmware#5559]
### Category

WiFi

### Hardware

Station G2

### Firmware Version

2.5.14

### Description

I have a station G2 acting as an MQTT gateway via wifi. After about a day or two i can no longer use the app to connect via wifi address. My router shows that the device is connected and still has an IP address but it no longer responds to ping. The behavior is identical to a closed bug found here: https://github.com/meshtastic/firmware/issues/4725

**Comment by Matzebhv** [comment]
Same problem here with 2 t-beam supreme. You can try to update to > .14 as it seems that this fixed the problem for some people. For me and others this does not work but is worth the try.
You can also look here -> https://github.com/meshtastic/firmware/issues/5549 and here -> https://github.com/meshtastic/firmware/issues/5458
For me it seems to be an ESP related problem.

**Comment by koliha** [comment]
Spoke too soon in #5458 - I managed 10 days 17hrs of uptime before it exhausted all heap memory and stopped responding.  Looks like a memory leak, probably as outlined in #5549 

Ping was still semi-responsive.  Hitting the http/json page was impossible.  It also dropped off MQTT.

![Screenshot 2024-12-15 at 5 54 40 PM](https://github.com/user-attachments/assets/cfb0c844-0928-427e-9ad5-191df81046e3)
![Screenshot 2024-12-16 at 10 55 34 AM](https://github.com/user-attachments/assets/94979931-1efb-475f-badb-5ba28fd60d40)

**Comment by esev** [comment]
Can you confirm that you are **not** using JSON mode for MQTT and have downlink enabled? If that's correct, I suspect this due to the memory leaks from #5549. If that's not correct, then there is another issue to troubleshoot.

**Comment by chairmanfaust** [comment]
I am using JSON on my mqtt server and have downlink enabled on my primary (longfast) channel as well as 2 other channels 

![Screenshot_20241217_135632_Meshtastic](https://github.com/user-attachments/assets/3984d42b-9c98-49a5-836e-6582010c0e13)

![Screenshot_20241217_142617_Meshtastic](https://github.com/user-attachments/assets/2e80b915-df58-4354-a203-61ddaf17bb82)

**Comment by esev** [comment]
My mistake. I hadn't realized that [MQTT::send subscriptions()](https://github.com/meshtastic/firmware/blob/4edeca5f846024365bbd8855a454d42d2eae4d57/src/mqtt/MQTT.cpp#L409) subscribes to both JSON and protobuf channels. It's probably the same memory leaks from the previously mentioned issue.

**Comment by garthvh** [comment]
JSON functionality in the firmware is in the process of being retired https://github.com/meshtastic/firmware/issues/5507

**Comment by esev** [comment]
@garthvh The memory leak is not in the JSON code-path. #5549 for details; essentially the same bug.

**Comment by EnGamma** [comment]
I'm seeing similar/same symptoms of losing phone-node wifi connection with TLORA_V2_1_1P6 device fw 2.5.11.   I'm sometimes able to reboot the node from another using RF remote administration.   I have 4 identical HW nodes all on fw 2.5.11, but it is affecting 2 nodes more than the others and one node especially.

These symptoms started after fw update from 2.3.10 to 2.5.11.
