### ISSUE TITLE
Turning off WiFi on reboot 

### ISSUE THREAD

**Issue by RichMar** [meshtastic/firmware#5580]
### Platform

ESP32

### Description

Hi, I have a heltec-wsl-v3 and I have both WiFi and Bluetooth enabled in the settings. When I get out of range of my WiFi, the bluetooth doesn't work until I turn WiFi off in the settings. Could an option be added in the WiFi settings so that when the device restarts the WiFi stays off?

**Comment by caveman99** [comment]
You can use either Wifi or Bluetooth reliably. when both are enabled, wifi is preferred. There's no automatic switching or dynamic usage planned, since that would add a ton of overhead to the code.
