### ISSUE TITLE
[Feature Request]: suport for heltec Wireless tracker v1.2

### ISSUE THREAD

**Issue by espssch** [meshtastic/firmware#5602]
### Platform

ESP32

### Description

I order a heltec Wireless tracker, I received a heltec Wireless tracker v1.2 (Htit-tracker v1.2). I contacted heltec. Their reply was :  Almost the same, except that the brands of some components have changed, such as the spring antenna. Will meshtastic  heltec Wireless tracker firmware for v1.1 work on v1.2?

**Comment by garthvh** [comment]
A different spring antenna won't require any firmware changes.
