### ISSUE TITLE
[Feature Request]: Add firmware version to nodeinfo packet

### ISSUE THREAD

**Issue by todd2982** [meshtastic/firmware#5615]
### Platform

NRF52, ESP32, RP2040, Linux Native

### Description

This would be good info to have for many reasons such as troubleshooting, or checking capabilities of the local mesh.  My primary reason for this request is so that it would be part of the JSON data visible through MQTT.  I can use that to track my firmware versions in Home Assistant for local and remote nodes that I manage.

I am aware that only ESP32 nodes can send via JSON, but they also repeat NRF52 boards that have OK to MQTT selected to help gather this info from those systems as well.

If packet size overhead is an issue, this could be encoded to HEX or some other data type that makes sense to the developers.

**Comment by garthvh** [comment]
Depending on security through obscurity should never be your only defense, but broadcasting out the version is also not a best practice either, no need to make life easy for an attacker.

**Comment by thebentern** [comment]
There are already sadly some issues around Node Info (User) packets being quite large with the addition of PKC. I would not be in favor of eating up even more precious bytes for firmware version discovery given that there is no compelling feature surrounding it, other than knowing which of your neighbors are lagging behind on a previous version.
