### ISSUE TITLE
[Bug]: Rangetest module saves 0.00000 as GPS data in the rangetest.csv

### ISSUE THREAD

**Issue by Fastomat** [meshtastic/firmware#5620]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.5.16.f81d3b0 Alpha

### Description

The Range Test module seems to not use live GPS data from the phone, for the **rangetest.csv** file. The .csv contains "0.0000" for rx lat, rx long and distance.

Both nodes are Heltec V3. Used iOS app for GPS location sharing is 2.5.12 (1317)

<ins>To reproduce</ins>

- Node A: sender node, GPS location fixed. Rangetest module Enabled, sender interval 30 seconds.
- Node B: receiver node, mobile. Rangetest module Enabled, sender interval OFF, Save to CSV ON. 
- * Node B receives GPS data via the iPhone app via bluetooth. Settings:
- * Will share your phone GPS location with your node: ON, interval fifteen seconds, smart position OFF.

The rangetest messages are received on node B (seq 1, seq 2...) via the Primary LongFast channel. The node B display shows the correct distance when walking around (e.g. 197m, then 210m, etc.) and arrow so the node is receiving GPS data from the phone. Then I enable Wifi on the receiving node and download the .csv via meshtastic.local/rangetest.csv. That csv has no GPS info about node B's own location.

<ins> GPS fixed setting </ins>
When setting the GPS location fixed on the receiving node B, that GPS info is used for both the node display and saved into the rangetest.csv file. I set it with '_meshtastic --setlat 1.234 --setlon 5.678 --setalt 9 --serial_' to make clear it was fixed.

The first 3 lines are with Node B receiving live GPS from the phone. The last 2 lines are with GPS fixed settings:

<img width="882" alt="image" src="https://github.com/user-attachments/assets/52c2166b-5bf4-4c2c-be91-a58186094e10" />

I don't know which part of the firmware the issue is. But I'm happy to gather more info if required.

Cheers,
Marcel

**Comment by fifieldt** [comment]
Confirmed -- the rx_lat and rx_lon come from GPS Status.

**Comment by fifieldt** [comment]
Looking at RangeTestModule.cpp it calls to GPSStatus for the receiver location. GPS handles fixed position, and GPS positions, but it does not handle phone data that I can see.

**Comment by qhader** [comment]
Hey everyone,
I’ve added temperature and humidity columns to my rangetest.csv file, and I can see the columns are there. But the values are always showing up as 0, even though the data is being sent. The payload seems fine (like seg 1), but the temperature and humidity fields aren’t updating.

Any idea what might be going wrong? Is there something I need to change in the way the data is parsed or written to the CSV?
