### ISSUE TITLE
[Bug]: fix position changes it self

### ISSUE THREAD

**Issue by dg1rue** [meshtastic/firmware#5652]
### Category

Other

### Hardware

T-Lora v2 1.6

### Firmware Version

2.5.15.79da236

### Description

If setting up fixed position and transmitting to device it shows up cotrrect in map but after a few seconds it changes the position by itself. Apparently by a random value for Long and Lat, but then it always comes up with the same (wrong) position.

**Comment by apoger** [comment]
Same on g2 station, heltec v3 and g2 nano.

**Comment by caveman99** [comment]
https://meshtastic.org/docs/configuration/radio/channels/#position-precision
