### ISSUE TITLE
Remove Health telemetry from official release binaries

### ISSUE THREAD

**Issue by thebentern** [meshtastic/firmware#5673]
### Platform

Cross-Platform

### Description

After some internal team discussions, it was determined that the Health telemetry should be excluded from the mainline firmware releases due to some potential legal risk (ala HIPAA compliance), depending on how it is used. It will be macro-guarded and remain available for consumers who wish to build it themselves.

**Comment by Mictronics** [comment]
What is `health telemetry`?

**Comment by thebentern** [comment]
> What is `health telemetry`?

Mostly temperature and heart-rate metrics for now.

**Comment by Mictronics** [comment]
I didn't even know such telemetry exists.
