### ISSUE TITLE
Represent HTTP only features in protobufs so they can be accessed by other connection methods. 

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/firmware#787]
This was suggested by @sachaw during the Meshtastic Dev Conference.

**Comment by garthvh** [comment]
@sachaw I still don't totally understand this one

**Comment by sachaw** [comment]
Yeah, it's not named very clearly.
What it's inferring is that http exclusive features. Range test CSV,  file system browsing etc should be represented with protobufs so they can be accessed over any connection method.

**Comment by garthvh** [comment]
https://github.com/meshtastic/Meshtastic-device/issues/1389#issue-1207732505

**Comment by caveman99** [comment]
I vote for a generic file send/receive over protobufs so we can provision devices by putting proto files into the flash filesystem. One use would be the oem.proto used for a secondary bootlogo and text.

**Comment by garthvh** [comment]
Is this complete @caveman99?

**Comment by caveman99** [comment]
The implementation is done, but there's room for improvement. I think we can close this.
